openebs/mayastor

- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/descriptor/mod.rs
A great pattern in the Rust language is the RAII guards, which ensures a
resource is implicitly managed, preventing acquiring without a correspondent
release. This commit introduces a guard type for the io channel handle, and
replaces one usage of such handle with the guard type.
closes #9
> Add guard type for io channel

- nix/mayastor-overlay.nix
- nix/pkgs/k9s/default.nix
- nix/pkgs/stern/default.nix
see the description of the individual packages for more
information about the tools themselves
> nix: add some use full k8s tooling

- jsonrpc/src/test.rs
- mayastor/src/aio_dev.rs
- mayastor/src/iscsi_target.rs
- mayastor/src/nvme_dev.rs
- mayastor/src/nvmf_target.rs
- mayastor/src/pool.rs
- nix/pkgs/libspdk/default.nix
- shell.nix
This updated our package to v19.1. There are, of course come changes too non public headers but overall its not all that bad.  The structure  of the repo has changes somewhat but this is transparent to our sys crate. 
One of the reasons I personally want this merged so quickly is because of the work done in reset handling.
> mayastor: update to v19.10

- nix/pkgs/mayastor/default.nix
The issue is tricky because nix does not know they are used at runtime,
so it does not include them. The solution is to create a new derivation
with a wrapper shell script around mayastor-agent with properly set PATH.
The derivation is used for image creation then. That makes the dependency
on these utils at runtime explicit.
> mayastor-agent image does not have mkfs and mount commands in PATH

- csi/src/mayastor_svc.rs
- mayastor-test/test_nexus_grpc.js
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- rpc/proto/mayastor.proto
- rpc/proto/mayastor_service.proto
moac will need these methods when feature of multiple replicas
per nexus is implemented.
> New add/remove nexus child method for use by moac.

- mayastor/src/bin/main.rs
- mayastor/src/environment/args.rs
- mayastor/src/environment/env.rs
- mayastor/src/event.rs
- mayastor/tests/nexus_add_remove.rs
- nix/mayastor-overlay.nix
- nix/pkgs/nvmet-cli/default.nix
The target CLI similar in nature when comparing it with the iSCSI target. However, using the CLI is somewhat simpler then echo-ing, and ln-ing yourself to something that works =)
> nix: add nvmet-cli

- mayastor-test/README.md
Trying this again to try to force GitLab to be sensible.
> docs: Add troubleshooting guide to help new developers get started

- .gitlab-ci.yml
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/uring_dev.rs
- mayastor/src/nexus_uri.rs
- mayastor/tests/core.rs
- mayastor/tests/nexus_rebuild.rs
the changes are only applied during test and do not fail the PR so unformatted code can be checked in master...
currently the spdk-sys submodule has ill formatted code... we avoid running the format check against submodules as that should be handled in the respective repos
> cargo fmt changes are not being detected by the linter

- csi/moac/README.md
- csi/moac/crds/mayastorpool.yaml
- csi/moac/crds/mayastorvolume.yaml
- csi/moac/csi.js
- csi/moac/event_stream.js
- csi/moac/index.js
- csi/moac/node.js
- csi/moac/pool_operator.js
- csi/moac/test/csi_test.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/index.js
- csi/moac/test/pool_operator_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.js
- csi/moac/volume_operator.js
- csi/moac/volumes.js
- deploy/moac-deployment.yaml
- deploy/pool.yaml
- doc/volume-operator.md
When the volume is created, volume CRD is created as well with all information about nexus and replicas. It is deleted again when the PVC is deleted.
> Implement k8s volume custom resources

- csi/src/mayastor_svc.rs
- mayastor-test/package-lock.json
- mayastor-test/package.json
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/rebuild.rs
- rpc/proto/mayastor.proto
- rpc/proto/mayastor_service.proto
- test.sh
Support also included for getting rebuild state.
Unit tests added for the rebuild process.
> rebuild: Add stop rebuild support

- doc/etc/README.adoc
- doc/etc/nexus.conf
- doc/etc/target.conf
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_config.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_module.rs
- mayastor/src/target/iscsi.rs
To make life a bit easier, in particular during testing, we want to ability to load or bootstrap mayastor with a given, specific config file.
> Allow nexus configuration from files

- csi/moac/csi.js
- csi/moac/grpc_client.js
- csi/moac/nexus.js
- csi/moac/test/csi_test.js
- csi/moac/test/nexus_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.js
- deploy/storage-class.yaml
This change does not implement sharing of the nexus,
but lays the foundation for that to happen.
Supported nexus protocols are
nbd
nvmf
iscsi
> Facilitate specification of the nexus protocol using CSI.

- mayastor/src/pool.rs
Get the bdev type from the name of the SPDK module via Pool::driver()
and use it when destroying the bdev by deleting the correct bdev type,
and to improve the logging.
> pool: Use base bdev type where appropriate

- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/core/reactor.rs
- mayastor/tests/core.rs
- mayastor/tests/mount_fs.rs
Some refactorings of Jeffry's when he started work on this project.
Also increased timeout of rebuild tests from 2 to 10 seconds.
> CAS-16: Some refactoring for new gRPC

- .github/workflows/build.yaml
- Cargo.lock
- nix/pkgs/mayastor/default.nix
I've ran this several times on my fork and I hope that
with the two cpu args it will be a bit more stable.
> ci: minor fixes

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_label.rs
Refactor disk label writing code to optimise writing of disk labels
-  ie. that labels are only updated if strictly necessary.
Of particular interest is the case when a nexus client is added - with a new disk that has no valid label.
We use the label from existing clients rather than creating a brand new label and then writing it out to all children.
> CAS-146 Minimise writing of disk labels

- .github/workflows/build.yaml
- Cargo.lock
- csi/Cargo.toml
- csi/src/client.rs
- csi/src/server.rs
- mayastor-test/test_common.js
- mayastor-test/test_csi.js
- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor-test/test_replica.js
- mayastor/Cargo.toml
- mayastor/src/bin/main.rs
- mayastor/src/core/env.rs
- mayastor/src/grpc.rs
- mayastor/src/lib.rs
- nix/pkgs/mayastor/default.nix
- test.sh
Mayastor now implements its own gRPC interface,
so that calls no longer have to go via the agent.
> CAS-16: New grpc interface for Mayastor

- .github/workflows/build.yaml
- .github/workflows/moac.yaml
> Add github action for testing moac

- mayastor-test/test_nexus.js
We start a target during some of the tests to use as a replica.
This sometimes starts too late and we fail the test, and subsequently
we fail.
This change simply moves the start of the replica up a bit.
> CI: intermittent failures in test_nexus

- doc/quick.md
> CSI iSCSI updates for quick.md

- csi/moac/csi.js
- csi/moac/test/csi_test.js
Minor change to adjust the test closer to reality and avoid useless parsing of JSON in the code.
> Improved test for changes related to iscsi feature

- mayastor/src/core/reactor.rs
The reactors Future::poll() should not sleep in release builds
> reactor: dont sleep in release builds

- csi/src/client.rs
- mayastor-test/test_cli.js
- mayastor/tests/nexus_metadata.rs
Reworked tabular output
Added nexus child listing facilities
Added more tests
> Further work on mayastor-client

- deploy/README.md
- deploy/moac-deployment.yaml
- deploy/nats-deployment.yaml
> k8s deployment file for NATS (CAS-292)

- terraform/README.adoc
- terraform/main.tf
- terraform/mod/k8s/main.tf
- terraform/mod/k8s/master.sh
- terraform/mod/k8s/node.sh
- terraform/mod/k8s/repo.sh
- terraform/variables.tf
Add more config settings to variables.tf
Setup hugepages in the node
Add support to load nvme modules ubuntu 20.04 only
Minor change in kube config handling, works with
- ubuntu 20.04
- ubuntu 18.04
> Update terraform config

- mayastor-test/test_nexus.js
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_nvmf.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/src/bin/initiator.rs
A version of the NVMEoF nexus support work which is slimmed down as much as possible. Limited to nexus using the same target as the replicas and without discovery support.
> CAS-53: Initial NVMEoF nexus implementation

- csi/moac/mbus.js
- csi/moac/package.json
- csi/moac/test/index.js
It is a NATS client written in JS capable of sending register,
deregister or any arbitrary message to the NATS server. It could
useful for troubleshooting.
> mbus utility program for sending messages to NATS

- .github/workflows/build.yaml
- mayastor-test/test_nexus.js
- mayastor/src/subsys/opts.rs
- mayastor/src/target/nvmf.rs
Add the NVMEoF discovery susbsytem when we bring up a target
by default (but allow for it to be disabled through config).
> CAS-192: nexus: Add NVMEoF discovery subsystem

- nix/pkgs/mayastor/default.nix
Point the new mayastor image to:
1e5dca302cff3e66220c3cf892a08c89733d535e
> Update mayastor image revision

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/target/nvmf.rs
+ linter formatting changes to
mayastor/src/target/nvmf.rs
> Implement flush support for Nexus. CAS-329

- mayastor/tests/nexus_rebuild.rs
Re-enable the rebuild_multiple unit test.
> Re-enable the rebuild_multiple unit test

- mayastor-test/test_replica.js
- nix/pkgs/libspdk/default.nix
Update spdk to the commit with the replica import fix
Add new test to verify that importing a pool also imports the replicas
> Fix importing pool with replicas (CAS-367)

- csi/moac/nexus.ts
- csi/moac/node.js
- csi/moac/pool.ts
- csi/moac/test/mayastor_mock.js
- csi/moac/test/nexus_test.js
- csi/moac/test/pool_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.js
- mayastor-test/test_cli.js
- mayastor-test/test_nexus.js
- mayastor-test/test_replica.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/src/pool.rs
- mayastor/src/replica.rs
- mayastor/tests/common/mod.rs
- rpc/proto/mayastor.proto
This simplifies the code in the control plane and improves atomicity of the create methods (either everything succeeds or fails).
> grpc create methods should return the created object (CAS-88)

- deploy/README.md
This will make the doc more concise and clear. No reason to mention
alternative that is by all means (flexibility and performance) worse
option than iSCSI.
> Do not mention NBD in our quick start guide.

- .github/workflows/nix-tests.yaml
Also have them clear the results from any previous runs.
> ci: re-enable nix-tests

- .github/workflows/nix-tests.yaml
- nix/test/rebuild/README.md
- nix/test/rebuild/default.nix
- nix/test/rebuild/node1-mayastor-config.yaml
- nix/test/rebuild/node2-mayastor-config.yaml
- nix/test/rebuild/rebuild.nix
The test cases cover scenarios such as:
- network failure
- node crash
Once @tjoshum has created the structure for the nix tests (i.e. a common Python library) the rebuild tests can be restructured accordingly.
> CAS-378: Rebuild nix tests

- mayastor/src/subsys/config/mod.rs
the pools were being exported in "legacy" mode and therefore when
imported some parameters were missing (uuid, alias)..
> CAS-434: fix pool status information

- csi/src/node.rs
Make staging volumes more idempotent.
Staging  a file system volume consists 3 phases
1) validation of arguments (return on fail)
2) attaching to the nexus,
3) file system mount.
This change
i) moves the accesstype check to phase 1.
ii) detaches the nexus if the file system mount fails.
> Detach on failed fs mount. CAS-429

- mayastor/tests/reactor.rs
Propagate the thread failures into the main thread by joining.
> reactor start_stop test

- mayastor-test/test_csi.js
> Cleanup nexus nvme after mocha CSI tests CAS-427

- Jenkinsfile
- doc/jenkins.md
- mayastor-test/test_common.js
- mayastor-test/test_csi.js
- mayastor-test/test_nexus.js
- scripts/moac-test.sh
- scripts/node-test.sh
A race condition in nexus tests is fixed as well.
The first stage: we run jenkins along with github actions. When
it is proved to work we will remove github actions .github directory
completely.
> Migrate our CI/CD from github actions to jenkins (CAS-397)

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_io.rs
During testing and performance benchmarking, it showed that when we
create an lvol, it does not support flush. The bdev then is exported as
a target -- over nvmf and consumed as replica.
By virtue of it being a nvme bdev, it implicitly supports flush, which
our lvol does not handle.
We must support flush and thus, simply complete the IO.
While here, i've removed some of the raw pointer deferences.
> nexus: flush should always succeed

- Jenkinsfile
Manually means by clicking a button in Jenkins webUI.
> Be able to trigger develop tests and image creation manually

- .github/auto_assign.yml
- Jenkinsfile
- doc/contribute.md
The update to documentation is meaningless. The purpose of this change is to test PRs with bors and jenkins.
---
Nothing below the line above should get into the commit message.
> Test integration of bors and jenkins

- Jenkinsfile
really a simple fix for a stupid error I made earlier
> Nightly develop images were not built and uploaded

- mayastor/src/logger.rs
Create an EnvFilter for the default subscriber that allows the filter to be configured via the RUST_LOG environment variable.
This reproduces as closely as possible the old behaviour using the logging crate.
The default logging level is honoured *only* if RUST_LOG is not set (to a valid value).
> 447 Initialise tracing so that default subscriber filtering may be configured via environment variable.

- mayastor/src/bdev/nexus/nexus_child.rs
Before writing a label to a child we must first ensure that it is
read-writable. The previous check did not take into account that a child
can service I/O whilst in the out-of-sync state. As a result, when
adding a child to a nexus a "Failed to sync labels" error message was
erroneously reported (even though the label was updated).
> Enhance check before writing labels to children

- jsonrpc/src/error.rs
- jsonrpc/src/lib.rs
- mayastor/src/bin/cli/cli.rs
- mayastor/src/bin/cli/context.rs
- mayastor/src/bin/cli/jsonrpc_cli.rs
- mayastor/src/bin/main.rs
- mayastor/src/core/env.rs
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/src/grpc/json_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/server.rs
- rpc/proto/mayastor.proto
- services/common/src/lib.rs
New gRPC call that invokes the specified (local) SPDK json-rpc method and returns the results.
> CAS-418 Support for json-rpc passthrough

- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/dev/null.rs
- spdk-sys/wrapper.h
Useful for benchmarking the I/O stack with minimal overhead
> Add spdk null bdev driver

- mayastor/src/core/env.rs
The upcoming SPDK 20.10 removes support for the legacy INI
configuration so do the same in Mayastor, dropping the -c CLI option.
Use of the legacy config had already been removed from the tests.
> CAS-501: Remove support for legacy INI configuration

- mayastor/src/lvs/lvs_pool.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/src/subsys/nvmf/target.rs
- mayastor/src/target/iscsi.rs
- mayastor/src/target/nvmf.rs
- nix/pkgs/libspdk/default.nix
- spdk-sys/README.md
- spdk-sys/build.rs
- spdk-sys/build.sh
Update libspdk to build against the v20.10.x-mayastor branch and sync with the API changes.
> CAS-437: Upgrade SPDK to 20.10 and update mayastor

- doc/jenkins.md
- mayastor/tests/common/mod.rs
- mayastor/tests/nexus_rebuild.rs
Update the nix configuration to include garbage collection - should prevent failures due to no disk space available
Somewhat improve rebuild cargo test - in hopes of avoiding some the nbd usual failures
> Attempt to improve Jenkins CI

- mayastor/src/logger.rs
Set up a LogTracer "logger" to translate any log messages received into trace events.
This ensures that log messages originating from third party crates still using the old log facade will not be lost.
> CAS-517 Ensure that "log" messages from third party crates are displayed as trace events

- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bin/cli/rebuild_cli.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/rebuild/rebuild_api.rs
- mayastor/src/rebuild/rebuild_impl.rs
- rpc/proto/mayastor.proto
Check if there are any active tasks when completing the rebuild
Add new stats subcommand to retrieve the rebuild stats
> Fix rebuild bug and add new subcommand

- mayastor/src/bdev/nexus/nexus_child.rs
When removing a child only set the state to closed if it is open. In all
other cases, do not modify the state.
This change should fix those issues where the child changes to the 
closed state on removal, when it had previously had its state set appropriately. 
This results in the control plane being unable to make the correct decisions.
> Only set a child to closed on removal if open

- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/core/nvme.rs
- mayastor/tests/replica_snapshot.rs
Recreate the snapshot test that was removed in #528.
> CAS-528: Reintroduce replica snapshot cargo test

- mayastor-test/e2e/common/util.go
- mayastor-test/e2e/nightly/pvc_stress_fio/pvc_stress_fio_test.go
- mayastor-test/e2e/nightly/test.sh
- mayastor-test/e2e/nvmf_vol/nvmf_vol_test.go
Use and move functions from and to common/util.go
Add pvc_stress test that uses fio
> Refactor for CAS-500

- Jenkinsfile
Why I'm trying to push this change that does not change anything?  I have spent quite some time yesterday figuring out how to disable default commit status updates. My findings lead me to the conclusion that it could be done with checkout scm parameter but I don't know how exactly and it requires more experiments. Nevertheless, the small changes that I had for that in my branch could be useful and also describe the future work that needs to be done in a comment.
I hope that the code as it is won't break the pipeline. That remains to be tested by bors 🤞
> Introduce init stage for disabling default commit status in the future

- Jenkinsfile
The current code works but in case that develop should not be
tested and error() is called in init stage, the final result
is ERROR instead of SUCCESS. This fix hasn't been tested but
according to stack-overflow it should work ;-)
> Fix for a recent regression to develop branch testing

- Jenkinsfile
The fix is a combination of changes to jenkinsfile and to the jenkins configuration done through UI.
Tested on test-jenkins branch.
> The fix for commit status updates.

- Jenkinsfile
Now when default github notifications are disabled in jenkins
configuration we can abort the job at global level. Another reason
is that we don't have to enable execution of unsafe code in the
pipeline then. We have already enabled raw job object access but we
would need more to get rid of the latest error message:
"Scripts not permitted to use method hudson.model.Run getExecutor"
The init stage remains there because it avoids duplicating the code
for setting pending state on a github commit.
> Move pipeline abort to global scope again.

- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/core/descriptor.rs
- mayastor/tests/nexus_label.rs
- mayastor/tests/rebuild.rs
The first commit provides a bit more visibility into why the creation of channels might have failed.
> Retirement

- scripts/e2e-cluster-dump.sh
- scripts/e2e-test.sh
Add scripts/e2e-cluster-dump.sh,
invoke from scripts/e2e-test.sh on test failures
> ci: collect cluster state and pod logs on e2e test failure CAS-611

- scripts/e2e-test.sh
disable e2e tests pending investigation
> ci: disable e2e tests pending investigation

- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/uri.rs
This abstracts transport and controller options.
Fixes CAS-622
> nvmx: abstract options

- .github/workflows/pr-commitlint.yml
- .pre-commit-config.yaml
- commitlint.config.js
- shell.nix
Add github action to lint PR commits and the PR itself.
Add pre-commit hook to lint commit messages locally.
> style(lint): lint commits messages

- mayastor/tests/rebuild.rs
CI/CD was showing occasional failures of rebuild tests. This was because
the tests generally only waited a short time (i.e. 2 seconds) for a
rebuild to complete. This wasn't always long enough.
The utility function to wait for successful rebuilds has been modified
so that it continually polls for rebuild progress. As long as some
progress is being made within a given window (5 seconds) it will
continue to wait for the rebuild. After 30 seconds, if the rebuild has
not completed, it will give up waiting for it.
> test(rebuild): wait for successful rebuild (CAS-620)

- scripts/e2e-test.sh
Add rebuild tests to the E2E test script.
> test: enable rebuild E2E test on CI/CD (CAS-609)

- csi/moac/node-packages.nix
- csi/moac/package-lock.json
- csi/moac/package.json
The hard work has been done in jkryl/javascript repo on github.
Here we only update to the new version of the package. Follow
up work is to try to upstream the fix (in progress with unsure outcome).
> feat(moac): k8s client lib - pull from upstream

- services/examples/pool-client/README.md
- services/examples/pool-client/main.rs
Add an example pool client which can make requests to the pool service
over a nats message bus.
> test: add example pool-client

- mayastor/src/grpc/mayastor_grpc.rs
Add log message with the nexus create arguments.
> refactor(nexus): add nexus create log

- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset-config.yaml
- deploy/mayastor-daemonset.yaml
- deploy/moac-deployment.yaml
Revert :v0.7.0 tag to :latest tag for
mayastor images
> chore(deployment): update k8s config files

- Jenkinsfile
Adds a parallel pipeline branch to tests where it builds k8s cluster,
runs e2e tests on it and destroys the cluster it if tests succeed.
CAS-570
> test(e2e): build and use on-demand k8s cluster

- Cargo.lock
- composer/src/lib.rs
- nix/pkgs/mayastor/default.nix
- operators/node/src/main.rs
- rest/src/lib.rs
- rest/tests/v0_test.rs
- services/Cargo.toml
- services/deployer/README.md
- services/deployer/src/bin.rs
- services/deployer/src/infra/dns.rs
- services/deployer/src/infra/empty.rs
- services/deployer/src/infra/jaeger.rs
- services/deployer/src/infra/mayastor.rs
- services/deployer/src/infra/mod.rs
- services/deployer/src/infra/nats.rs
- services/deployer/src/infra/rest.rs
Deploys all (configurable) control plane components in a local docker
cluster.
For more details please use the help argument and have a look at the
README.md.
> feat(deployer): new tool to test the control plane

- scripts/e2e-test.sh
- test/e2e/common/util.go
- test/e2e/uninstall/uninstall_test.go
1. Default ON_FAIL to stop in scripts/e2e-test.sh
2. Add CLEANUP option to scripts/e2e-test.sh
use it to select desired beahviour for uninstall
test check or cleanup
3. Add support methods to common/util to
Check that no volume resources exist
Check no test pods exist
invoke those checks in uninstall if cleanup
is not selected.
4. Refactor uninstall to support
a) check resource leakage and fail immediately
b) check resource leakage, cleanup and fail.
> ci: disable cluster cleanup on test fail

- Jenkinsfile
- scripts/e2e-test.sh
New variable in e2e-test.sh script is introduced that is expected
to contain names of all e2e tests that should run nightly in the
future.
> ci: support for running nightly e2e tests

- Jenkinsfile
- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/reporter/junit.go
- test/e2e/csi/e2e_suite_test.go
- test/e2e/install/install_test.go
- test/e2e/node_disconnect/README.md
- test/e2e/node_disconnect/replica_pod_remove/replica_pod_remove_test.go
- test/e2e/pvc_stress_fio/pvc_stress_fio_test.go
- test/e2e/rebuild/basic_rebuild_test.go
- test/e2e/replica/replica_test.go
- test/e2e/resource_check/resource_check_test.go
- test/e2e/uninstall/uninstall_test.go
Send reports to Jira xray.
Specify which test plan in the Jenkinsfile.
Currently implemented for on-demand and nightly tests.
Updated one readme.
> test: send xray reports

- mayastor/src/bin/spdk.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- nix/pkgs/libspdk/default.nix
> feat: build against SPDK 21.01

- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/src/target/iscsi.rs
- mayastor/tests/nexus_multipath.rs
- mayastor/tests/nexus_share.rs
- nix/pkgs/libspdk/default.nix
> feat(nexus): allow shared replica to be added as local child

- Jenkinsfile
- scripts/e2e-test.sh
Define the continuous tests in the test script rather
than the Jenkinsfile. Add script option --profile
to specify this. 
Add rebuild and replica e2e tests to continuous runs.
Ensure commit status is not affected by running continuous tests.
> test(e2e): extend e2e continuous tests

- Jenkinsfile
- test/e2e/loki/promtail_configmap_e2e.yaml
- test/e2e/loki/promtail_daemonset_e2e.template.yaml
- test/e2e/loki/promtail_namespace_e2e.yaml
- test/e2e/loki/promtail_rbac_e2e.yaml
Install Loki on the cluster prior to each e2e test.
Remove Loki from the cluster when finished.
API key is stored as a Jenkins secret.
> test(e2e): install loki on the cluster

- doc/run.md
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bin/mayastor-client/nexus_cli.rs
- mayastor/src/bin/mayastor.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/subsys/nvmf/mod.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/tests/nexus_multipath.rs
- rpc/proto/mayastor.proto
- rpc/src/lib.rs
- spdk-sys/build.rs
- test/grpc/test_nexus.js
Implement set_ana_state in nexus_bdev::Nexus and expose that over
gRPC and the client CLI.
Fixes CAS-756, #758
> feat(nexus): implement set ANA state for an NVMf-published Nexus

- mayastor/tests/aio_unmap.rs
- nix/pkgs/libspdk/default.nix
Test is currently disabled until spdk is updated.
> test(cargo): verify unmap operation for aio module

- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/e2e_config/e2e_config.go
- test/e2e/common/test.go
- test/e2e/common/util.go
- test/e2e/common/util_cleanup.go
- test/e2e/common/util_mayastor_crds.go
- test/e2e/common/util_pvc.go
- test/e2e/common/util_testpods.go
- test/e2e/csi/dynamic_provisioning_test.go
- test/e2e/io_soak/filesystem_fio.go
- test/e2e/io_soak/fio.go
- test/e2e/io_soak/io_soak_test.go
- test/e2e/io_soak/rawblock_fio.go
- test/e2e/node_disconnect/lib/node_disconnect_lib.go
- test/e2e/node_disconnect/replica_pod_remove/replica_pod_remove_test.go
- test/e2e/pvc_stress_fio/pvc_stress_fio_test.go
- test/e2e/rebuild/basic_rebuild_test.go
- test/e2e/replica/replica_test.go
- test/e2e/uninstall/uninstall_test.go
+  a bunch of other changes to remove hardcoded values.
> ci: add namespace support required for disruptive pods MQ-325

- Jenkinsfile
Ensure the nightly run happens on the 
Mayastor pipeline only.
The Mayastor-e2e pipeline currently shares this Jenkinsfile,
though for not much longer, until then ensure nightly runs occur
only on Mayastor pipeline.
Additionally, emit build tag to the XRay report description.
> test(e2e): run nightly on only one pipeline

- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/test.go
- test/e2e/common/util.go
- test/e2e/common/util_cleanup.go
- test/e2e/install/install_test.go
- test/e2e/io_soak/io_soak_test.go
- test/e2e/ms_pod_disruption/replica_pod_remove_test.go
- test/e2e/multiple_vols_pod_io/multiple_vols_pod_io_test.go
- test/e2e/pvc_stress_fio/pvc_stress_fio_test.go
- test/e2e/rebuild/basic_rebuild_test.go
- test/e2e/replica/replica_test.go
- test/e2e/resource_check/resource_check_test.go
- test/e2e/uninstall/uninstall_test.go
Add pool online checks
after installation
before each test run
resource check test for 3rd party tests
Rationalise the code checking for reuse
> test(e2e): add pool online checks

- Jenkinsfile
Fix logic to determine the nightly schedule.
Also ensure bors try requests do not generate
XRay reports.
> test(e2e): nightly and XRay fixes

- test/e2e/common/util_mayastor_crds.go
- test/e2e/install/install_test.go
Replace the eventually statement with a for loop.
> fix: fix install test pool check

- Jenkinsfile
Tag images produced by nightly builds as 'nightly'.
This is to allow mayastor-e2e-self-ci runs to run
against the most recent successful develop images.
> test(e2e): tag nightly builds

- composer/src/lib.rs
- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/controller_state.rs
- mayastor/src/bdev/dev/nvmx/mod.rs
- mayastor/src/bdev/dev/nvmx/uri.rs
- mayastor/src/bdev/dev/nvmx/utils.rs
- mayastor/tests/block_device_nvmf.rs
This fix introduces support of hot removal for nvmx devices, which
is done via AER callbacks.
Implements CAS-825
> feat(nvmx): support of hot removal for nvmx devices

- mayastor/src/bin/mayastor-client/jsonrpc_cli.rs
> fix(jsonrpc): revert change to reformat output from jsonrpc subcommand

- Jenkinsfile
Builds from develop are pushed to the CI registry before the e2e test is run.
However we should tag the images as 'nightly' only when the test succeeds.
This ensures the mayastor-e2e-self-ci runs use images known to have passed CI.
> test(e2e): tag CI images only on success

- .pre-commit-config.yaml
- csi/src/filesystem_vol.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/core/bdev.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/subsys/nvmf/transport.rs
- nix/lib/rust.nix
- nix/sources.json
This updates rustc nightly to a newer version and bumps
nixpkgs allong with it.
As a consequence, some minor clippy lints needed fixing.
> chore(nix): update nixpkgs and rustc

- mayastor/src/core/reactor.rs
- mayastor/tests/reactor.rs
> chore(core): make delayed polling explicit

- Jenkinsfile
When using a Loki query "run=<build_no>" is ambiguous,
because branches and pipelines use independent
sequences of build numbers.
Instead of the build number, construct a string based on:
pipeline + branch + build number.
e.g. "Mayastor-develop-456"
> test(e2e): use loki_run_id to identify runs in Loki MQ-612

- mayastor/src/lvs/lvs_pool.rs
- mayastor/tests/lvs_pool.rs
Requirement coming from FM-40
fixes CAS-848
> fix: default pool device to aio if not specified

- csi/moac/.gitignore
- csi/moac/csi.ts
- csi/moac/grpc_client.ts
- csi/moac/nexus.ts
- csi/moac/node.ts
- csi/moac/package.json
- csi/moac/pool.ts
- csi/moac/replica.ts
- csi/moac/test/csi_test.js
- csi/moac/test/grpc_client_test.js
- csi/moac/test/nexus_test.js
- csi/moac/test/pool_operator_test.js
- csi/moac/test/pool_test.js
- csi/moac/test/replica_test.js
- csi/moac/test/rest_api_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/tsconfig.json
- csi/moac/volume.ts
- csi/moac/volumes.ts
Callback was called twice which resulted into strange errors about
unhandled exceptions in grpc lib being printed into the log.
As part of troubleshooting I have rewritten grpc_client to
typescript to catch more errors during the compilation.
> fix(moac): fix double callback in controllerPublish method

- Jenkinsfile
Send slack message and allow build to pass
on XRay report failure.
> test(e2e): do not fail build on XRay failure

- .gitignore
- chart/Chart.lock
- chart/Chart.yaml
- chart/README.md
- chart/develop/values.yaml
- chart/release/values.yaml
- chart/templates/moac-deployment.yaml
- chart/test/values.yaml
- chart/values.yaml
- deploy/etcd/statefulset.yaml
- deploy/etcd/svc-headless.yaml
- deploy/etcd/svc.yaml
- scripts/generate-deploy-yamls.sh
Added a helm dependency to our mayastor chart.
Updated the generate yaml script to include the generated etcd yaml files.
Added the newly generated develop yaml files to the deploy folder.
> chore: add etcd depoyment via helm

- chart/templates/moac-deployment.yaml
- csi/moac/index.ts
- csi/moac/test/index.js
- deploy/moac-deployment.yaml
- mayastor/src/bdev/nexus/nexus_io.rs
> feat(moac): get the default namespace from pod's filesystem

- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
- csi/moac/volume_operator.ts
- csi/moac/volumes.ts
Two fixes that come in two commits.
> fix(moac): destroy volume fixes

- Jenkinsfile
Temporarily disable e2e testing
> test(e2e): disable e2e tests

- Jenkinsfile
Fixes MQ-280 - missing random built files by cleaning up workspace each run.
> ci: clean jenkins workspace before build MQ-280

- Jenkinsfile
Re enable e2e testing in Mayastor pipeline
> test(e2e): re-enable e2e testing

- Jenkinsfile
We may need to tag 'nightly' images outside of nightly runs.
Added Jenkins config option to tag a successful build as 'nightly'.
if tests pass when run manually.
Allow e2e tests to be disabled from Jenkins config.
Removed some duplicated code.
Replace deprecated 'continue' keyword with 'reinstall'.
> test(e2e): fixes for nightly pipeline

- csi/moac/src/watcher.ts
It seems to be an undocumented behaviour of the watcher library that
we are using, to call error callback even if there is no error upon
the first start. The solution is to register error callback after the
watcher is started.
I also made some changes to avoid printing error messages to the log
when the watcher restart was actually intentional.
Resolves: CAS-938
> fix(moac): avoid duplicating watcher upon restart

- csi/moac/src/volume.ts
- csi/moac/test/volumes_test.js
We labelled replicas when creating the volume but it has quite a lot
of overhead since we need to create nexus object and wait for it to
go away after the labeling is finished. More over creating a storm of
rpc requests (share replicas, nexus create, destroy) isn't good for
mayastor's health that is impacted by blocking connect problem and it
doubles the memory overhead. Don't create the nexus until the volume
is published.
Resolves: CAS-944
> feat(moac): defer labeling of replicas to volume publish

- Jenkinsfile
Grafana is monitoring the job now.
> ci: disable slack notification on job status change

- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nvmx/mod.rs
- mayastor/src/bin/mayastor-client/controller_cli.rs
- mayastor/src/bin/mayastor-client/main.rs
- mayastor/src/grpc/controller_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- rpc/proto/mayastor.proto
- test/grpc/test_cli.js
Introduced a new command for listing nvme controllers.
Implements CAS-918
> fix(cli): controller cli command added

- shell.nix
- test/python/README.md
- test/python/common/command.py
- test/python/common/fio.py
- test/python/common/nvme.py
- test/python/conftest.py
- test/python/test_nexus.py
- test/python/test_nexus_create_destroy.py
- test/python/test_nexus_kill_all.py
- test/python/test_null_nexus.py
I had not gotten around to cleaning things up a bit. Ive also removed
the implicit install of Python packages when entering the shell.
> test(python): cleanup some unused code

- chart/templates/etcd/storage/localpv.yaml
- deploy/etcd/storage/localpv.yaml
Explicitly set the persistentVolumeReclaimPolicy to Retain.
Also, you should manually delete the data.
> fix: add missing change from merged PR

- nix/pkgs/mayastor/cargo-package.nix
> fix: update sha for building images

- mayastor/src/core/env.rs
- mayastor/src/core/mod.rs
- mayastor/src/grpc/mayastor_grpc.rs
- rpc/proto/mayastor.proto
- test/python/common/hdl.py
- test/python/docker-compose.yml
- test/python/test_common.py
Mayastor now reports the set of supported features and its version via
gRPC call.
Fixes CAS-972
> feat(core): report supported features

- test/python/features/pool.feature
- test/python/features/replica.feature
- test/python/test_bdd_pool.py
- test/python/test_bdd_replica.py
roughly translated from test/grpc/test_replica.js
resolves CAS-961
> test(py): add pytest-bdd feature tests for pools and replicas

- test/python/features/rebuild.feature
- test/python/test_bdd_rebuild.py
- roughly translated from test/grpc/test_rebuild.js
- resolves CAS-969
> test(py): add pytest-bdd feature tests for rebuild

- Jenkinsfile
- scripts/pytest-tests.sh
- test/python/setup.sh
- added file ./test/python/setup.sh to setup python environment
- added file ./scripts/pytest-tests.sh to run "pytest" tests
- added "pytest tests" stage to Jenkinsfile
> test(py): run pytest based tests as part of CI

- mayastor/src/bdev/aio.rs
- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/malloc.rs
- mayastor/src/bdev/null.rs
- mayastor/src/bdev/nvme.rs
- mayastor/src/bdev/nvmf.rs
- mayastor/src/bdev/nvmx/uri.rs
- mayastor/src/bdev/uring.rs
- mayastor/src/nexus_uri.rs
Make BDEV create error message more consistent and user-friendly.
Fix for parameters validation of malloc BDEV create API.
Fixes CAS-712
> fix(mayastor): fix bdev create error messages

- test/python/test_nexus_multipath.py
Create 2 nexuses each with 2 replicas, connect to both nexuses over
NVMf, run fio against the block device. While fio is running, create
a 3rd nexus with the same 2 replicas and connect to it over NVMf.
Verify that the existing block device now has 3 paths.
Fixes CAS-975
> test(python): add a 3rd nexus to an existing multipath device

- mayastor/src/bdev/device.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/device.rs
- mayastor/src/bdev/nvmx/handle.rs
- mayastor/src/bdev/nvmx/mod.rs
- mayastor/tests/block_device_nvmf.rs
> chore: simplify clone() calls

- deploy/csi-daemonset.yaml
Signed-off-by: Payes Anand <payes.anand@mayadata.io>
> fix(image-tag): update mayastor-csi image tag to v0.8.1

- test/python/common/hdl.py
Attempt to work around gRPC bug by retrying once on failure.
> fix(pytest): create explicit readiness_check in MayastorHandle

- test/grpc/package-lock.json
- test/grpc/package.json
This should address the latest dependabot alerts.
> fix(security): update grpc packages

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/tests/nexus_children_add_remove.rs
Don't allow it as that would render the volume unusable.
Fixes: CAS-1245
> fix(nexus): should not remove the last healthy child

- .pre-commit-config.yaml
- mayastor/src/bdev/nvme.rs
- mayastor/src/bdev/nvmf.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- nix/pkgs/libspdk/cet-disable.patch
- nix/pkgs/libspdk/default.nix
New features include an async NVMe driver.
Fixes CAS-1204
> feat: build against SPDK 21.10

- .gitignore
- mayastor/src/core/bdev.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/server.rs
- mayastor/src/grpc/v1/pool.rs
- mayastor/src/grpc/v1/replica.rs
- mayastor/src/lvs/lvol.rs
- mayastor/src/lvs/lvs_pool.rs
- mayastor/src/pool.rs
- rpc/build.rs
- rpc/src/lib.rs
- scripts/pytest-tests.sh
- test/python/setup.sh
- test/python/v1/hdl.py
- test/python/v1/replica/docker-compose.yml
- test/python/v1/replica/features/replica.feature
- test/python/v1/replica/test_bdd_replica.py
- adds the implementation of v1/replica service.
- add tests for v1/replica
> feat(grpc): add mayastor v1 service for replica

- mayastor/src/grpc/controller_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/server.rs
- mayastor/src/grpc/v1/host.rs
- mayastor/src/host/blk_device.rs
- mayastor/src/host/resource.rs
- rpc/build.rs
- rpc/src/lib.rs
- test/python/setup.sh
- test/python/v1/hdl.py
Signed-off-by: Akhil Mohan <akhil.mohan@datacore.com>
> feat(grpc): adding v1 host service

- Cargo.lock
- composer/Cargo.toml
- csi/Cargo.toml
- devinfo/Cargo.toml
- jsonrpc/Cargo.toml
- mayastor/Cargo.toml
- mbus-api/Cargo.toml
- nvmeadm/Cargo.toml
- rpc/Cargo.toml
- spdk-sys/Cargo.toml
- sysfs/Cargo.toml
Ensure all version numbers have been updated.
> chore(version numbers): increment all to 1.0.0

- .github/auto_assign.yml
Removes Jeffry from the list of auto-assigned reviewers
> chore(code reviewers): remove gila

- mayastor/src/bin/mayastor.rs
Using 2MB Hugepage is the common case, but in some enviroment, Hugepage is enabled on size 1GB.
So also check whether 1GB page is enough to run Mayastor.
> chore(hugepage): add 1GB Hugepage checking

- bors.toml
Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>
> chore(bors): require DCO for bors r+

- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- scripts/check-deploy-yamls.sh
Signed-off-by: GlennBullingham <glenn.bullingham@datacore.com>
> chore(release): sets mayastor image tags to v1.0.2
