- mayastor/examples/nvmf_uri.rs
- mayastor/src/executor.rs
- mayastor/src/jsonrpc.rs
- mayastor/src/lib.rs
- mayastor/tests/io.rs
- mayastor/tests/reconfigure.rs
Dynamic mutable reference on executor was obtained twice in the tick
function. Clear rules for using the executor context have been defined,
which should prevent similar problems in future. Also the executor's API
was simplified.
> Fix illegal instruction crash in mayastor io unit test

- mayastor/src/bdev/nexus/nexus_bdev.rs
When we only write two partitions, we in fact only have 2 partitions
in memory. This may sound logical but other tools simply always write
out 128 partitions.
Initially we did the same but prior to integration this was
changed and we forgot to adjust the offset before writing out the
backup label to disk
With the change:
$ mctl create gpt  -r aio:///code/disk1.img?blk_size=512 -s 1GiB -b 512
"gpt"
$ sgdisk -p /code/disk1.img
Found valid GPT with corrupt MBR; using GPT and will write new
protective MBR on save.
Disk /code/disk1.img: 2097152 sectors, 1024.0 MiB
Sector size (logical): 512 bytes
Disk identifier (GUID): 3D1034D1-C0B0-40B4-BB80-4B8D9E903CB3
Partition table holds up to 2 entries
Main partition table begins at sector 2 and ends at sector 2
First usable sector is 2048, last usable …
> nexus_label: adjust the cursor to the right offset

- .pre-commit-config.yaml
- .travis.yml
- Cargo.lock
- mayastor-test/test_common.js
- mayastor-test/test_csi.js
- nix/pkgs/libiscsi/default.nix
- nix/pkgs/libspdk/default.nix
- shell.nix
- test.sh
This change moves SPDK within the nixpkg sets which allows us to
start using the chachix and avoid rebuilding SPDK all the time.
Unfortunately, due to a lack of control of the Travis image, packages pushed from my dev box
do not result in the same hash as Travis defaults to tracking unstable. The solution to that is to have
Travis push the pkg after successful run but I've not figured out how to have it do that yet.
> nix: use package libspdk

- nix/pkgs/libspdk/default.nix
Fix for https://github.com/spdk/spdk/issues/825 and
https://bugs.dpdk.org/show_bug.cgi?id=356 and some other nits.
> Patch a bug in dpdk which caused build failures in rare cases

- csi/src/mount.rs
- jsonrpc/src/test.rs
- mayastor/examples/nvmf_uri.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/descriptor/mod.rs
- mayastor/src/lib.rs
- mayastor/tests/io.rs
- mayastor/tests/nexus_label.rs
- mayastor/tests/reconfigure.rs
The errors were found by clippy from rust nightly toolchain 2019-10-20.
It is recommended that people upgrade to at least this version of
nightly or later.
> Fix issues found by clippy in rust code

- Dockerfile
- nix/mayastor-overlay.nix
- nix/pkgs/libspdk/default.nix
- nix/pkgs/stern/default.nix
If set to true it adds --enable-debug configure option to libspdk.
Currently it is not used by anything. In future we might use it to
build debug flavour of mayastor.
> Add enableDebug param to libspdk nix package

- doc/build.md
- mayastor-test/test_common.js
- mayastor-test/test_grpc.js
- mayastor-test/test_nexus_grpc.js
When killing proc without sudo we must match pid instead of ppid.
When running as root we don't need to tweak perms on nbd devs.
> Fix bugs related to when running the tests as root

- .gitlab-ci.yml
- .pre-commit-config.yaml
- csi/moac/default.nix
- mayastor/src/nvmf_target.rs
- nix/pkgs/mayastor/default.nix
Minor bugfixes:
* checksum for cargo deps of mayastor in nix was wrong
* avoid building mayastor twice when building the images in gitlab
* use NVMF_TGT_NAME_MAX_LENGTH instead of hardcoded constant
* name docker images properly and add some more metadata
> Update spdk-sys subrepo to v19.10 branch and other minor bugfixes

- cli/src/mctl.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/bdev/nexus/nexus_module.rs
- mayastor/src/bdev/nexus/nexus_share.rs
Initially we used the the driver_ctx pointer itself to keep track of the IO status and (abused) the io outstanding fields in the bdev_io.
These changes remove that and add a proper io context which is work needed prior to rebuild
> Clean up IO handling and introduce proper io context

- mayastor-test/test_grpc.js
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/pool.rs
Just a side note: the change in test suite does not really verify the fix. To test the fix fully we would need to create the pool, replica and nexus all in one test. That would be an interesting task for the future. The fix was tested manually on the k8s cluster for perf testing.
> Set the default block size in case it is explicitly set to zero

- mayastor/src/nvmf_target.rs
Notice the unwrap(). This is during init so we actually want to fail if we can not allocate the memory to contain the CString.
> nvmf: use CString when setting target name

- mayastor-test/test_grpc.js
- mayastor/src/pool.rs
- mayastor/src/replica.rs
Clearing large pools on SSD disks can take an hour. If people want
to do that for security reasons then they can do that manually
before the disk is assigned to a pool.
Clearing user data stored on volumes is mandated by CSI spec so
that is done upon lvol destroy.
NOTE: Devices which do not support unmap are not properly cleared when
destroyed due to a bug in SPDK https://github.com/spdk/spdk/issues/944.
> Do not clear whole pool upon create but only lvols when they are destroyed

- mayastor-test/test_nexus_grpc.js
- mayastor/examples/nvmf_uri.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_config.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/descriptor/mod.rs
- mayastor/src/nvme_dev.rs
- mayastor/src/replica.rs
- mayastor/tests/nexus_label.rs
- mayastor/tests/reconfigure.rs
The commits messages on their own provide mode details in short
- make the nexus configure itself automatically removing the need for blksize completely
- add a protective MBR to the labels as on some machines the partitions did not show up automatically
Next PR will add more test cases where we purposefully try to create nexus devices with bad value and validate proper behaviour. 
As an example; i've created a zvol and exported that over nvmf. After creating the nexus, the node with has that volume shows:
```
zd0                    230:0    0     1G  0 disk 
├─zd0p1                230:1    0     4M  0 part 
└─zd0p2                230:2    0  1019M  0 part 
```
Printing the partition table
```
$ sgdisk -p /dev/zd0
Disk /dev/zd0: 2097152 sectors, 1024.0 MiB
Sector size (logical/physical): …
```
> Add protective MBR and automatically calculate nexus geometry 

- nix/lib/rust.nix
- nix/mayastor-overlay.nix
- nix/pkgs/mayastor/default.nix
- shell.nix
This change adds support for selecting what channel we want to use via `--argstr channel stable` for example when invoking nix-shell.
By default, it is set to nightly. The followup commit enabled debug build by default. Testing with -L flag works as expected (which only works with debug enabled)
> nix: support for multiple rust versions and debug builds

- Cargo.lock
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/descriptor/mod.rs
- mayastor/src/lib.rs
- mayastor/src/rebuild.rs
- mayastor/tests/rebuild.rs
- nix/pkgs/mayastor/default.nix
- The rebuild task creation has been reworked a bit and returns itself, this means there is always a reference to the structure from within rust
- Rework the IO enum types 
- Only reconfigure the io channels when they are in use
> rebuild: minor prerequisites for rebuild integration within the nexus

- deploy/mayastor-daemonset.yaml
- mayastor-test/test_cli.js
- mayastor-test/test_common.js
- mayastor-test/test_grpc.js
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/iscsi_target.rs
- mayastor/src/lib.rs
- mayastor/src/nvme_dev.rs
- mayastor/src/nvmf_target.rs
- mayastor/src/replica.rs
The pod's IP in k8s environment is passed to mayastor process through
environment variable. If undefined it is set to 127.0.0.1. Other
minor fixes include:
* unifying domain name used in nqn and iqn strings.
* changing port of nvmf target to 8420 which does not appear to be used
by anything else.
* allow DEBUG env var even in release version of mayastor so that we
don't need to rebuild image if we want to use it for testing.
> Add IP of remote replica to URI used by nexus.

- mayastor/src/aio_dev.rs
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_module.rs
- mayastor/src/bdev/nexus/nexus_rebuild.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/descriptor/mod.rs
- mayastor/src/event.rs
- mayastor/src/executor.rs
- mayastor/src/poller.rs
- mayastor/src/rebuild.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/rebuild.rs
Most importantly, this adds support for spawning tasks onto a reactor directly (or more precise the default thread on the reactor) as well as adding support for dynamically creating new threads that will run on a reactor but need to be polled explicitly.
> nexus: add initial rebuild support

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_rebuild.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/event.rs
- mayastor/src/rebuild.rs
- mayastor/tests/nexus_add_remove.rs
- mayastor/tests/rebuild.rs
- mayastor/tests/reconfigure.rs
There was some confusion around adding devices to an existing nexus.
This was mostly caused by the method names themselves where not that
clear about what they do.
online/offline puts an existing child into the online state taking part
in the nexus IO path. (For online this not the true yet because of WIP
around rebuild). The child is not implicitly removed.
registering children -- is done during creating of the nexus, these
methods where initially named add_children but now are called
register_xx.
add/remove will add or remove a child to/from the nexus. And will
attempt to destroy the bdev itself.
> nexus: add more test cases for adding children

- Cargo.lock
- csi/src/mayastor_svc.rs
- doc/errors.md
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/executor.rs
- mayastor/src/iscsi_target.rs
- mayastor/src/jsonrpc.rs
- mayastor/src/lib.rs
- mayastor/src/nvmf_target.rs
- mayastor/src/pool.rs
- mayastor/src/replica.rs
This is a proof of concept done on replica methods. Nexus methods will follow shortly.
> Start using snafu error crate in replica RPC methods.

- Cargo.lock
- mayastor-test/test_nexus.js
- mayastor/Cargo.toml
- mayastor/src/aio_dev.rs
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/src/bdev/nexus/nexus_rebuild.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/src/descriptor.rs
- mayastor/src/event.rs
- mayastor/src/iscsi_dev.rs
- mayastor/src/lib.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/nvmf_dev.rs
- mayastor/src/poller.rs
- mayastor/src/rebuild.rs
- mayastor/tests/nexus_add_remove.rs
- nix/pkgs/mayastor/default.nix
Besides the main group of nexus errors, there are a couple of other
error groups for child bdev, rebuild, labels, nbd, uri parsing, event
and poller modules.
> Convert all error types in nexus code to snafu errors.

- mayastor/src/bin/main.rs
- mayastor/src/environment/args.rs
- mayastor/src/environment/env.rs
- mayastor/src/event.rs
- mayastor/tests/nexus_add_remove.rs
This change adds support for a JSON config file. The JSON file are
rpc methods invoked, prior to accepting any other RPC calls.
Additionally, this change auto adjusts the logger when -L is passed.
> mayastor: add support for JSON config file

- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/descriptor.rs
- mayastor/src/dma.rs
- mayastor/src/environment/env.rs
- mayastor/src/jsonrpc.rs
- mayastor/src/lib.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/rebuild.rs
- mayastor/tests/io.rs
- mayastor/tests/mount_fs.rs
- mayastor/tests/nexus_add_remove.rs
- mayastor/tests/nexus_label.rs
- mayastor/tests/rebuild.rs
- mayastor/tests/reconfigure.rs
* Refactor the code around bdev descriptor object to feel more rusty
and to avoid code duplication with spdk_bdev_open().
* Rust wrapper object for DMA buffer lives in its own file now.
* Remove dma_zmalloc() in favour of dma_malloc() - both methods
returned zero initialized memory.
* Fix bug when return code from mayastor_stop wasn't properly
propagated to mayastor_start caller.
* Fix default log expression which filtered out all messages not coming
from the mayastor lib (i.e. messages from the binaries using the lib).
* Remove "deprecated" tag from mayastor_start() as it's preferred
alternative to mayastor env lib for simple test & utility programs.
Help message for the new tool:
```
Test initiator for nexus replica
Connect, read or write a block to a nexus replica using its URI
USAGE: …
```
> Test utility for reading/writing to/from nexus child - replica

- mayastor/src/app.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/bin/main.rs
- mayastor/src/environment/env.rs
- mayastor/src/lib.rs
- mayastor/src/logger.rs
- mayastor/src/spdklog.rs
- mayastor/tests/common/mod.rs
Move legacy mayastor start/stop functions to app module.
Move log related functions to logger module.
Set log level for rust unit tests to debug (instead of trace).
spdklog module is not used but left in the source tree just in case.
PS: This eliminates the need for MY_POD_IP workaround when running the initiator on the same host with mayastor. It moves legacy start code from a sight not to confuse it with new mayastor env code. I assume that it lowers the required hp memory by a bit but still not enough to run mayastor on the same host with initiator while having 1G of memory in hugepages. The main culprit is iscsi initiator/target in spdk which reserves large memory pools for IO. This could be solved by tuning the IO depth etc, which is possible to do with a configuration file. This PR …
> Do not start nvmf/iscsi target on behalf of initiator utility.

- deploy/mayastor-daemonset.yaml
The mem reqs were heavily overestimated and it was not possible to
start ms on nodes with 4G of mem in some cases. The majority of
allocated memory in ms comes from huge pages which is a separate
memory pool. For remaining allocations done by mayastor on the
heap we need much less than 2G. The new limits were verified when
running fio in k8s cluster.
There is a small fix for change of ms option name done some time ago.
> Reduce the memory requirements for mayastor pod.

- mayastor-test/test_common.js
- mayastor/src/app.rs
- mayastor/src/bin/spdk.rs
- mayastor/src/delay.rs
- mayastor/src/environment/env.rs
- mayastor/src/lib.rs
The annoying message was caused by forgetting to unregister the delay
poller at the end. Other changes:
* DELAY was renamed to MAYASTOR_DELAY to avoid accidental name clash
* The delay code was repeated at three places -> single reusable module
> Fix warning message re registered poller when ms, initiator and spdk exits

- .gitlab-ci.yml
The publish stage depends on mayadata/buildah image whose dockerfile
is not part of mayastor repo. This image rarely needs to be updated
as it just needs to contain a working skopeo and podman tool. We
should revisit this in future and include it or find a better way
than including a docker file (perhaps using nix somehow?).
> CI/CD pipeline should be capable of publishing images to docker hub.

- .gitlab-ci.yml
The fix is to explicitly specify when the pipeline should run.
That is for master and PRs. Also we skip lint & style checks
on master branch as those are mostly useful just for PRs.
> CI/CD pipeline was spawned twice for each PR.

- Cargo.lock
- Cargo.toml
- csi/Cargo.toml
- csi/src/client.rs
- csi/src/identity.rs
- csi/src/mayastor_svc.rs
- csi/src/node.rs
- csi/src/server.rs
- jsonrpc/Cargo.toml
- jsonrpc/src/test.rs
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/tests/common/mod.rs
- nix/lib/rust.nix
- nix/pkgs/mayastor/default.nix
- rpc/Cargo.toml
tonic-rs has recently added support for UDS so we do not need to make use of our
fork anymore. Also, while here, removed some unused dependencies and bump the
versions.
> mayastor: switch to upstream tonic-rs

- shell.nix
Even better would be to disable fortify conditionally for
libspdk and mayastor package when doing debug build. But that
would need a different solution - this variable works only in
nix shell.
> Disable "fortify" causing annoying warning when in nix shell.

- Cargo.lock
- cli/Cargo.toml
- csi/Cargo.toml
- nix/pkgs/mayastor/default.nix
- rpc/Cargo.toml
Very shortly after we updated tonic (beta) the actual first release was made. This
commit moves us to the first release and, removes left over dependency no longer needed.
> grpc: update to tonic release bits

- Cargo.lock
- jsonrpc/src/test.rs
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_module.rs
- mayastor/src/environment/env.rs
- mayastor/src/event.rs
- mayastor/src/lib.rs
- nix/pkgs/mayastor/default.nix
No functional changes; just want to upstream this early before the other wad of changes as it touches Cargo.lock
During tests (that is #[test]) the signal handling results in a crash.
The culprit here is the fact that the test framework starts Mayastor
on a different thread. To avoid this we make the management thread global instead
of store it thread-local.
While here, I've also removed the lazy_static!() and switched us over to
OnceCell and, some minor cleanup in the CAS bdev module. As this requires
a change in Cargo.lock, we might as well updated the dependencies too.
Lastly, the callback to env::start() was called without the proper context.
> nexus: fix signal handling during shutdown

- mayastor-test/test_nexus.js
- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/core/env.rs
- mayastor/src/core/reactor.rs
- mayastor/tests/core.rs
- mayastor/tests/mount_fs.rs
NBD was hanging when we shutdown as we did not wait for any outstanding IO completed. These IO's where not submitted by us rather by systemd-udev.
Secondly, when we use `block_on` our reactor state is not set to running which implies we need to account for handling this case in the shutdown future. This typically affects testing and not normal mode of operations.
> fix NBD and reactor shutdown

- nix/pkgs/libspdk/default.nix
This makes use of new 20.01 branches created in spdk-sys and spdk repositories. Debug version of libspdk nix package was enhanced with more options suitable for running it in debug environments.
> Update spdk-sys submodule to 20.01 branch

- nix/pkgs/libspdk/default.nix
In preparation for building SPDK with the io_uring bdev.
> nix: Add liburing to libspdk.nix

- nix/mayastor-overlay.nix
- nix/pkgs/liburing/default.nix
Upstream nix-unstable moved from liburing 0.2 to 0.4pre, which introduced libdevdir in the configure script. This was not set as part of the build so libspdk_fat.so ended up being linked to liburing.so.1 without a full path, breaking the build of Mayastor.
Override upstream's nix expression by setting libdevdir to libdir, and also moving up to the current 0.5 release.
> nix: Use mayastor-overlay to build liburing

- nix/mayastor-overlay.nix
The hashes for the patches used by lcov are not matching
this change overrides the attribute to get us passed that.
> workaround: nix-unstable is not joking

- csi/moac/README.md
- csi/moac/index.js
- csi/moac/node-packages.nix
- csi/moac/package-lock.json
- csi/moac/package.json
- csi/moac/test/watcher_test.js
- csi/moac/watcher.js
- mayastor-test/package-lock.json
- mayastor-test/package.json
- mayastor-test/test_common.js
- mayastor-test/test_csi.js
This does not fix the security vulnerability in minimist package reported by
npm audit because the old version of minimist package is dependency of grpc
package that hasn't been fixed yet. The plan is that the vulnerability will
go away when we replace grpc package by grpc-js (native grpc implementation
for javascript) and when grpc-mock is patched to use grpc-js rather than grpc.
> Update moac and mayastor-test npm dependencies to the latest versions

- csi/moac/pool_operator.js
- csi/moac/test/node_stub.js
- csi/moac/test/pool_operator_test.js
The problem happens when a pool resource is checked and the node operator
has not finished sync of nodes. In that case pools haven't been read
from the storage node and pool operator thinks they don't exist and
starts to create them. It fails to create the pools and it prints
disturbing messages to the log and makes the moac behave a bit wacky.
The fix is to defer pool creation until the node has been synced.
> Fix race condition in pool operator when moac starts.

- mayastor-test/test_nexus.js
- mayastor/Cargo.toml
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/uring_util.rs
- mayastor/src/bin/uring-support.rs
- mayastor/tests/core.rs
Only test uring bdevs if the filesystem and kernel support it.
Move the functions testing for io_uring support from the core unit test to bdev::uring_util. Add a CLI tool that calls these functions given a path so that it can be called from test_nexus.
> mayastor-test: Test uring bdevs in test_nexus

- Cargo.lock
- Cargo.toml
- nix/pkgs/mayastor/default.nix
- nvmeadm/Cargo.toml
- nvmeadm/src/lib.rs
- nvmeadm/src/nvme_namespaces.rs
- nvmeadm/src/nvme_page.rs
- nvmeadm/src/nvmf_discovery.rs
- nvmeadm/src/nvmf_subsystem.rs
- nvmeadm/tests/discovery_test.rs
This library will be used within the CSI driver to connect, discover
and perhaps other functionality that we might need. This is to avoid
the need of external binaries (like with iSCSI).
This touches Cargo.lock and so we also take the opportunity to
upgrade the dependencies.
> nvmeadm: library to connect to remote nvmf targets

- csi/moac/test/mayastor_mock.js
- csi/src/client.rs
- csi/src/mayastor_svc.rs
- mayastor-test/test_replica.js
- mayastor/src/bdev/uring_util.rs
- mayastor/src/bin/main.rs
- mayastor/src/bin/uring-support.rs
- mayastor/src/pool.rs
- mayastor/tests/core.rs
- rpc/proto/mayastor.proto
- rpc/src/jsonrpc.rs
Add io_if to CreatePoolRequest with permissible values of aio, uring and auto (preferring uring if supported by the kernel) and create the appropriate type of bdev.
Show kernel io_uring support status on startup.
Add a unit test to check for valid I/O interfaces values.
> pool: Allow I/O interface to be configured per-pool

- nix/pkgs/libspdk/default.nix
- nix/pkgs/mayastor/default.nix
- spdk-sys/build.rs
We need to clean up some of the packages and start pinning
to a stable nix-pkgs. This should also mean we remove any stuff we
don't use currently.
> build: remove rdma-core

- mayastor/src/rebuild.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/nexus_rebuild.rs
a management async tasks schedules all copy tasks, awaits them and schedules enough tasks until the bdev is fully rebuilt
(still using a single reactor this time)
> rebuild: run n copy tasks at a time (async tasks)

- mayastor-test/test_nexus.js
- mayastor/src/bdev/nexus/nexus_nbd.rs
Speculating that the root cause is actually the nexus taking "too long"
to complete an IO. Currently, we set the NBD timeout to 1s and it seems
that when we hit this timeout the NBD socket is actually shutdown...
After some testing 3s seems to be enough to keep things happy (at least
on github actions)
> CI issues: mkfs/dd fails randomly on CI

- csi/src/mayastor_svc.rs
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/nexus_rebuild.rs
- mayastor/tests/reconfigure.rs
- When a child is set offline, stop any ongoing rebuilds for that child
- When setting a child online, set its state to faulted and initiate a rebuild
- The reconfigure tests had to be updated to wait for the rebuild to complete before carrying out   some checks.
- Create a common "wait_for_rebuild" utility function
Fixes:
- Add support for offline and online operations to the "child_operation"
- Do not return anything from rpc calls to offline_child and online_child. This prevents error messages being output by rpc clients like mctl. This is because return values were not expected.
> Rebuild: Start rebuild when setting child online

- bors.toml
- we require 2 reviewers
- we do not want merge commits
- clippy in a PR must always pass before we stage it
Not 100% sure yet if this is is final but I think it is.
!!!
Below here things are ignored CAS-1
> bors: update configuration

- .pre-commit-config.yaml
- .prettierrc
- csi/moac/logger.js
- csi/moac/test/csi_test.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/grpc_client_test.js
- csi/moac/test/index.js
- csi/moac/test/nexus_test.js
- csi/moac/test/node_operator_test.js
- csi/moac/test/node_test.js
- csi/moac/test/pool_operator_test.js
- csi/moac/test/pool_test.js
- csi/moac/test/registry_test.js
- csi/moac/test/replica_test.js
- csi/moac/test/rest_api_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/test/watcher_test.js
- csi/moac/test/workq_test.js
- csi/moac/volumes.js
- mayastor-test/sudo.js
- mayastor-test/test_cli.js
- mayastor-test/test_common.js
- mayastor-test/test_csi.js
- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor-test/test_replica.js
Correct a spelling mistake in .prettierrc, and commit the changes
now necessary to have the precommit hooks pass against all of our
files.
I've also altered the precommit hooks so that they no longer alter
code in the repository when they run. This should minimise the effort
required to repair any damage from teething problems with these tools.
> build: fix prettier linting and make hooks read-only

- mayastor-test/test_replica.js
- mayastor/src/bdev/uring_util.rs
- mayastor/src/bin/uring-support.rs
- mayastor/src/pool.rs
Return a URI in the disks field where the URI scheme contains the
base bdev type.
Add a unit test to test creation of pools that use uring bdevs,
though skip the test if the kernel lacks support, which requires
changes to uring-support to only test for kernel support if the
pathname argument is not present.
> pool: Return base bdev type in list pools

- .github/workflows/build.yaml
- nvmeadm/src/nvmf_discovery.rs
- nvmeadm/tests/discovery_test.rs
- test.sh
Make sure 'cargo test' includes nvmeadm in CI.
Add test to .github/workflows/build.yaml and test.sh.
Fix a commonent in nvmeadm/src/nvmf_discovery.rs.
Add a test for connect in nvmeadm/tests/discovery_test.rs.
> nvmeadm: improve test coverage.

- terraform/README.adoc
- terraform/mod/k8s/repo.sh
- terraform/mod/lxd/main.tf
- terraform/variables.tf
Downgrade the lxd image to Ubuntu 18.04/bionic, making it consistent
with the libvirt provider, as 19.04/disco is no longer supported.
Fixes failed package installation from the Ubuntu repositories.
Mount /lib/modules and /boot from the host into the container to allow
kubeadm's pre-flight checks to pass and hence start.
For the k8s installation, install the Docker from a repository that
matches the version of Ubuntu instead of using 16.04/xenial. Move
the comment out of daemon.json as it was causing parse failure and
preventing Docker from starting.
Finally, update the documentation to smooth out some roadblocks.
> terraform: Fix lxd provider to allow k8s to start

- nix/pkgs/ms-buildenv/default.nix
- nix/pkgs/ms-buildenv/root/etc/sudoers
We really don't need sudo, however, some of the GH actions require it.
The reason that some of them need/assume that, is that they can be run
on the host directly or within a container.
> build: add sudo to build image

- .github/workflows/build.yaml
- .github/workflows/nix.yaml
The ms-builldenv is now also done, only when a nix file changes.
> CI: move part of the build to self-hosted

- .github/workflows/build.yaml
- nvmeadm/.cargo/config
- nvmeadm/tests/discovery_test.rs
Spin up an instance of spdk as an nvmf target.
Test discovery, connect and disconnect against this target.
Kill the spdk instance.
Modified .github/workflows/build.yaml to modprobe nvme_tcp in CI.
Added nvmeadm/.cargo/config so that cargo test for nvmeadm uses sudo.
> CAS-196 Test nvmeadm against an nvmf target

- csi/moac/pool.js
- csi/moac/test/mayastor_mock.js
- terraform/mod/k8s/node.sh
Since bcb1cc2 the disks field in the listPools reply contains a URI.
Strip that back to the path only for consistency within moac.
For mayastor-mock, have listPools store a URI to match mayastor's
behaviour.
Reviewed by Jan.
> moac: Strip URI scheme from disks when constructing Pool 

- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/grpc.rs
- mayastor/src/replicas/rebuild/rebuild_api.rs
- mayastor/src/replicas/rebuild/rebuild_impl.rs
- mayastor/tests/nexus_rebuild.rs
- mayastor/tests/reconfigure.rs
- rpc/proto/mayastor.proto
Adds a new get_rebuild_progress rpc to indicate the rebuild progress
Also updates the list_nexus child field:
1. adds a rebuild progress to the child
2. maps the child states to a more simplified version for moac
Also fixed a bug where a non faulted child could self rebuild itself
and added tests for this
Added document relevant to this: https://mayadata.atlassian.net/wiki/spaces/MS/pages/53870599/Mapping+of+Nexus+to+Moac+Child+States
CAS-181
CAS-193
> rebuild: add progress and map child states

- .github/workflows/build.yaml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/core/env.rs
- mayastor/src/core/handle.rs
- mayastor/src/core/mod.rs
- mayastor/tests/reset.rs
The code this commit refers to has already been included in
cas-79 but this commit adds explicit testing of those changes.
Includes gila's rust-based testing of reset functionality in a
new unit test plus support for the reset IO in the core handle
code.
Also included is a command-line option to pass addition options
to the EAL environment to aid debugging.
The number of huge pages available was increased from 2048 to 8192
to avoid memory issues seen in the reset test.
> CAS-225. Handling for reset IO in nexus function table.

- .github/workflows/build.yaml
Switching from 8192 hugepages in the unit tests to 2048 hugepages in the mocha tests causes problems. Solve this by using 8192 in both tests.
> CI: Use 8192 huge pages throughout the test

- csi/src/node/iscsiutil.rs
- mayastor-test/test_nexus.js
- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/mount_fs.rs
- mayastor/tests/nexus_rebuild.rs
Return device path as a URI always!
Handle device path as a URI instead of a path to the device
Fix a typo and copy and paste error in iscsiutil
> Fix CSI volume provisioning for NBD devices

- doc/quick.md
- nix/pkgs/libspdk/default.nix
State the SSE4.2 instruction set requirement and list the processors
that satisfy that requirement. Also change the libspdk build flag to
-march=nehalem as -march=corei7 was renamed in gcc-4.9.
Update the requirements section and minor fixes for the rest of the
document.
> doc: Clarify CPU architecture requirements in quick.md

- csi/src/client.rs
- mayastor-test/test_cli.js
I have reworked the mayastor-client:
Streamlined the command line argument handling;
Completed the implementations of nexus, pool, and replica functionality;
Ensured input byte sizes are acceptable as bytes, or with binary & SI multipliers;
Output byte sizes shown as bytes, command line options to switch to binary or SI multipliers.
CAS-69 CAS-70 CAS-71 CAS-77
> Reworking the mayastor-client

- doc/build.md
- doc/quick.md
- mayastor-test/README.md
./test.sh now requires that the nvme_tcp module be loaded.
> Update docs to allow for running tests locally.

- csi/src/node.rs
- csi/src/node/iscsiutil.rs
Mounting iscsi targets with the std rust library,
results in creation of loopback devices and mounting
of the volume on the loopback devices.
Also unmounts were not destroying the loopback devices.
Workaround by resolving the absolute path of the iscsi
target to avoid the issue.
> Change so that mount does not use loopback

- doc/quick.md
Rework the structure of the Quickstart guide:
1. Prioritise Storage Node configuration ahead of deploying mayastor on the cluster
2. Provide a definition of what a Storage Node is, within the context of mayastor
3. Update tested platforms with AKS information
4. Update example commands given for checking and setting 2MB huge page support.
(sudo tee now used as this works on AKS)
5. Update example commands given for creating storage classes, to clearly identify the transport
(ie. nbd vs iscsi)
Also, remove reference to NVME_TCP module in "Requirements" section as this isn't supported by the CSI driver in this release
> Reformat and update the Quickstart Guide

- mayastor/src/pool.rs
The code that determines the base bdev type inadvertently used
lvs_bdev_ptr after it had already been destroyed. Switch to base_bdev
instead so that that the base bdev type can be determined.
Fixes: bcb1cc2 ("pool: Return base bdev type in list pools")
> pool: Fix failure to destroy pool

- csi/moac/nexus.js
- csi/moac/test/mayastor_mock.js
- csi/moac/test/nexus_test.js
- csi/moac/test/volumes_test.js
- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_rpc.rs
- mayastor/src/grpc.rs
- mayastor/tests/nexus_rebuild.rs
- rpc/proto/mayastor.proto
When a  child is added the control plane expects mayastor to rebuild
the child. Added a new parameter to add_child which allows for this
whilst also allowing for a finer grained control over rebuild.
Adjusted all the required tests for this including semistandard fixes
Added a test to verify that the new parameter works as expected
Resolves CAS-149
> Automatically rebuild when adding a new child

- mayastor-test/test_csi.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/core.rs
When a child fails to be added due to a different block size or invalid
size the returned error does not use the name form the bdev which is
now destroyed.
When adding a new child the size of the child has to be larger than the
minimum required.
The nexus bdev now takes into account the requested size when it was
created rather than just looking at its children sizes.
At the moment new children need to be as large as the smallest child,
this is due to the partition being done in relation to the smallest
child. We might want to consider doing it in relation to the nexus size
+ metadata.
Resolves CAS-247
> nexus: address child sizing mismatches

- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/tests/common/ms_exec.rs
- mayastor/tests/io.rs
- mayastor/tests/replica_timeout.rs
Create a new replica timeout test, based on the existing reset test,
that performs I/O, brings down one Nexus child via a SIGTERM followed
by performing a read, which must pass, then bringing down the
remaining Nexus child followed by another read, which must fail.
This requires Bio::assess to mark the IO as failed if the child IO
failed otherwise it can return a read as success with the buffer
untouched.
Also fix an off-by-one bug in the existing io_test.
> mayastor-test: Test Nexus child going offline

- terraform/variables.tf
Pods are getting evicted in response to disk pressure event with
libvirt provider in some cases.
> Increase the default disk size in TF scripts to 6G

- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/tests/core.rs
Make Nexus::destroy_children close a child first before destroying it,
making its behaviour match the code comment.
Addresses this panic when creating a Nexus with multiple children
where the 2nd or later child is inaccessible:
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `Init`,
right: `Closed`', mayastor/src/bdev/nexus/nexus_child.rs:218:9
Fixes: 63bd078 ("nexus: add more test cases for adding children")
Resolves: CAS-297
> nexus: Close child when destroying all Nexus children

- mayastor/src/core/env.rs
- mayastor/src/subsys/opts.rs
- mayastor/src/target/iscsi.rs
- mayastor/src/target/nvmf.rs
- mayastor/tests/replica_timeout.rs
- mayastor/tests/reset.rs
The preferred method for having multiple iSCSI target portals is to use different IP addresses, together with the well known port (3260). As this is not straightforward to do for kubernetes pods (which have a single IP address) we need to use other non-standard ports. In this case we need to allow the port values to be configurable.
resolves CAS-144
> CAS-144 Allow default nexus and replica iSCSI target and nvmf ports to be overridden.

- .github/workflows/pr.yaml
- mayastor-test/sudo.js
If we only lint javascript files which have changed in the most recent
commit, files changed in previous commits in a PR won't be checked.
We also wouldn't run the linter for a PR which updates the toolchain.
Either of these scenarios would leave extra work for future developers
working on unrelated changes.
(As part of rolling this out, also updated sudo.js to conform to the
current linting standard.)
> ci: Have the linter check all javascript files

- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_child_error_store.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/subsys/config.rs
- mayastor/src/subsys/opts.rs
- mayastor/tests/error_count.rs
- mayastor/tests/error_store.rs
- spdk-sys/wrapper.h
CAS-241. Functionality to store and query a record of recent errored IOs in each nexus child and a means of enabling the feature and setting the buffer size.
Test added which adds an error bdev layer between the nexus and one of its
replicas and allows unit testing of the feature. Also included unit testing
of the error store independenly of the bdev.
Addressed some code-review comments, ops and errors are stored
instead of flags, also made the ordering of parameters more consistent.
Use monolithic time instead of absolute time in error store.
Using message-passing to the management core.
Addressed some code-review comments, ops and errors are stored
instead of flags, also made the ordering of parameters more consistent.
Use monolithic time instead of absolute time in error store.
Using …
> CAS-241. Functionality to store and query a record of recent errored IOs

- csi/moac/README.md
- csi/moac/default.nix
- csi/moac/node-composition.nix
- csi/moac/node-env.nix
- csi/moac/node-packages.nix
Strip build-time dependencies of moac from docker image. It is a dirty
hack though I haven't found a better solution than patching generated
nix files. NPM and NIX aren't friends and this is what you get when
you invite both of them to your house :-) On a positive note we should
be able to remove the workaround when we won't have any modules with
bindings. That means when we get rid of grpc-uds that we plan to do
anyway soon.
The size of moac image dropped down from 981 MB to 271 MB.
Note 1: A lot of the changes are formatting changes as our nix style tool and
node2nix tool don't agree on what is the preferred style of nix files :-)
Note 2: we switch from production to development nix pkg generation, the only
difference is that packages from devDependencies are included as well (mocha, …
> Reduce the size of MOAC docker image (CAS-306)

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- jsonrpc/src/test.rs
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/src/core/descriptor.rs
- mayastor/src/core/mod.rs
- mayastor/src/replicas/rebuild/rebuild_api.rs
- mayastor/src/replicas/rebuild/rebuild_impl.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/lock_lba_range.rs
- mayastor/tests/nexus_metadata.rs
- mayastor/tests/nexus_rebuild.rs
- nix/pkgs/libspdk/default.nix
- nvmeadm/src/nvmf_discovery.rs
- spdk-sys/build.rs
- test.sh
- Provide the ability to lock/unlock LBA ranges when rebuilding a segment.
- Temporarily change the Docker build image that is used so that we can use the SPDK changes to support the locking/unlocking.
- Additional sleeps have been introduced in various test cases to allow time for the rebuild operations to take effect. The locking/unlocking seems to have affected the test timings somewhat.
> CAS-214: Add support to lock/unlock LBA ranges

- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/replicas/mod.rs
- mayastor/src/replicas/rebuild/rebuild_api.rs
- mayastor/src/replicas/rebuild/rebuild_impl.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/nexus_rebuild.rs
- mayastor/tests/reconfigure.rs
added a few more testcases and that led to fixing a few bugs
rebuild with childs of different sizes (prior that would fail) including
using children with sizes < metadata
using non multiple of the segment size for completeness
the lookup of rebuild jobs and concurrent rebuild jobs which revealed a
bug
rebuild operations idempotence (currently on the client api) though we
may want to restrict it to RPC specifically
bonus: when the rebuild tests fail (local or CI) the cargo test itself
gets stuck which is caused by panics on a different thread (?) so moved
the failures to the reactor thread and also use different nexus and bdev
names on each test - this produces a cleaner failure log
rebuild code coverage reported by grcov is now ~84% (if you trust it)
todo: cas-287 will test the IO …
> rebuild: more testing bug fixes (CAS-246)

- mayastor/src/bdev/aio_dev.rs
- mayastor/src/bdev/iscsi_dev.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nvmf_dev.rs
- mayastor/src/bdev/uring_dev.rs
- mayastor/src/core/descriptor.rs
- mayastor/src/core/dma.rs
- mayastor/src/core/mod.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/replicas/rebuild/rebuild_api.rs
- mayastor/src/replicas/rebuild/rebuild_impl.rs
- mayastor/tests/common/error_bdev.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/error_count.rs
- mayastor/tests/lock_lba_range.rs
- mayastor/tests/nexus_rebuild.rs
Fault destination child when the rebuild fails allowing MOAC to replace
it with another when it detects the Faulted state.
Added tests using existing bdev error functionality to inject failures
on both src and dst children during a rebuild to verify that the dst
child is faulted.
todo: if the failure was caused by the src child we should be able to
replace that child with another and proceed with the rebuild
> rebuild: fault child on failure (CAS-287)

- csi/src/node.rs
- csi/src/server.rs
- mayastor/src/bin/main.rs
- nix/lib/nixPackages.nix
- nix/lib/rust.nix
- nix/mayastor-overlay.nix
- nix/pkgs/libspdk/default.nix
- nix/pkgs/liburing/default.nix
- nix/pkgs/mayastor/default.nix
This changes does some small changes:
- we now point mayastor/default.nix to an actual commit we release
- bumped packages of nixpkgs itself and liburing
- bumped rust overlay such that are are on rust stable 1.44 (from 1.41)\
- bumped liburing 0.5 -> 0.6
- all images pkgs, by default now, are built in release mode
- fixed the libspdk/default.nix (not all variable are set by configure)
To create an image we can run:
```
skopeo copy docker-archive:/$(nix-build -A mayastorImage --no-out-link)
docker://mayadata/mayastor:gila
```
(NOTE: mayastorImage == mayastoreCSIImage)
If you want "debug" images, you can make this change in your local
check-out (by updating nix/mayastor-overlay.nix. This will also pick up the
sources from the git tree and not fetch them from github.
Also, please be aware …
> nix: make release build easier

- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/nexus_uri.rs
Add missing nvmf namespace identifier to the bdev name
Additionally fault the child if a rebuild fails to start
> CAS-317: Fixup rebuild of nvmf replica

- deploy/README.md
- deploy/mayastor-daemonset.yaml
- deploy/moac-deployment.yaml
Update the moac deployment and mayastor daemonset yaml files to reflect the correct image tags for this release (i.e. imagename:v.0.2.0)
Update the README.md (Quickstart guide) to remove references to this release having been tested on Azure AKS, since we know that there are possibly some issues with this at this time and further investigation is required.  The notes on AKS section is left in situ, since this is very likely to still apply to Azure deployments.
> Prepare deploy folder content for v0.2.0 staging

- deploy/README.md
- deploy/mayastorpoolcrd.yaml
When the timing is "just right" applying the pool yaml file fails
because it's up to moac to register the pool crd.
Add the pool crd to the deployment which might facilitate new installs
> CAS-321: add mayastorpool.yaml to deployment

- csi/moac/node.js
- csi/moac/pool.ts
- csi/moac/test/mayastor_mock.js
- csi/moac/test/node_test.js
- csi/moac/test/pool_test.js
- rpc/proto/mayastor.proto
... even if there is no change
I reworked the logic a little bit. Previously we have ignored changes to the disk because it was considered as an awkward situation that we didn't know how to respond to. However ignoring such change is not a solution because then msv resources don't reflect the right state on the storage node (the resource did not exist when this code was written). So I think that now the code works better and it fixes the bug that was the primary motivation for changing it.
> CAS-312 moac logs a warning about unexpected disk change

- csi/moac/package.json
- csi/moac/watcher.js
It can happen that generation number remains the same in case when status part of CRD is changed. In that case the event is of no interest to us (because moac makes status changes so it would react to self), but we should print less disturbing message to the log file.
Resolves: CAS-316
> moac emits debug messages about stale object events (CAS-316)

- .github/workflows/pr.yaml
- csi/moac/node_operator.js
- csi/moac/test/watcher_stub.js
- csi/moac/test/watcher_test.js
- csi/moac/watcher.js
Makes use of the existing work queue to serialise node updates
Sometimes the watcher is out of date with k8s. A temporary fix is to
always bypass the cache and get the information we need directly from
k8s and update. We also update the watcher cache with the new value.
(I've raised cas-328 to track this issue)
Also added the corresponding watcher tests
> moac: msn is out of date (CAS-327)

- csi/moac/nexus.ts
- csi/moac/test/volumes_test.js
- csi/moac/volume.js
- csi/moac/volume_operator.js
When a new child is added, the msv is temporarily showing incorrect
information until we get back a grpc list response. Instead, set the
child as pending until we retrieve the correct information via the list
nexus.
The update volume is also failing as there are concurrent updates, so
serialise these using the workq and also bypass the cache.
> moac: msv is out of date (CAS-323)

- csi/moac/csi.js
- csi/moac/test/csi_test.js
After reinstall k8s keeps calling us to unpublish a volume which does
not exist anymore. To stop this forever loop return ok instead of
returning not found if the volume does not exist...
> moac: unpublish old volume (CAS-326)

- Cargo.lock
- csi/Cargo.toml
- csi/src/node.rs
- csi/src/node/iscsiutil.rs
- csi/src/node/nvmfutil.rs
- deploy/mayastor-daemonset.yaml
- deploy/storage-class.yaml
- mayastor-test/test_csi.js
- nix/pkgs/images/default.nix
- nix/pkgs/mayastor/default.nix
- nvmeadm/Cargo.toml
- nvmeadm/src/nvmeadm.rs
- nvmeadm/src/nvmf_discovery.rs
Add nvme-of support to the CSI plugin, to make
nexuses shared over NVMe-oF available on kubernetes.
Add nvmeadm utility execuatble, primarily as a development
aid for the nvme library code.
Update k8s yaml files to facilitate functioning of NVMe-oF
from within the pod container.
> Provision NVMe-oF volumes. CAS-81

- csi/src/node/nvmfutil.rs
Use the correct nqn prefix
Handle the return value of nvmeadm::nvmf_discovery::disconnect
> Correctly disconnect nvme devices CAS-337

- mayastor/src/bdev/dev/aio.rs
- mayastor/src/bdev/dev/iscsi.rs
- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/dev/nvmf.rs
- mayastor/src/bdev/dev/uring.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/core/bdev.rs
During the URI work, the struct Bdev was marked as
Send. This should not be the case.
Send means that the Struct Bdev would be safe to send to other
threads. There is nothing that guarantees that however.
> bdev: struct Bdev should not be sync

- csi/moac/node.js
- csi/moac/registry.js
- csi/moac/volume.js
When a node leaves it should at least unbind its existing resources.
todo: when a node is removed gracefully should we also destroy the
pools?
Also we now replace children which have no underlying replica with new
ones during the volume fsa irregardless of the online count which seems
reasonable.
> CAS-341: replica not replaced when node leaves

- mayastor/tests/lock_lba_range.rs
Added an additional reactor_poll to allow the second lock to be
obtained.
> CAS-343: Re-enable the multiple_locks unit test

- csi/src/node/iscsiutil.rs
- csi/src/server.rs
Make isci attach idempotent:
If a session for the target portal and iqn exists,
skip to just waiting for the device path to exist.
Refine the waiting for device path code,
1) specify granularity of sleeps,
2) reduce the timeout from 10 seconds to 1 second,
on the grounds that large timeouts can mask issues.
> CSI attach idempotency. CAS-340

- csi/moac/node.js
- csi/moac/test/node_test.js
The problem was that the node was marked as online only after calling
various merge object functions, so if those functions wanted to call
RPC method on the node, it failed.
> moac: pool creation fails when storage node is imported (CAS-336)

- csi/moac/csi.js
- csi/moac/test/csi_test.js
- csi/moac/test/index.js
The constraint to schedule app locally on storage node is preserved for NBD. For iSCSI and nvmf the k8s scheduler is free to use any node with running mayastor csi plugin.
The fix to split mayastor daemon yaml file and decouple csi plugin from mayastor is ready and will follow this PR.
> Remove k8s scheduler constraint for iscsi/nvmf volumes (CAS-295)

- deploy/README.md
- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
csi-agent runs on all nodes so that iscsi and nvmf exported volumes can be mounted anywhere.
> Split mayastor daemonset yaml into csi-agent and mayastor yamls (CAS-294)

- .github/workflows/nix-tests.yaml
- mayastor/tests/common/mod.rs
- mayastor/tests/mount_fs.rs
Temporarily disable the "Nix Workflow Tests" which occasionally just
stays queued and doesn't seem to run:
"Nix Workflow Tests / Run Nix Tests (pull_request)...
Queued — Waiting to run this check... "
Also, while we're here unaffinitize the threads used in the mount_fs
tests to reduce contention and also and bring assert to the reactor
thread so we can fail a bit more gracefully.
> address some CI issues

- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/dev/aio.rs
- mayastor/src/bdev/dev/iscsi.rs
- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/dev/malloc.rs
- mayastor/src/bdev/dev/nvmf.rs
- mayastor/src/bdev/dev/uring.rs
- mayastor/src/bdev/util/uri.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/subsys/config.rs
Support for optional UUID query parameter for storage URIs, example:
aio:///disk1.img?blk_size=512&uuid=e40efd60-05a9-4f96-99af-1b6a25e109dd
If one is provided then we set the uuid of the bdev to that.
> CAS-344: add UUID to URI format

- mayastor/src/rebuild/rebuild_impl.rs
- mayastor/tests/add_child.rs
The rebuild job requires the nexus descriptor to lock/unlock LBA ranges.
It is not necessary for the descriptor to be writable to use this
functionality. Furthermore, if the nexus is shared (i.e. over iscsi),
it is claimed, thereby prohibiting another writable descriptor being
opened against it.
> CAS-372: Use read-only nexus descriptor in rebuild job

- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor/src/bdev/dev/aio.rs
- mayastor/src/bdev/dev/iscsi.rs
- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/dev/malloc.rs
- mayastor/src/bdev/dev/nvmf.rs
- mayastor/src/bdev/dev/uring.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/core/bdev.rs
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/tests/nexus_rebuild.rs
- rpc/proto/mayastor.proto
All "URI devices" are now created and set to their proper name and not
the full URI. The URI is still set as an alias which the rest of the
code currently relies on.
For example an aio device:
aio:///dev/ram0?blk_size=512 now has the name /dev/ram0
Add aliases to the output of mayastor-client bdev list subcommand.
Also, destroy the nexus children when failing to create a nexus with a
generic error. This fixes a JS test which was "passing" incorrectly.
Also temporarily "patch" that test which was not failing as expected.
> CAS-345: normalize the dev name

- mayastor/src/bin/cli/cli.rs
- mayastor/src/bin/cli/nexus_cli.rs
- mayastor/src/bin/cli/rebuild_cli.rs
Added support for the following rebuild operations:
- start
- stop
- pause
- resume
- state
- progress
Added the optional "norebuild" argument to the "nexus add" command. This
determines whether or not a rebuild is started automatically for the
added child. If false, a rebuild is started. If true a rebuild is not
started. (Note: false is the default value)
> CAS-373: Add rebuild support to mayastor-client

- csi/moac/crds/mayastorpool.yaml
- csi/moac/pool_operator.js
- csi/moac/test/pool_operator_test.js
Add a new field "disks" to status part of mayastor pool CRD. The
difference between disks in spec and status part is that spec part
describes what is desired (i.e. /dev/sdb) and the status part tells what
is actually used (i.e. aio://dev/sdb). They should be the same except
the protocol part in some cases.
> moac should accept URIs for pool devices (CAS-311)

- csi/moac/default.nix
- deploy/storage-class.yaml
Remove nbd storage class from example storage class yaml
Make image tags in the develop branch consistent i.e. develop
> Remove nbd storage class and tag moac image as develop in dev

- mayastor-test/test_rebuild.js
- mayastor/src/rebuild/rebuild_impl.rs
- mayastor/tests/nexus_rebuild.rs
The amount of data that can be rebuilt at any given time has been
increased from 40KiB to 1MiB.
The number of concurrent copy tasks is increased to 16, with each task
copying 64KiB of data.
> CAS-377: Increase the rebuild data size

- mayastor/README.md
- mayastor/tests/add_child.rs
- mayastor/tests/nexus_rebuild.rs
- nvmeadm/tests/discovery_test.rs
pause rebuild between checks
bump up the number of shared buffers
update README with an actual example
delete tmp disk files before truncation
> fix nvmeadm and rebuild tests

- csi/src/dev.rs
- csi/src/dev/iscsi.rs
- csi/src/dev/util.rs
- csi/src/match_dev.rs
Modified match_iscsi_device() so that it no longer refers to the "ID_SCSI_SERIAL" attribute when searching for iSCSI devices, as there is no guarantee that it will be present in the udev device record.
Fixed bug in extract_uuid().
> CAS-382 CSI plugin should not assume "ID_SCSI_SERIAL" attribute is present in udev records for iSCSI devices

- mayastor/src/bdev/dev/iscsi.rs
- mayastor/src/bdev/dev/nvmf.rs
replicas for the same volume have the same UUID which caused collisions
when trying to open them in the nexus
Include 'host:port/' in the bdev name for nvmf/iscsi
todo: add test case
> fix bdev replica names

- mayastor/src/bdev/nexus/nexus_child_error_store.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/tests/error_count.rs
CAS-351: This enables the option of removing a child if the error count exceeds a limit, currently set at 5 errors in 10 seconds for each child.
This also limits the stored errors to reads and writes to prevent flush errors (seen when using nvmf on the front end) from filling the error store.
> CAS-351: Error handling in Kubernetes cluster.

- mayastor/src/core/bdev.rs
- mayastor/src/core/share.rs
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/src/nexus_uri.rs
- mayastor/src/pool.rs
- mayastor/tests/pool.rs
This change will create base bdevs using URIs if we are passed
a valid scheme. If we use the legacy model where we specify
a device path like /dev/sdx -- we will use that
> pool: support creation by means of URIs

- csi/src/block_vol.rs
- csi/src/filesystem_vol.rs
- csi/src/mount.rs
- csi/src/node.rs
- csi/src/server.rs
- mayastor-test/test_csi.js
To support block volumes.
at node stage volume
- attach to the device
at node publish volume
- create a block special file
- bind mount the device path to the block special file
at node unpublish volume
- unmount the block special file
- delete the block special file
at node unstage volume
- detach from the device
To facilitate this
At staging ensure the sequence of operations is
1 Attach the device.
2 For fs volumes only, mount the device on the staging path.
At unstaging ensure the sequence of operations is
1 For fs volumes only, unmount staging path from the device.
2 Detach the device.
Ensure that each of the above operations are idempotent.
For clarity move
- filesystem volume functions (un/stage, un/publish),
- block volume (un/publish)
to separarate files.
> Add support for block volumes. CAS-14

- deploy/mayastor-daemonset.yaml
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/config/mod.rs
- mayastor/tests/yaml_config.rs
CAS-348: Export the config file on "state-changing" grpc calls
If we fail to export (unexpected) then we fail the grpc and rely on the
control plane to retry - methods should be idempotent
Change the config device creation order:
1. pools
2. share pool replicas (if shared)
3. nexus (may be using the pool)
only if IMPORT_NEXUSES is true as when a node comes back up it may have
outdated view of the volumes and it would be dangerous to blindly
recreate the nexuses
4. base bdevs (last, otherwise the nexus fails to create)
CAS-349: persist the config ...
for k8s in the following host path: /var/local/mayastor/config.yaml
This is achieve using the host path volume:
directoryOrCreate type mount to create the path
fileOrCreate type mount to create the file
set IMPORT_NEXUSES env variable to false …
> CAS-348: export config on grpc / CAS-349: persist the config in k8s

- mayastor/src/subsys/config/opts.rs
Increase error limit to 64, 5 is possibly too low to correctly handle events such as pod restarts.
> Increase error limit to 64

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/core/handle.rs
- mayastor/src/core/mod.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/src/subsys/nvmf/mod.rs
- mayastor/tests/replica_snapshot.rs
This implements basic functionality to allow a Nexus to create
a snapshot on a replica using an NVMe Admin command.
Add NVME_ADMIN as a permitted IO type and implement NVMe Admin
Passthru starting from BdevHandle as a standalone function until it
reaches nexus_bdev. Creating a snapshot sends an admin command with
opcode c0h and the current Unix time in cdw10/11.
Register a custom command handler for NVMe Admin opcode c0h with SPDK
to handle snapshot creation when initialising the NVMf subsystem.
The handler creates a snapshot against the replica (lvol) by calling
vbdev_lvol_create_snapshot with a snapshot name derived from the
timestamp. Complete the NVMf request in the snapshot done callback.
The snapshot is then available in the list of replicas.
Add a test of NVMe Admin commands first …
> CAS-330: Expose lvol snapshot functionality

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/core/handle.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/nvmf/admin_cmd.rs
- mayastor/src/subsys/nvmf/mod.rs
- mayastor/tests/common/bdev_io.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/io.rs
- mayastor/tests/replica_snapshot.rs
- mayastor/tests/replica_timeout.rs
Move NVMe admin command handler to the nvmf subsystem.
In Replica, move the snapshot done callback to the function that uses
it, refactor use of nvme_status, and use ffihelper for conversion to a
C string.
Add function comments where appropriate.
In the integration tests, factor out read_some and write_some to
common and swtich current users to that.
Fixes: d909c1e ("replica: Implement create_snapshot")
> snapshots: Minor refactoring

- mayastor/tests/error_count.rs
Some cargo tests were failing because the management thread did not have enough time to process futures sent to it.
Increased time the reactor is allowed to run before querying the error store.
> Allow longer for errors to propagate in error-count test.

- .github/workflows/image.yaml
- csi/moac/README.md
- csi/moac/default.nix
- doc/build.md
- nix/lib/version.nix
- nix/mayastor-overlay.nix
- nix/pkgs/images/default.nix
- nix/pkgs/mayastor/default.nix
- nix/sources.json
- nix/test/basic/fio_nvme_basic.nix
- nix/test/rebuild/rebuild.nix
- terraform/README.adoc
There are two flavours of mayastor nix package: mayastor and
mayastor-dev. The same for csi plugin package mayastor-csi and
mayastor-csi-dev. They don't get accidentaly confused by the build
system as was happening before with "release" parameter that made
creating the release packages very error-prone.
Overhaul of nix code for creating docker images. No code duplication
and intuitive target names. All image targets end with "-image" suffix.
The flavour of the package that the image is based on (if any) preceeds
the suffix (i.e. dev or adhoc). Nix code for moac image is part of
images now and follows the same rules.
We are able to derive the accurate version number of mayastor package
in fully automated way. It uses a git command to lookup a tag of the
top-most commit and if the tag does …
> Proper mayastor debug package and code cleanup.

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_io.rs
Ensure the status field in the NioCtx gets defined when the Bio is created. 
This change also reduces some code duplication by adding a constructor for the Bio.
> CAS-399 Ensure status field in NioCtx is always defined.

- mayastor-test/test_replica.js
- mayastor/src/bin/initiator.rs
Add a create-snapshot command for the standalone initiator binary
and have test-replica use that to create a snapshot and verify that it
appears in the list of replicas.
Extends #370.
> snapshots: Add regression test via initiator

- nix/pkgs/libspdk/default.nix
Upgrade spdk to the latest v20.07.x-mayastor
This fixes the reconnects that were failing due to an adminq leak
- this was triggered by the keep alives when the socket was disconnected
> CAS-400: Fix nvmf reconnect

- deploy/README.md
Fix typo in deployment quick start guide of Storage Pool definition.
> Fix quick start guide README typo

- deploy/fio.yaml
tini handles signals properly allowing k8s to kill the container
with SIGTERM and thus avoid the grace period followed by SIGKILL
> add tini init system to the fio container

- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/rebuild/rebuild_impl.rs
- mayastor/tests/nexus_rebuild.rs
The cancel_child_rebuild_jobs function was, among other things,
cancelling all rebuild jobs with the child as a source, and then
restarting them with the intention that they would use a different
source child. In reality, the same source child could be chosen as the
state of the child was typically updated after the call to this function.
This fix splits the function into two separate cancel and start
functions. The caller is responsible for first cancelling the rebuilds,
then updating the child state appropriately before finally restarting
any previously cancelled rebuild jobs.
Additional fixes:
1. Fix the rebuild_lookup test to iterate over all "non-added" children.
2. Fix the uri in the destination handle error message.
> CAS-402: Fix cancel_child_rebuild_jobs

- csi/moac/crds/mayastorvolume.yaml
- csi/moac/csi.js
- csi/moac/test/csi_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.js
- csi/moac/volume_operator.js
- csi/moac/volumes.js
- mayastor-test/test_nexus.js
- mayastor/src/subsys/config/mod.rs
Moac should not attempt to recreate new volumes based on the existing
CRDs on startup as this could lead to having a completely new data.
Rather, it now simply imports them and attaches existing replicas.
If a replica is currently not online then at the moment it will be
removed. Unfortunately there is an issue when trying to add a replica
from the same node again, see cas-426
> CAS-424: import volumes on startup

- mayastor/Cargo.toml
- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_metadata.rs
- mayastor/src/bin/casperf.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/core/bdev.rs
- mayastor/src/core/dma.rs
- mayastor/src/core/handle.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/reactor.rs
- mayastor/src/core/thread.rs
- mayastor/src/rebuild/rebuild_impl.rs
- spdk-sys/logwrapper.h
This tool allows us to pump IO full speed to supported storage URI's.
The intent of this is to be able to test performance without the need
for setting up any targets and, subsequently, benchmark tools.
Its nowhere near as sophisticated as fio, but that's also not the
intent. The intent is to get good numbers but also, to assist in
testing/developing the handling of IO errors and rebuild.
The PR is a bit noisy as I removed some of the (needless) cast operations. This was an artifact still of the many upgraded we have done in the past. 
Right now, only READs are implemented (it is safer to develop)
> Want simple performance tool

- csi/moac/pool_operator.js
- csi/moac/test/node_stub.js
- csi/moac/test/pool_operator_test.js
Sync Nodes with the pools on the 'mod' event as well as the 'sync'.
'sync' covers the case where the node has already been added to the
registry and synced which. In this case the event stream will replay
this and so we need to pre-populated the resource list.
'mod' is the other case where the pool custom resource gets processed
before the node is synced or when it is down.
Added a log message when resources are pre-populated which as otherwise
we might not see any indication of pools being processed.
> CAS-407: moac pool resource ignored

- Cargo.lock
- csi/Cargo.toml
- csi/src/block_vol.rs
- csi/src/error.rs
- mayastor-test/test_csi.js
- nix/pkgs/images/default.nix
- nix/pkgs/mayastor/default.nix
Also add an idempotency fix to block volume publishing.
We now use the findmnt utility to check if the device is already
mounted.
A side effect of that change is that we return an error in the
unlikely case that another device is mounted at the same location.
> Add mocha tests for CSI block volumes. CAS-379

- mayastor/src/subsys/nvmf/target.rs
Correcting the log msg text emitted during the target's final init phase ("role" -> "roll")
Because it's Friday, we're on a commit roll and I want "in" on it :-)
> Correcting minor typo in nvmf target.rs

- mayastor/tests/reactor.rs
Reactor test required the test system to have more than 4 cpus
otherwise test threads panic'd but not the main thread. Most of
the time the test passed while producing strange panic stacks in
the log, but sometimes the test failed with cryptic error message
in the description.
The requirement has changed to having at least 2 vcpus that most
likely all test machines will have. The problem with an error that
is not propagated to the main thread will be solved on behalf of
a different ticket.
> Lazy instance has previously been poisoned in rust tests (CAS-432)

- deploy/pool.yaml
Use `generateName` in the msp example in the deployment directory.
With this users won't have to give their pools unique names
> CAS-17: auto pool names

- mayastor-test/test_replica.js
- mayastor/src/replica.rs
- mayastor/src/subsys/nvmf/admin_cmd.rs
- mayastor/tests/replica_snapshot.rs
The call to vbdev_lvol_create_snapshot ultimately ends up in
spdk_bs_open_blob where it asserts that the current spdk thread is the
md_thread, which in Mayastor terms is the management reactor.
Ensure that by having nvmf_create_snapshot_hdlr call
Replica::create_snapshot via the management reactor. Addresses:
mayastor: blobstore.c:6677: bs_open_blob: Assertion `spdk_get_thread() == bs->md_thread' failed.
when running against a debug build of SPDK.
Re-enable the mocha test disabled in 0c1687ca and re-add the Rust
integration removed in 2e9acb9.
Resolves: CAS-404
Fixes: d909c1e ("replica: Implement create_snapshot")
> snapshots: Perform snapshot operations on the management reactor

- csi/src/block_vol.rs
It appears the findmnt returns bind mounts in different formats,
on different boxes.
for example dev[/nvme0n1], udev[/nvme0n1], tmpfs[/nvme0n1]...
So use a more relaxed regular expression to determine the device.
> For greater portability relax block mount check.

- mayastor-test/test_common.js
- mayastor-test/test_snapshot.js
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_snapshot.rs
- mayastor/src/bin/cli/cli.rs
- mayastor/src/bin/cli/snapshot_cli.rs
- mayastor/src/core/handle.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/nvmf/admin_cmd.rs
- rpc/proto/mayastor.proto
- scripts/node-test.sh
Implement create_snapshot against a nexus over gRPC and the
mayastor-client CLI. This basically calls BdevHandle::create_snapshot
which sends our vendor-specific NVMe Admin command to all children.
Returns name of the snapshot over gRPC, derived from the nexus name
but is not used anywhere else at the moment.
Add a mocha test for create_snapshot against a nexus with 1 child
replica over gRPC. This requires changes to functions in test_common
to allow more than 1 instance of Mayastor to be started and to ensure
that those multiple instances are stopped.
> CAS-392: Add create snapshot support to RPC and CLI

- .github/workflows/nix-tests.yaml
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_child_status_config.rs
- mayastor/src/bin/cli/cli.rs
- mayastor/src/bin/cli/nexus_child_cli.rs
- mayastor/src/bin/cli/nexus_cli.rs
- mayastor/src/bin/cli/rebuild_cli.rs
- mayastor/src/core/env.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/subsys/config/mod.rs
- nix/test/basic/fio_nvme_basic.nix
- nix/test/child_status/child_status.nix
- nix/test/common.nix
- nix/test/default.nix
- nix/test/disconnect/disconnect.nix
- nix/test/rebuild/rebuild.nix
- rpc/proto/mayastor.proto
Child status information is now persisted to a configuration file (a
yaml file currently stored in the /tmp directory). Whenever the child
status changes, the configuration file is updated to reflect this.
When Mayastor starts, it reads in the configuration file and sets the
child status accordingly. Any children in the "degraded" state will be
automatically rebuilt (regardless of the state of the rebuild when
Mayastor was stopped).
Support has been added to the mayastor-client to fault a child. The
command looks like:
mayastor-client nexus child fault <nexus_uuid> <child_uri>
**Note: For now the configuration file is saved in the /tmp directory. Where this should actually be saved will be subsequently addressed.**
> CAS-125: Restart rebuilds when Mayastor restarts

- mayastor/src/bdev/nexus/nexus_nbd.rs
- mayastor/src/bin/cli/nexus_cli.rs
If the initialization takes time or never finishes (i.e. a bug in code
or misconfiguration) the atomic variable was never updated and the
receiver in the main thread waited forever. Operation was hung - unable
to complete.
Besides the fix of the hang, the fix improves the situation in a
couple of ways:
* the timeout has been increased from 100ms to ~1s
* exponential backoff prevents crazy many loops for slow systems
* log messages give insight without flooding the screen
> nexus publish hangs if kernel inits nbd dev for too long (CAS-453)

- mayastor-test/test_nexus.js
- mayastor-test/test_replica.js
- mayastor/src/bdev/dev.rs
- mayastor/src/pool.rs
- mayastor/tests/core.rs
- nix/pkgs/libspdk/default.nix
- nix/test/rebuild/node1-mayastor-config.yaml
- nix/test/rebuild/node2-mayastor-config.yaml
- shell.nix
- spdk-sys/build.rs
- spdk-sys/build.sh
Re-enable io_uring support for bdev but not sockets as the latter requires kernel 5.5.
Keep uring bdev tests disabled to avoid a kernel 5.4 bug that is still present in the latest Ubuntu 20.04 kernel.
Resolves: CAS-408, CAS-129
> Re-enable io_uring support

- Jenkinsfile
- doc/jenkins.md
- scripts/release.sh
This commit does a couple of things:
* ci/cd tests are run only for pull requests and develop (see below)
* schedules nightly builds of develop every day at 2am
* nightly job on develop pushes images to dockerhub
* a commit to master/release branch pushes images to dockerhub
* new script for building & pushing imgs usable even w/o jenkins
> Create workflow for pushing mayastor images to dockerhub (CAS-450)

- deploy/README.md
- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- deploy/moac-deployment.yaml
From v0.4.0, deployment files should use the 'latest' tag on Mayastor container image specifications, to avoid the need to update these with each release.  A note to users to that effect, and the need to change the tag as maybe required (e.g. if seeking to run an earlier version) has been added to the README.md file.
> Update deployment YAML files to use 'latest' tag

- mayastor/tests/pool.rs
The mayastor::pools::PoolsIter iterator currently does not behave correctly if you attempt to destroy a collection of pools as you iterate through them.  Modify the "create_pool_legacy" test to prevent triggering this undefined behaviour.
> CAS-458 prevent crash in cargo "create_pool_legacy" test.

- csi/moac/finalizer_helper.ts
- csi/moac/pool_operator.js
- csi/moac/tsconfig.json
- csi/moac/volume.js
- deploy/moac-rbac.yaml
Modify the pool-operator to
1. add a finalizer to the pool CR if the number of
replicas in the pool is > 1
only if the pool CR deletionTimestamp is not set.
2. remove the finalizer from the pool CR when the
number of replicas is 0.
> Protect storage pools that host volumes with a finalizer

- mayastor/src/bdev/nexus/nexus_bdev_snapshot.rs
- mayastor/src/lvs/lvol.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/mod.rs
- mayastor/src/subsys/nvmf/admin_cmd.rs
- mayastor/src/subsys/nvmf/mod.rs
- mayastor/tests/common/bdev_io.rs
- mayastor/tests/io.rs
- mayastor/tests/replica_snapshot.rs
- mayastor/tests/replica_timeout.rs
- spdk-sys/build.rs
- spdk-sys/nvme_helper.c
- spdk-sys/nvme_helper.h
- spdk-sys/wrapper.h
The pool layer rework in e6f7517 introduced lvs and is the preferred
home for new functionality on pools/replicas so move snapshot creation
there.
Sharing a snapshot, which is essentially a replica or lvol, causes
the shared property to be written to the blob's extended attributes,
which fails because a snapshot is read-only. Simply return early and
log a warning instead of an error and failing the RPC call.
Update the Rust integration test to share the snapshot, create a nexus
with the snapshot as its child, and extend the IO tests to verify that
the snapshot behaves as one.
> CAS-410: Allow snapshots to be shared

- csi/moac/pool_operator.js
Updating the status of the pool CR object was
incorrectly moved to after the object is "pushed"
to k8s
> Fix bug introduce in a recent change

- mayastor-test/test_common.js
- mayastor-test/test_csi.js
- mayastor-test/test_nexus.js
- mayastor-test/test_rebuild.js
- mayastor-test/test_snapshot.js
Legacy INI style configuration was been deprecated in SPDK 20.04 and
will be removed in a future release.
Remove use of ini style configuration when starting Mayastor by
converting them to yaml format Mayastor config (test_nexus) or
dropping it altogether (test_rebuild, as it was actually unused).
Change the first argument to common.startMayastor to take a Mayastor
config instead.
Note that test_nexus still has a standalone instance of SPDK that uses an ini file, this will be addressed in CAS-430.
> CAS-331: mayastor-tests: Remove ini file usage

- Jenkinsfile
- doc/jenkins.md
Bonus feature are slack messages sent to mayastor-backend channel
when nightly tests break/recover. Otherwise it would be very easy
to go unnoticed.
> Jenkins should not update status of commit if all stages were skipped (CAS-459)

- mayastor-test/test_common.js
- mayastor-test/test_nexus.js
Change test_nexus to start a 2nd instance of Mayastor to act as an
NVMf target instead of starting the SPDK binary. As this was the only
user, remove common.startSpdk.
This allows the default nvmf target in SPDK to be disabled.
> CAS-430: Use mayastor instead of spdk binary in mocha tests

- mayastor/src/subsys/config/opts.rs
- nix/pkgs/libspdk/default.nix
- nvmeadm/tests/discovery_test.rs
- spdk-sys/build.sh
Delete the archive when building SPDK, removing its default NVMf
target. This revealed the nvmf_discovery test as the last user of that
so refactor it to use the mayastor binary instead.
Fix a few typos in comments in subsys/config/opts.
> spdk: Remove linking to event_nvmf.a

- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_child_error_store.rs
- mayastor/src/bdev/nexus/nexus_child_status_config.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/src/subsys/config/mod.rs
- mayastor/tests/add_child.rs
- mayastor/tests/nexus_rebuild.rs
The nexus child state information is now managed simply by the
ChildState enum. The faulted state makes use of enum variants to
distinguish between the different types of fault conditions.
The use of ChildStatus has been completely removed. This was meant to
map internal Mayastor child state information to states required by the
control plane. This conversion is now performed when the child object is
mapped to its grpc representation.
> CAS-466: Simplify the nexus child state management

- Jenkinsfile
This is a temporary workaround that will be removed when we upgrade
to SPDK 20.10 that does not create these files at all.
> Clean stale iscsi conn files after running mayastor tests (#449)

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/tests/fault_child.rs
If a nexus has a single healthy child, prevent that child from being
faulted (otherwise it would make the nexus unusable).
> Prevent faulting the last healthy child

- deploy/mayastor-daemonset-config.yaml
- deploy/mayastor-daemonset.yaml
- mayastor/src/bdev/nexus/nexus_bdev.rs
Add support for using the child status config file when deploying Mayastor
on K8s. This allows child states to be correctly set when a Mayastor pod
is restarted on the same node.
Bug fix:
- Update child states when a nexus is destroyed to ensure that their
entries in the child status config file are removed.
> CAS-474: Use child status config in Mayastor deployment

- deploy/mayastor-daemonset-config.yaml
- deploy/mayastor-daemonset.yaml
On k8s, even before even attempting to start mayastor we should make
sure that the nats service is ready.
> CAS-481: wait for message bus

- Cargo.lock
- Cargo.toml
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/core/reactor.rs
- mayastor/src/core/thread.rs
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/src/pool.rs
- mayastor/src/replica.rs
- mayastor/tests/common/bdev_io.rs
- mayastor/tests/common/compose.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/mayastor_compose_basic.rs
- mayastor/tests/reset.rs
- nix/pkgs/mayastor/default.nix
- spdk-sys/build.rs
Its been rather complicated to start/stop multiple mayastors within a
single test case. This is true for the BDD tests as well as the unit
tests.
The bookkeeping of the processes itself is a PITA, but things get more
complicated when we want to send signals, pause instances and
the likes. We need to be able to do this simply and easily for more
sophisticated recovery logic.
So using containers seems to be a logical, and instead of using YAML
files to compose targets, I've opted for using the docker remote API
directly. Note, this API  can be used on anything that runs docker
local or remote. However, we use "FROM SCRATCH" and do not make use of
a basic image, and start the artefact located in /target directly.
This docker API rather verbose, and so you will see alot of Some() and
Default …
> test: add framework to start mayastor instances

- mayastor/src/bin/casperf.rs
- mayastor/src/bin/cli/context.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/bin/main.rs
- mayastor/src/core/env.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/src/subsys/mbus/mbus_nats.rs
A lot of the "main" code is done with in the start closure of
mayastor. This PR moves this into main.rs where it should be. The
older .start() method is still present as they are used by tests but
over time we can phase it out.
The need for this - is mostly to avoid spawning runtimes during init
> core: rework main.rs

- mayastor-test/test_snapshot.js
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_snapshot.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/core/mod.rs
- mayastor/src/lvs/lvol.rs
- mayastor/src/subsys/mod.rs
- mayastor/src/subsys/nvmf/admin_cmd.rs
- mayastor/src/subsys/nvmf/mod.rs
- mayastor/tests/replica_snapshot.rs
- spdk-sys/nvme_helper.c
- spdk-sys/nvme_helper.h
Implement create snapshots for local replicas by having a separate codepath for lvol bdevs that creates the snapshot.
> CAS-477: snapshot creation fails on replicas which are not shared

- csi/build.rs
- csi/proto/mayastornodeplugin.proto
- csi/src/freezefs.rs
- csi/src/nodeplugin_grpc.rs
- csi/src/server.rs
- deploy/csi-daemonset.yaml
- mayastor-test/test_common.js
Create service associated with CSI plugin to service
filesystem freeze unfreeze requests.
To properly snapshot an filesystem volume,
the FS must be frozen prior to creating the
lvol snapshot and then be unfrozen.
To do this use the linux utililty fsfreeze which
must be run on the node on which the volume has
been mounted.
MOAC will make remote calls to the service running
on the node to do this.
> Create service associated with CSI plugin. CAS-480

- Jenkinsfile
The NixOS KVM in the lab keeps loosing connectivity and we now have the
docker compose tests which should be used instead.
The existing tests are still kept, we're just not running them on CI.
> Disable Nix tests from CI

- mbus-api/examples/client/main.rs
- mbus-api/src/lib.rs
- mbus-api/src/mbus_nats.rs
- mbus-api/src/send.rs
Message bus requests can go unanswered. In fact, if no receiver was
listening in when the request was sent, it will not get it altogether.
This a default timeout of 5s with a default max number of 5 retries.
To avoid complicating things for the moment, each retry it spaced out by
1s * nr of retries and capped at 10s - further down the line we might
want to customize this a bit.
By using request_ext one can specify timeout and max_retries explicitly.
> CAS-488: message bus timeout and retry

- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/tests/common/compose.rs
- mayastor/tests/nexus_child_location.rs
A nexus child is identified as being local if its bdev driver is neither
nvme nor iscsi. Therefore, nexus children with bdev drivers of type
"lvol", "aio" or "malloc" will be identified as local.
> Add a function to check if a nexus child is local

- doc/build.md
A few links in `doc/build.md` corrected on reading the docs to get a better understanding of the codebase
> doc: update faulty links in build document

- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_metadata.rs
- mayastor/tests/nexus_label.rs
No longer store a BdevHandle in each NexusChild. Instead, generate a new BdevHandle object each time get_dev() is called for the child. Remove the NexusChild::read_at() and write_at() methods from NexusChild and use the BdevHandle methods instead using an explicit BdevHandle.
One NexusChild::write_at() method is retained to keep the code tidy, but this is used only in the nexus_label code and uses a transient BdevHandle internally.
> CAS-491-Remove-stored-handle

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_fn_table.rs
To make the logic for controlling write-only child bdevs more straightforward.
The write-only count in the NexusChannel is removed and now we use a two separate vectors of BdevHandles,
one for read operations and one for write (or other modifying) operations.
Included new check for attempted reads when no readable channels are present.
> CAS-493 Separate Nexus read and write channels.

- deploy/mayastor-daemonset.yaml
- mayastor/src/core/env.rs
- mayastor/src/subsys/config/mod.rs
The sync_config used by mayastor during configuration changes now
saves only pools into the config file.
Loading and "manually" writing of base bdev's and nexus is still
supported as it facilitates testing.
This somewhat improves the current k8s config by allowing replicas to
be revived after a crash/restart.
> CAS-489: limit config sync to pools

- Cargo.lock
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- nix/pkgs/mayastor/default.nix
Ensure only one reconfigure task is active per-nexus at a time.
This is achieved by locking an async mutex at the start of Nexus::reconfigure().
> CAS-492 Serialise reconfigure

- mayastor/src/bdev/dev/nvmf.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/core/bdev.rs
- mayastor/src/core/io_driver.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/thread.rs
- mayastor/src/nexus_uri.rs
- mayastor/tests/common/compose.rs
- mayastor/tests/common/mod.rs
- mayastor/tests/io_job.rs
- mayastor/tests/lvs_pool_rpc.rs
- mayastor/tests/mayastor_compose_basic.rs
- mayastor/tests/nexus_child_location.rs
- mayastor/tests/replica_timeout.rs
- mayastor/tests/reset.rs
- shell.nix
This change adds the ability to create workloads within a given mayastor
instance. This is for testing -- not just during mayastor development but
also for e2e tests where we can invoke job creations form within k8s in
the near future.
An example is given `io_job.rs` where we create 2 nvmf targets through
the compose framework, and then use `struct MayastorTest` to do
some IO to it.
> test: need ability to (easily) drive IO to a nexus

- mayastor/src/core/env.rs
- mayastor/src/core/reactor.rs
- mayastor/src/core/thread.rs
- mayastor/src/lvs/lvol.rs
- mayastor/tests/common/mod.rs
Use NonNull<T> to ensure pointers are not NULL when
dealing with FFI.
> thread: use NonNull<>

- mayastor-test/test_nexus.js
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/bin/initiator.rs
- mayastor/src/core/handle.rs
- mayastor/src/subsys/nvmf/subsystem.rs
This allows a Nexus published on nvmf to benefit from
multipath access from a supporting initiator, such as the one in the
Linux kernel. This requires multiple Nexuses published with the same
UUID which means they have the same NQN.
> CAS-498: Enable ANA reporting

- Cargo.lock
- csi/src/dev/nvmf.rs
- nix/pkgs/mayastor/default.nix
- nvmeadm/Cargo.toml
- nvmeadm/src/error.rs
- nvmeadm/src/lib.rs
- nvmeadm/src/nvme_namespaces.rs
- nvmeadm/src/nvme_uri.rs
- nvmeadm/src/nvmf_discovery.rs
Add parsing of nvmf uri's to the admin library.
@mtzaurus will use this to move the tests that use NBD to NVMe
> nvme: add uri support

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/tests/nexus_rebuild.rs
When destroying a nexus all rebuild jobs should be cancelled before
closing the children. This ensures that the close on the children can
complete properly as any handles held by the rebuild job will no longer
exist.
Previously, destroying the nexus resulted in the rebuild jobs being
stopped. However, this just issued a stop request but did not wait for
the rebuild job to actually stop.
Note: This change attempts to resolve the issues seen on CI where rebuild
test cases have been observed to hang.
> Cancel all rebuild jobs on nexus destruction

- Cargo.lock
- mayastor/Cargo.toml
- mayastor/tests/mount_fs.rs
- nix/pkgs/mayastor/default.nix
- nvmeadm/src/nvme_namespaces.rs
Existing mount tests are refactored to not use Mthreads and to use NVMF protocol for testing nexus connectivity instead of NBD.
> CAS-512 Refactor mount_fs testcases to use NVMe protocol instead of NBD

- mayastor/src/logger.rs
- mayastor/tests/common/mod.rs
This reduces the copious logging from the h2 component.
Parse the internal logging initialisation string the same way as
the RUST_LOG environment variable.
> cargo tests: Limit debug logging to mayastor component

- mayastor-test/e2e/install/deploy/pool.yaml
- mayastor-test/e2e/install/install_test.go
- mayastor-test/e2e/setup/bringup-cluster.sh
- Enable and start iscsi daemeon service in the nodes
- Use ubuntu2004 and load nvme kernel modules
- Add creation of pools as part of the deployment
> e2e vagrant deployment usability fixes

- deploy/mayastor-daemonset.yaml
- mayastor/src/core/env.rs
- mayastor/src/subsys/config/opts.rs
The -l option serves the same purpose as the -m option however it accepts
a list of cores with ranges i.e 1,2,10-15.
Also two default values have been updated while here as the number of
shared buffers was to low to test this change and some notes to the YAML
file has been added.
> env: add -l option to specify cores

- README.md
Using `develop` will result in sometimes showing `aborted` which is sort of misleading.
> Point the build icon to `master`

- mayastor-test/e2e/nightly/README.md
- mayastor-test/e2e/nightly/pvc_stress/pvc_stress_test.go
- mayastor-test/e2e/nightly/test.sh
Do {
Scenario: A Mayastor deployment should respond correctly to new Mayastor PVC declarations
Given: Mayastor is deployed on a Kubernetes cluster
And: A StorageClass resource is defined for the Mayastor CSI plugin provisioner
When: A new, valid PVC resource which references that StorageClass is declared via a k8s client
Then: A corresponding PV should be dynamically provisioned
And: The reported status of the PVC and PV resources should become ‘Bound’
And: A corresponding MayastorVoume CR should be created
And: The reported status of the MayastorVolume should become 'healthy'
Scenario: A Mayastor deployment should respond correctly to the deletion of PVC resources
Given: A Mayastor deployment with PVs which have been dynamically provisioned by the Mayastor CSI plugin
When: An existing …
> Add e2e pvc stress test. CAS-500

- mayastor/tests/common/mod.rs
Previous change set the test logs to mayastor=DEBUG to silence the h2
logs but this completely removes logs from other components including
from the test components.
Add back debug logs from all but limit h2 to info.
If this is still too much we could try info,mayastor=debug,h2=info etc
> Add back logs from test code

- composer/src/lib.rs
- mayastor/tests/io_job.rs
- scripts/cargo-test.sh
I've packed two changes into one PR as they are quite small a loosely related: 
1. pins `io_driver` test target containers to improve likelihood of succeeding as suggested by @gila 
2. traps signals in the wrapper `cargo-test.sh` to allow for clean up. This is related to CAS-524, if we want to make it nice and driven by tests themselves.
~Cleanup is currently a bit brutal as it goes after all containers.~ I've done that as the other alternative would be listing names which is not very future-proof. Also our CI/CD runs on dedicated machines. Possible changes:
- explicitly list names used throughout the tests
- prefix all names in tests with a selector (e.g. `mayadata-`) and filter for it in the loop at handler
- prefix all names in tests with a selector passed as an environment variable to …
> Pin io_driver targets to cores and docker cleanup wrapper for cargo-test

- terraform/README.adoc
- terraform/mod/libvirt/main.tf
We need this field so that we work with terraform v0.13
> terraform: Require the libvirt provider

- mayastor-test/e2e/install/install_test.go
Enumerate and query the nodes in the test cluster to
a) Determine what IP address to use for the test registry
b) If there are nodes labelled for mayastor
c) Configure pools on suitable labelled nodes
> Make the install test more platform agnostic

- csi/moac/test/watcher_test.js
By strange coincidence the timer triggers sooner than it should
which according to nodejs doc should not happen. Extend time interval
by one millisecond to avoid it.
> moac: Fix unreliable time interval tests for watcher

- mayastor/src/bdev/nexus/nexus_nbd.rs
- nvmeadm/tests/discovery_test.rs
Run the set timeout in another thread while we poll as it seems that
when the nbd device is open it triggers a partition scan.
Set the NBD size to 0 before disconnecting as it was observed that when
we disconnect sometimes the device gets rescanned and the kernel thinks
it should partition scan again... setting the size to 0 before the
disconnect seems to alleviate this.
> Try to fix CI nbd issues

- Jenkinsfile
- mayastor/tests/nexus_multipath.rs
New test with 2 identical Nexuses on 2 nodes with the same replica on
one node as their child. This requires creating the nexus with a local
replica on one node first, then sharing the replica over nvmf before
creating the nexus on the other node with the remote replica as its
child.
Use the kernel initiator to connect to both nexuses and check that
both are disconnected when disconnecting by NQN.
On Jenkins, clean up all nvmf connections after cargo tests in case
this test fails to clean up. While I'm here, remove the temporary
workaround to clean up state spdk_iscsi_conns shm files as SPDK 20.10
no longer creates such files.
> CAS-511: Test nexuses with common child

- mayastor/src/logger.rs
Clean up event formatting code, and ensure consistency when multiple (ie. nested) spans are present.
> Clean up log/tracing event formatter

- Jenkinsfile
This helps when debugging problems. In particular it gives us a
name of the node where the tests are running which is useful when
trying to reproduce a failure.
> Print env vars in each test stage of jenkins

- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/core/bdev.rs
A channel is used to allow a nexus child to wait on the removal of the
underlying bdev before completing the close call.
The previous assumption had been that a call to destroy() would only
return when the bdev had actually been removed. However, in some cases,
such as for NVMf bdevs, this was not the case.
When closing a local (loopback) child, the underlying bdev must not be
destroyed. Doing so would result in the lvol and data being deleted.
Instead, the child is only removed, but the underlying bdev remains
untouched.
> CAS-514: Make nexus children wait for bdev removal on close

- mayastor-test/e2e/uninstall/uninstall_test.go
For CI we want to use a single cluster to install and run
builds for different commits.
So the sequence would be
1. Push the images to the test registry
2. Run the install test
3. Run all other tests
4. Run the uninstall test
5. and maybe restart the test registry
This change adds the uninstall test
> Add uninstall test

- mayastor-test/e2e/install/README.md
- mayastor-test/e2e/install/deploy/pool.yaml.template
- mayastor-test/e2e/install/install_test.go
Change the install test to use defined docker registry,
and yaml files for pools.
Note pool status is not checked for success.
Communication of resources to use is via environment variables.
That appears to be the way for go test.
Previous behaviour is supported, see README.md
> Change install test to use external resources CAS-541

- mayastor-test/e2e/common/test.go
- mayastor-test/e2e/common/util.go
- mayastor-test/e2e/nvmf_vol/deploy/fio_nvmf.yaml
- mayastor-test/e2e/nvmf_vol/deploy/pvc_nvmf.yaml
- mayastor-test/e2e/nvmf_vol/nvmf_vol_test.go
- mayastor-test/e2e/setup/bringup-cluster.sh
E2e test which creates a PVC using the mayastor-nvmf storage class, deploys a fio pod, runs fio against the volume, expects it to succeed, and then tears down the pod and the PVC. 
A module common/util.go contains functions available to other later e2e tests.
Not yet run by CI testing. Assumes an existing running cluster with a mayastor deployment.
> E2e nvmf basic

- mayastor-test/e2e/common/io_connect_node.sh
- mayastor-test/e2e/node_disconnect/README.md
- mayastor-test/e2e/node_disconnect/deploy/fio_iscsi.yaml
- mayastor-test/e2e/node_disconnect/deploy/fio_nvmf.yaml
- mayastor-test/e2e/node_disconnect/deploy/moac-deployment-refuge.yaml
- mayastor-test/e2e/node_disconnect/deploy/storage-class-2-repl.yaml
- mayastor-test/e2e/node_disconnect/node_disconnect_iscsi/node_disconnect_iscsi_test.go
- mayastor-test/e2e/node_disconnect/node_disconnect_nvmf/node_disconnect_nvmf_test.go
Currently tests are specific to a vagrant deployment set up according to the READMEs.
It is assumed that a cluster is running with mayastor installed with some label changes applied to k8s-1, and using the default IP addresses used by the vagrant deployment. Reducing these prerequisites is an ongoing process.
Isolation of the replica is achieved by modifying the iptables of the affected node.  
The test takes care not to isolate a node running the nexus, moac or the kubernetes master node.  
A successful fio run is used to indicate a functional volume.
> e2e tests for a disconnected replica in a 2-replica volume

- csi/moac/crds/mayastorvolume.yaml
This was a regression introduced publish nexus changes. Somehow this
part of the change did not make it to develop ...
> Fix mayastorvolume.yaml file with CRD definition.

- Jenkinsfile
- doc/jenkins.md
- mayastor-test/e2e/example-parallel.sh
- mayastor-test/e2e/example-simple.sh
- scripts/release.sh
Modest goal of this commit is to make jenkins aware of the e2e test
cluster without executing any e2e tests for now. A new e2e stage is
added and in that stage we build mayastor debug images, upload them to
private docker registry and run kubectl get nodes to test that
kubeconfig is set correctly.
Command line arguments of release.sh have been reworked in order to
provide greater flexibility for various use cases.
> Connect jenkins to e2e test cluster.

- mayastor-test/e2e/common/util.go
- mayastor-test/e2e/node_disconnect/iscsi_drop/node_disconnect_iscsi_drop_test.go
- mayastor-test/e2e/node_disconnect/iscsi_reject/node_disconnect_iscsi_reject_test.go
- mayastor-test/e2e/node_disconnect/iscsi_reject_idle/node_disconnect_iscsi_reject_idle_test.go
- mayastor-test/e2e/node_disconnect/lib/node_disconnect_lib.go
- mayastor-test/e2e/node_disconnect/nvmf_drop/node_disconnect_nvmf_drop_test.go
- mayastor-test/e2e/node_disconnect/nvmf_reject/node_disconnect_nvmf_reject_test.go
- mayastor-test/e2e/node_disconnect/nvmf_reject_idle/node_disconnect_nvmf_reject_idle_test.go
- mayastor-test/e2e/node_disconnect/setup/node_disconnect_setup_test.go
- mayastor-test/e2e/node_disconnect/teardown/node_disconnect_teardown_test.go
- mayastor-test/e2e/node_disconnect/test.sh
Ensure node to isolate is one hosting a replica for the volume.
Disable tests by using "test -c" to ensure they are at least compiled.
More detailed test descriptions.
> Add support for disconnection testing on volumes with more than 3 mayastor nodes.

- chart/templates/mayastor-daemonset.yaml
- deploy/mayastor-daemonset.yaml
Mayastor requires access to the udev database that resides in /run/udev
in order for the ListBlockDevices() gRPC request to function correctly.
This access must be provided via an explicit volume mount when Mayastor
is run from within a container. Without such access, the gRPC call
returns partial and (highly misleading) incorrect information.
@cjones1024 carried out the investigation and made the original changes.
I have moved the changes in his PR from their original place in
deploy/mayastor-daemonset.yaml to
chart/templates/mayastor-daemonset.yaml as this is now used to construct
the YAML file in the deploy directory.
For the purposes of review see https://github.com/openebs/Mayastor/pull/576 for the original PR.
> Cas-561: Provide access to udev databse for mayastor container via additional volume mount.

- Jenkinsfile
- mayastor-test/e2e/install/README.md
- mayastor-test/e2e/install/install_test.go
- scripts/e2e-test.sh
- shell.nix
It is just a starting point. There are many things to improve.
For example:
* reworking test directory structure,
* dynamic spawn of k8s cluster,
* making it possible to run multiple e2e tests in parallel,
* eliminate pool template file in install test
* generate deployment yaml files to a different dir than deploy/
* adding more e2e tests
> Integrate install & uninstall e2e tests to jenkins

- mayastor/src/bdev/nexus/nexus_fn_table.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/src/target/iscsi.rs
- nix/pkgs/libspdk/default.nix
This includes spdk/spdk@6d9d3f87 to fix #555.
Sync with upstream changes to nvme_bdev_opts (kato configuration),
spdk_bdev_fn_table and iscsi_portal_grp_open.
Remove a few members from TcpTransportOpts that are unused and should
have been removed in the 20.10 rebase.
> mayastor: Build against SPDK 21.01-pre

- mayastor-test/e2e/node_disconnect/README.md
- mayastor-test/e2e/node_disconnect/lib/node_disconnect_lib.go
- mayastor-test/e2e/node_disconnect/nvmf_reject_reassign/nvmf_reject_reassign_test.go
- mayastor-test/e2e/node_disconnect/test.sh
This test causes a replica node to be faulted by IO packet rejection, and then waits for the control plane
to provision a new replica. The test requires 4 mayastor nodes.
> Add replica re-assignment e2e test. 

- csi/moac/nexus.ts
When adding a replica to a nexus, ensure that the nexus state in the MSV
is set to degraded.
> CAS-582: Set nexus state to degraded when adding replica

- .gitignore
- scripts/generate-deploy-yamls.sh
- test/e2e/install/install_test.go
Deployment yaml files are now generated to `./test-yamls` which is `.gitignore`-d to avoid polluting developer's git.
> Do not overwrite versioned files in e2e tests CAS-595

- Jenkinsfile
- doc/jenkins.md
- scripts/reclaim-space.sh
Jenkins worker was running out of space because docker images were not
pruned. I decided to put all space reclaiming into a single script that
is run before each e2e stage. So nix GC is no longer run as a service
on worker nodes. The advantage is that we can synchronize GC with running
jobs that way.
> jenkins worker is running out of space

- mayastor/src/subsys/config/mod.rs
- mayastor/src/subsys/config/opts.rs
This changes allows configuring zero copy along with any other socket
options available.
> CAS-597: zero-copy should be configurable

- test/e2e/common/util.go
- test/e2e/rebuild/README.md
- test/e2e/rebuild/basic_rebuild_test.go
- test/e2e/rebuild/fio.yaml
This test checks that a rebuild can be started and completes correctly.
Some helper functions have been added to the common directory and could
be used to refactor some of the existing code in the future.
I have purposely not added the test to the Jenkinsfile yet, as I want to wait for
the discussion on the E2E cleanup procedure to conclude. I will raise a separate
work item for this.
> test: add basic rebuild E2E test (CAS-285)

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/tests/replica_timeout.rs
The assertion occurs due to the nvmf subsystem transitioning from a
paused to an inactive state, which is forbidden. Always resume the
nexus in child_retire so that it is usually in the active state, which
avoids the assertion when unpublishing it.
Fixes #549, CAS-549, CAS-606.
> fix(nexus): assertion failure when unpublishing a faulted nexus

- mayastor/src/subsys/config/mod.rs
- mayastor/src/subsys/config/opts.rs
Setting environment variables is common pattern within the container
ecosystem. This change allows for manipulating most commonly tuned variables
by setting environment KEY=value.
When a YAML file is used, the configuration in the YAML file wins.
> CAS-598: Want ENV support for config options

- scripts/e2e-test.sh
- scripts/e2e_check_pod_restarts.sh
Add script which checks for mayastor pod restarts,
invoke it after every test run
> ci: check for mayastor pod restarts when running e2e-tests CAS-612

- scripts/grpc-test.sh
- scripts/moac-test.sh
Speed up installing npm packages by utilizing all available cores on a machine. I opted to put it to script rather than jenkins so development on local machine can do that too (nixos, rust, go compilation does it by default anyway, so it should produce no surprises).
If I missed some npm install please comment.
> perf(tests): set npm jobs to cpu count

- mayastor/src/core/mod.rs
- mayastor/src/core/poller.rs
- mayastor/tests/poller.rs
This change adds a safe abstraction around the poller interface. We
did not use pollers much (if not at all) but now that we need to
construct, among others our own qpairs we need to create them often
and frequently.
A small trampoline function (which is always inlined) is used to avoid
passing around raw pointers. The poller will execute a closure and allows
us to capture variables so there is no need for boxing arguments.
> feat(poller): want poller abstraction

- csi/moac/volume.ts
- scripts/e2e-test.sh
- test/e2e/replica/README.md
- test/e2e/replica/replica_test.go
Adding a replica to an unpublished nexus was causing the child to be
added as online rather than degraded when the volume was subsequently
published. Because of this a rebuild was not run and data corruption
could occur when reading from the newly added child.
This change delays the addition of a replica until a volume is
published; ensuring the child is added as degraded and rebuilt
accordingly.
Also added a new "replica_test" E2E test.
> fix(replica): delay adding replica (CAS-585)

- csi/moac/node-packages.nix
- csi/moac/package-lock.json
- csi/moac/package.json
- nix/pkgs/images/default.nix
- test/grpc/package-lock.json
- test/grpc/package.json
0.1.6 has a cached prebuilt binary on github so it is downloaded if
available instead of having to build grpc library each time the module
is installed.
Unfortunately, with nix that does not work. More over mayastor tests
still depend on official node-grpc package so the benefit of this change
is not as anticipated. That said the following cases were improved:
1. when running moac unit tests, npm install will be much faster
2. when running grpc api tests, we have to build grpc just once (the
official one) instead of twice as before.
> feat(js): use new version of grpc-uds with cached binary

- doc/jenkins.md
We use only keys for ssh auth. Disable password authentication
altogether to avoid future mishaps.
> docs(jenkins): disable password auth

- .github/workflows/pr-commitlint.yml
- .gitignore
- .pre-commit-config.yaml
@commitlint/config-conventional is not installed by npx so we need to
install it before running @commitlint/cli.
since we're doing this, install @commitlint/cli which speeds up npx as
it no longer needs to pull it.
> fix(linter): fix linter git hook

- mayastor/src/bdev/dev/nvmf.rs
- test/grpc/test_nexus.js
Check bdev_count returned in the nvme_create callback and return early
if no bdev was created, deleting the partially created nvme bdev
first, to avoid dereferencing a null context.names.
Fixes CAS-526.
> fix(nexus): segfault connecting to 0 ns nvmf tgt

- csi/moac/event_stream.js
- csi/moac/index.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/index.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
- mayastor/src/subsys/mbus/registration.rs
- services/node/src/server.rs
Give storage nodes a chance to register with control plane before
we start to import volumes from crds. Otherwise moac tries to fix
volumes that are ok, but it does not know about it.
> fix(moac): import vols after nodes are registered

- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/bdev/dev/nvmx/utils.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/tests/block_device_nvmf.rs
This change adds the last remaining functionality for NVMe I/O handles
to be feature-compatible with existing generic bdev handles:
- unmap()
- write_zeroes()
In addition, a small refactoring in I/O channels to use poller::Poller
instead of native poller-related SPDK API.
Implements CAS-614
> feat(nvmx): set of new features for device handles

- mayastor/src/bdev/nexus/nexus_io.rs
When calling child_retire() and bdev_destroy returns
an error, log the error instead of panicking. The bdev
may be missing due to a simultaneous bdev removal via
the control plane. A further change will introduce
better synchronization to avoid this condition.
> fix: avoid panic with missing bdev

- mayastor/tests/rebuild.rs
Disable the rebuild_dst_disconnect test. This test is occasionally
failing on CI/CD even with a suitably high timeout time. When this
occurs an error message is output indicating that we failed to get IO
channel because we were probably low on memory.
A ticket will be raised to investigate this fully and re-enable the
test.
> test(rebuild): disable test

- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
We still keep the rule that one replica is always local to the
nexus, but when deciding which replica is chosen as local we try
to choose the node with smallest number of nexuses.
> fix(moac): distribute nexuses more evenly

- .github/workflows/pr-commitlint.yml
- commitlint.config.js
Sanitize PR title and body when doing the lint pull request stage.
Also explicitly set type-enum values so we add "example" to the list.
> fix(lint): sanitize PR messages

- chart/templates/csi-daemonset.yaml
- deploy/csi-daemonset.yaml
- nvmeadm/src/nvmf_discovery.rs
- nvmeadm/tests/discovery_test.rs
The uninstall keeps failing due to an invalid prestop hook in the 
csi-driver-registrar.
See:
https://github.com/kubernetes-csi/node-driver-registrar/pull/61/files
Also fix unwrap in nvmeadm library which caused the csi to crash
> fix(csi): tackle e2e uninstall test failure

- mayastor/.cargo/config
- mayastor/.cargo/runner.sh
This reduces our usage of `sudo` in Mayastor tests.
Currently, they run as root with full privileges
(via a cargo alias), this isn't awesome.
This PR still uses `sudo`, but only uses `sudo`
long enough to gain the required capabilities
(which @gila told me, thank you). I think the
ambient capabilities are optional, but I suspect
the way it plays into inherited binaries will be
relevant to our use case.
I haven't used `capsh` much, so I'd appreciate
any pointers! :blush: 
From `mayastor/`, as a normal user:
```bash
nix-shell ../shell.nix
> cargo test
```
From `mayastor/`, as root:
```bash
sudo nix-shell ../shell.nix
> cargo test
```
> chore: more fine grained mayastor test permissions

- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/device.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/bdev/dev/nvmx/uri.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mempool.rs
- mayastor/src/core/mod.rs
- mayastor/tests/block_device_nvmf.rs
- spdk-sys/build.rs
- spdk-sys/nvme_helper.h
This fix introduces shutdown logic for NVMe controllers, which kicks in
upon device removal and properly cleans up controller I/O resources.
I/O device now uses a wrapper around SPDK I/O device handle, which
allows better I/O channel iteration and hides low-level SPDK functions
inside iterator.
Implements CAS-627
> feat(nvmx): controller shutdown/removal

- commitlint.config.js
Previously we overrode the defaults set by
`@commitlint/config-conventional`. Now we do not.
We flagged this during a discussion on Slack about
#644 as we noted the fix still left #642 invalid
due to line length issues.
I'm not sure why we overrode this, this might cause
breakage in scripts which depend on the presumed
line length.
> chore: permit default conventional commit lengths

- csi/moac/test/volumes_test.js
The problem was that after we add a new replica to the volume it
does not immediately transition to degraded state (the new replica
usually starts in degraded state because it is not synced) but the
volume state change happens shortly after it. So the test code was
wrong that immediately after adding a child to nexus the state should
be degraded. It has to wait for it.
> ci(moac): scale up/down test fails sometimes

- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
- csi/moac/volumes.ts
fix(moac): sync replicas more often
One of the previous fixes for moac introduced a significant change to
lifecycle of the volumes and that was that a nexus for a volume was
created only if the volume was used (published in k8s speak). That
creates a number of occasions when we don't attempt to synchronize
data on replicas although we should. To solve that we create a nexus
each time we think that data need to be synchronized. We don't publish
it so that no one can access the volume. The new cases are:
* when volume is created: nexus writes labels to replicas and goes
away again.
* when volume is imported: nexus checks replicas and sets their
status (not implemented in data plane yet).
* when replicas are scaled up: new replica gets added to the new
nexus and when the synchronization is …
> fix(moac): sync replicas more often

- scripts/e2e-cluster-dump.sh
- scripts/e2e-test.sh
- test/e2e/common/util.go
- test/e2e/install/install_test.go
- test/e2e/uninstall/uninstall_test.go
- Change the check for MOAC deployment readyness,
use the condition status
emit more diagnostics messages during the check.
- Delete pools prior to uninstall
- Make --logs option more useful in the e2e-tests script
> ci: refine ci install+uninstall tests

- csi/moac/.gitignore
- csi/moac/csi.ts
- csi/moac/nexus.ts
- csi/moac/package.json
- csi/moac/pool.ts
- csi/moac/replica.ts
- csi/moac/test/csi_test.js
- csi/moac/test/mayastor_mock.js
- csi/moac/test/nexus_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/tsconfig.json
- csi/moac/volume.ts
NBD does not work well with new nexus feature when nexus is created
only if it is used (mounted). For NBD we need to know which node the
nexus is located and the location must not change throughout the
lifetime of the volume. Apparently that does not work now when nexus
is created on whatever node is available and the location can change
between mounts of the volume.
And as part of that convert csi.js to typescript.
Resolves: CAS-672
> refactor(moac): drop support for NBD in CSI

- rest/tests/v0_test.rs
Remove inadvertently checked in debug flag
Remove the commented out debug code as we now have the deployer tool
to create control plane clusters.
> fix(ci): remove debug flag

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/core/bdev.rs
- mayastor/src/core/env.rs
- mayastor/src/grpc/nexus_grpc.rs
- test/grpc/test_nexus.js
Add a destroying flag to NexusChild and only set it in destroy() so
a nexus child destroyed via the normal close() path actually removes
the bdev.
This allows a remove via e.g. an NVMe async event notification to only
mark the child as faulted, which does remove it from the I/O path, and
allows a subsequent normal destroy of a child to remove the bdev.
Previously it would have set NexusChild::bdev to None without
destroying the bdev, which leaks it.
This requires that the shutdown process destroys nexuses first so that
it then destroys each child and its bdev, in that order, as the remove
event from SPDK as part of shutdown would not destroy the bdev, which
would result in the process hanging.
Fixes CAS-624
> fix(nexus): allow re-adding child removed by AEN

- test/e2e/uninstall/uninstall_test.go
Bug in the handling of CAS-651 failure in the
uninstall test.
If lingering pods are found nuke them,
otherwise the test execution hangs on
deleting the namespace.
> ci: fix uninstall to work around lingering pod

- doc/build.md
- nix/pkgs/images/default.nix
- nix/pkgs/mayastor/default.nix
- scripts/release.sh
- terraform/README.adoc
Provide the ability to build container images for the control plane
services and operators.
To build the node service, for example:
nix-build -A images.node-service
or to build a debug version, add the suffix "-dev":
nix-build -A images.node-service-dev
To build the node operator, for example:
nix-build -A images.node-operator
or to build a debug version, add the suffix "-dev":
nix-build -A images.node-operator-dev
Additional change:
Changed the existing image names to remove the "-image" suffix. So the
command to build the mayastor image now looks like:
nix-build -A images.mayastor
rather than:
nix-build -A images.mayastor-image
> feat(control plane): allow images to be built

- Cargo.lock
- Cargo.toml
- mayastor-macros/actix/src/lib.rs
- mbus-api/src/lib.rs
- mbus-api/src/message_bus/v0.rs
- mbus-api/src/v0.rs
- nix/pkgs/mayastor/default.nix
- rest/Cargo.toml
- rest/service/src/main.rs
- rest/service/src/v0/children.rs
- rest/service/src/v0/mod.rs
- rest/service/src/v0/nexuses.rs
- rest/service/src/v0/nodes.rs
- rest/service/src/v0/pools.rs
- rest/service/src/v0/replicas.rs
- rest/service/src/v0/swagger_ui.rs
- rest/service/src/v0/volumes.rs
- rest/src/versions/v0.rs
- rest/tests/v0_test.rs
- services/deployer/src/infra/rest.rs
refactor(rest): improve rest versions
Part of the motivation for this is that we should not mix api versions
on the same openapi spec.
This change makes adding api versions easier by wrapping each version
module with its own openapi wrapper which then generates and exposes
versioned api specs and versioned swagger-ui's.
While we're here, make use of the openapi base path to clean up the
openapi paths and allow for easier to read auto generated code.
Also clean up some redundant type definitions.
refactor(rest): add cmdline certificate arg
Adds cmdline arguments to use https certificates.
Adds argument to use dummy certificates (used by test).
> refactor(rest): improve rest versioning and add certificate arguments

- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/controller_inner.rs
- mayastor/src/bdev/dev/nvmx/controller_state.rs
- mayastor/src/bdev/dev/nvmx/device.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/bdev/dev/nvmx/mod.rs
- mayastor/src/bdev/dev/nvmx/uri.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/tests/block_device_nvmf.rs
- mayastor/tests/nvme_device_timeout.rs
This fix introduces tuneable actions for I/O timeouts for NVMe
controllers (Abort, Reset and Ignore), which are now configurable
in place for running controllers and allow setting different timeout
actions for different controllers.
State transitions for NVMe controllers are now handled by a dedicated
state machine entity, which is now part of the global state of every
controller. Such an approach provides better state encapsulation and
validation and is less error prone than direct state manipulations.
Implements CAS-659
> feat(nvmx): i/o timeouts for nvme controller

- mbus-api/src/message_bus/v0.rs
- mbus-api/src/send.rs
- mbus-api/src/v0.rs
- rest/service/src/v0/jsongrpc.rs
- rest/service/src/v0/mod.rs
- rest/src/lib.rs
- services/Cargo.toml
- services/common/src/wrapper/v0/mod.rs
- services/jsongrpc/src/server.rs
- services/jsongrpc/src/service.rs
Mayastor already exposes SPDK JSON RPC methods through its gRPC
interface. This gRPC interface is further exposed up through the REST
API. Now generic JSON gRPC methods can be invoked using a REST call.
> feat(rest): expose json rpc methods

- scripts/e2e-test.sh
- test/e2e/common/util.go
- test/e2e/resource_check/resource_check_test.go
- test/e2e/uninstall/uninstall_test.go
The CSI test suite is a 3rd party test suite.
We would like to apply stringent resource leakage checks for
each test.
We have test code which does this, it makes sense to reuse this.
However it is not straightforward to integrate this with the
3rd party source code.
Doing so makes it more difficult to integrate future changes in
the 3rd party source code.
Create a simple resource check test which is sequenced to run after
each 3rd party test suite.
Rename CheckNo* functions to the more apt CheckFor*
> ci: add post 3rd party test resource check CAS-691

- Jenkinsfile
When e2e test run fails, k8s cluster built for the test is left running
to allow investigation. This adds sending notification to team's slack
about that cluster.
> ci(e2e): notify slack of k8s cluster left running

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/core/env.rs
Set all children to Destroying state instead to address possible
segfault on shutdown when destroying nexuses.
Fixes CAS-697
> fix(nexus): set children to destroying state on shutdown

- control-plane/agents/jsongrpc/src/server.rs
- control-plane/deployer/src/infra/mod.rs
The deployer tool now has the ability to run the JsonGrpc service. To do
so, issue the following command:
../deployer start -s JsonGrpc
The JsonGrpc agent isn't added to the list of default services to run
because in most cases it won't be necessary (it provides a way to invoke
SPDK JSON gRPC methods).
> feat(deployer): ability to deploy JsonGrpc service

- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
This fix introduces better API abstractions for such SPDK objects as
i/o qpair and poll group. All low-level SPDK handles are hidden
inside high-level Rust wrappers, which incapsulates low-level SPDK
library functions.
As a plus, high-level wrappers allow using Options instead of raw
pointers, which makes code look a lot better.
Implements CAS-628
> refactor(nvmx): more abstractions for spdk objects

- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- deploy/moac-deployment.yaml
Set mayastor image tags back to 'develop', after merging back
from master branch following GitFlow release of v0.7.1
> chore(release): Revert k8s deployment config files

- doc/build.md
The links to the phrase `nix build` in build docs are broken. This PR fixes those links.
Signed-off-by: shubham <shubham14bajpai@gmail.com>
> fix: correct dead links in build docs

- Cargo.lock
- Cargo.toml
- composer/src/lib.rs
- control-plane/agents/common/src/wrapper/v0/mod.rs
- control-plane/agents/jsongrpc/src/service.rs
- control-plane/deployer/Cargo.toml
- control-plane/deployer/bin/src/deployer.rs
- control-plane/deployer/src/infra/mayastor.rs
- control-plane/deployer/src/infra/mod.rs
- control-plane/deployer/src/lib.rs
- control-plane/mbus-api/Cargo.toml
- control-plane/mbus-api/src/mbus_nats.rs
- control-plane/mbus-api/src/message_bus/v0.rs
- control-plane/mbus-api/src/v0.rs
- control-plane/rest/service/src/v0/jsongrpc.rs
- control-plane/rest/service/src/v0/mod.rs
- control-plane/rest/src/lib.rs
- control-plane/tests/Cargo.toml
- control-plane/tests/tests/common/mod.rs
- control-plane/tests/tests/nexus.rs
- control-plane/tests/tests/pools.rs
- control-plane/tests/tests/replicas.rs
- mayastor/src/core/share.rs
- mayastor/src/grpc/pool_grpc.rs
- mayastor/src/lvs/error.rs
- nix/pkgs/control-plane/cargo-project.nix
- nix/pkgs/mayastor/default.nix
- scripts/ctrlp-cargo-test.sh
This is the initial bits of a new test project which leverages the new
control plane to test mayastor.
It has already revealed a few issues.
Make replica share protocol conversion from gRPC fallible as it was
causing mayastor to crash on the REST tests.
Split the deployer into a library and a binary allowing for the library
to be used by the coming rest test project.
Allow for a JSON Value to traverse the stack allowing swagger to
display it as JSON and with colours.
Also make sure the rest client returns the correct errors.
> feat(rest-test): new rest test project 

- Cargo.lock
- mayastor/Cargo.toml
- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/device.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/tests/block_device_nvmf.rs
This fix introduces I/O statistics for read, write and unmap
operations for NVMe block devices.
Implements CAS-722
> fix(nvmx): controller i/o statistics

- control-plane/agents/common/src/wrapper/v0/mod.rs
- control-plane/agents/common/src/wrapper/v0/msg_translation.rs
- control-plane/agents/common/src/wrapper/v0/pool.rs
- control-plane/agents/common/src/wrapper/v0/volume.rs
- control-plane/agents/node/src/server.rs
- control-plane/mbus-api/src/message_bus/v0.rs
- control-plane/mbus-api/src/v0.rs
- control-plane/rest/service/src/v0/block_devices.rs
- control-plane/rest/service/src/v0/mod.rs
- control-plane/rest/src/versions/v0.rs
Implement a REST call for listing block devices. The REST call uri can
optionally include the 'all' query parameter. This determines whether
all devices should be listed or just those that are deemed usable.
Omitting the query parameter results in all devices being listed.
Also added traits for converting messages between rpc and message bus
formats as this will be a common occurrence for control plane agents.
Resolves CAS-689
> feat(rest): expose list_block_devices method

- chart/templates/moac-deployment.yaml
- csi/moac/csi.ts
- deploy/moac-deployment.yaml
- test/e2e/uninstall/uninstall_test.go
Update for bug fixes
csi-provisioner 1.6.0 -> 2.1.0
csi-attacher 2.2.0 -> 3.1.0
E2E:
Re-enable the checks for mayastor pods on uninstall
Turn off the topology feature gate,
this will be addressed in the future.
> fix: update CSI sidecars used with mayastor CAS-651

- control-plane/rest/src/lib.rs
- control-plane/rest/src/versions/v0.rs
- control-plane/rest/tests/v0_test.rs
Add rest client support and test cases for calling JSON gRPC methods and
listing block devices.
Resolves: CAS-732
> feat(rest client): add support for new rest calls

- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/tests/nexus_label.rs
- mayastor/tests/nexus_rebuild.rs
- dispensed with NexusChildLabel struct entirely
(which maintained a child reference and seemed to be causing deadlocks)
- added extra sanity checking for valid labels
- create labels correctly for disks of varying size
- allow changing of disk GUID if creating nexus with different UUID
Resolves CAS-720
> refactor(nexus): clean up label parsing code

- Jenkinsfile
Because of new beefier worker nodes for Jenkins we can run e2e tests in parallel
with other jobs thus keeping more CI capacity for other jobs
> ci(e2e): run e2e on shared worker

- chart/templates/_helpers.tpl
- chart/templates/mayastor-daemonset.yaml
- chart/templates/moac-deployment.yaml
- chart/values.yaml
- deploy/mayastor-daemonset.yaml
- deploy/moac-deployment.yaml
- scripts/generate-deploy-yamls.sh
- test/e2e/install/install_test.go
The purpose of profiles is to provide reasonable defaults for yaml
templates for each of the major use cases:
* develop: used by developers to run mayastor
* release: used for stable releases of mayastor
* test: used by mayastor e2e tests
In addition to that I have:
* increased debug level of moac when running in develop env
* fixed wrong usage of -l parameter (indexing starts at 0)
* introduced rule of thumb for cpu count and hugepage mem (1:1)
Resolves: CAS-699
> chore: do profile-based yaml generation

- Jenkinsfile
- scripts/e2e-test.sh
- test/e2e/install/install_test.go
Add parameter to build to indicate a continuous test.
Continuous tests need only run E2E tests and test a specific labelled
image from dockerhub.
A successful completed run will trigger another run if
the parameter e2e_continuous is set to true and if the global
config option E2E_CONTINUOUS_ENABLE is set to "true".
A failure will send a Slack message to alert developers.
Continuous tests have their own Xray test plan target.
> test(e2e): run back-to-back CI runs

- mayastor/src/bin/mayastor-client/nexus_cli.rs
Allow users to pass multiple children to the `mayastor-client nexus create` command.
> fix: mayastor-client nexus create accept many children

- Cargo.lock
- mayastor/Cargo.toml
- mayastor/src/bin/mayastor-client/context.rs
- mayastor/src/bin/mayastor-client/main.rs
- nix/pkgs/mayastor/default.nix
- test/grpc/test_cli.js
Unifies the `-a` and `-p` flags to a `-h` flag which
takes a full url (optionally) without a scheme.
Further, this makes the flag global, so it can be used
in any position:
```bash
RUST_BACKTRACE=1
RUST_LOG=mayastor=trace
cargo run -- nexus list
cargo run -- --bind 127.0.0.1 nexus list
cargo run -- -b 127.0.0.1:10124 nexus list
cargo run -- --bind http://127.0.0.1:10124 nexus list
cargo run -- --bind http://127.0.0.1 nexus list
cargo run -- nexus list --bind 127.0.0.1
cargo run -- nexus list --bind 127.0.0.1:10124
cargo run -- nexus list -b http://127.0.0.1:10124
cargo run -- nexus list --bind http://127.0.0.1
```
Closes #707.
> feat: unify mayastor-client address/port flags

- test/e2e/common/test.go
- test/e2e/install/install_test.go
Disable metrics consumption in the agent when running e2e tests
to avoid a conflict in use of port 8080 if multiple
agents run on the same machine.
> test(e2e): avoid conflicts in metrics port usage

- mayastor/src/bdev/dev.rs
- mayastor/src/bdev/dev/aio.rs
- mayastor/src/bdev/dev/iscsi.rs
- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/dev/malloc.rs
- mayastor/src/bdev/dev/null.rs
- mayastor/src/bdev/dev/nvmf.rs
- mayastor/src/bdev/dev/uring.rs
- mayastor/src/bdev/util/uri.rs
Resolves https://mayadata.atlassian.net/browse/CAS-713 .
mayastor-client bdev create (or list) seem to no respect the configured block size, see `blk_size`:
```bash
$ mayastor-client bdev create 'malloc:///disk1?bs=4096&size_mb=10'
{
"name": "disk1"
}
$ mayastor-client bdev list
{
"bdevs": [
{
"name": "disk1",
"uuid": "9043165c-7633-4295-abce-a2dde42b7445",
"num_blocks": 20480,
"blk_size": 512,
"claimed": false,
"claimed_by": "Orphaned",
"aliases": "malloc:///disk1?bs=4096&size_mb=10",
"uri": "malloc:///disk1?bs=4096&size_mb=10&uuid=9043165c-7633-4295-abce-a2dde42b7445",
"product_name": "Malloc disk",
"share_uri": "bdev:///disk1"
}
]
}
```
Users should be guided on the correct parameters if invalid ones are passed.
Such as:
```bash
$ mayastor-client bdev create …
```
> feat: make bdev create parameters strict

- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/util.go
- test/e2e/common/util_cleanup.go
- test/e2e/common/util_node.go
- test/e2e/common/util_pvc.go
- test/e2e/common/util_testpods.go
- test/e2e/io_soak/README.md
- test/e2e/io_soak/filesystem_fio.go
- test/e2e/io_soak/fio.go
- test/e2e/io_soak/io_soak_test.go
- test/e2e/io_soak/rawblock_fio.go
- test/e2e/node_disconnect/lib/node_disconnect_lib.go
- test/e2e/node_disconnect/replica_pod_remove/replica_pod_remove_test.go
- test/e2e/pvc_stress_fio/pvc_stress_fio_test.go
- test/e2e/uninstall/uninstall_test.go
Deviations from MQ-25 test configuration
- replication factor is set to 1 for now
- application pods MAY be located on the same nodes as Mayastor
- this requires a larger test cluster and more thought
Also included is bunch of changes to ensure clusters are
rendered usable, this to faciliate ease of test development.
Re-creating clusters is time consuming in code-debug-test iteration cycle.
> ci: i/o soak test - NVMe over TCP. MQ-25

- Jenkinsfile
Skipped steps should not allocate Jenkins agents.
> test(e2e): avoid allocating agents if not needed

- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/bdev/dev/nvmx/utils.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/nvme.rs
- mayastor/tests/block_device_nvmf.rs
- mayastor/tests/nvme_device_timeout.rs
This fix introduces a new generic enum for indicating completion status
for I/O operations, instead of a single boolean flag.
This allows better per-domain separation of I/O errors (NVMe, SCSI,
etc).
Implements CAS-736
> feat(nvmx): extended nvmx i/o completion status

- mayastor/src/bin/mayastor-client/bdev_cli.rs
Resolves https://mayadata.atlassian.net/browse/CAS-718
The protocol argument of `mayastor-client bdev share` is safer and easier to document as an option
`-p nvmf` style:
```
$ ./artifacts/pkgs/mayastor/bin/mayastor-client bdev share --help
mayastor-client-bdev-share 
share the given bdev
USAGE:
mayastor-client bdev share <name> -p <protocol>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-p <protocol>        the protocol to used to share the given bdev [default: nvmf]  [possible
values: nvmf, iscsi]
ARGS:
<name>    
```
> feat: make bdev share protocol argument as an option

- control-plane/tests/tests/nexus.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/tests/child_size.rs
When creating a new nexus, as a final step, the newly created
nexus is added to a global list of nexus instances.
This list is required when handling bdev removal - specifically
it is used by lookup_child_from_bdev() to determine the nexus child
that is associated with a given bdev.
The problem occurs when there is an error creating a nexus,
and proper cleanup necessitates the removal of some children that may
have already been successfully created. The removal code requires the
owning nexus to be present in the global list in order to successfully
remove the children, but the nexus has not yet been added to the list,
as it has not been successfully created.
The solution is to add the (partially created) nexus to the list of global
instances as early as possible in the creation process. …
> fix(nexus): mayastor hangs when creating a nexus if there is an error creating a child

- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/core/block_device.rs
- mayastor/tests/block_device_nvmf.rs
- mayastor/tests/nvme_device_timeout.rs
I/O callbacks now receive references to the device that performs I/O,
which simplifies device identification during I/O completion assessment.
Implements CAS-741
> feat(nvmx): pass device reference to i/o callbacks

- composer/src/lib.rs
Running a cargo test that uses composer results in these entries in
the system log:
dockerd[pid]: time="<time>" level=warning msg="Security options with
`:` as a separator are deprecated and will be completely unsupported
in 17.04, use `=` instead."
so update the separator to use '='.
> fix(composer): update separator for security options

- Jenkinsfile
- scripts/e2e-test.sh
- test/e2e/common/loki/loki.go
- test/e2e/common/test.go
- test/e2e/go.mod
- test/e2e/io_soak/io_soak_test.go
- test/e2e/loki/promtail_daemonset_e2e.template.yaml
Send log entries directly to Grafana/Loki from golang tests, with the app string "marker"
Change Loki credentials to username + password as this form is needed for the go library.
Build number now passed into e2e-test.sh to propagate the build number to the markers.
Currently called when each ginkgo test starts.
Fix typo in soak test and temporarily disable from overnight (extended) runs.
> test(e2e): add markers to loki log stream

- chart/templates/moac-deployment.yaml
- deploy/moac-deployment.yaml
Bug or Regression:
* External-provisioner may have stopped provisioning for a PVC depending
on certain timing conditions (provisioning failed once, next attempt
currently running, PVC update arrives from API server).
* Fix CSI translation issues with EBS, AzureFile and Cinder drivers
* Producing storage capacity may have failed with the object has been
modified errors
* Fix topology translation during CSI migration for gce-pd, aws-ebs,
cinder drivers
> fix(csi): update CSI external provisioner to 2.1.1

- scripts/e2e-test.sh
- test/e2e/configurations/ci_e2e_config.yaml
- test/e2e/io_soak/io_soak_test.go
Run soak tests, as well as replica and
rebuild tests on overnight builds.
Fixed ginkgo test strings to match Xray test definition
for io_soak test.
Removed iscsi from the config list of soak protocols.  
Reduce load factor in soak tests so they
can be run on Hetzner clusters, until we
have larger nodes available or until the new 
e2e-fio image is in use.
> test(e2e): add io_soak to extended tests

- Jenkinsfile
It is not needed anymore as it is taken from build job run.
MQ-242
> ci(e2e): do not pass ENVIRONMENT param

- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/src/subsys/nvmf/target.rs
- mayastor/tests/nexus_multipath.rs
- test/grpc/test_nexus.js
Leave ANA reporting disabled when publishing a Nexus over NVMf unless
the environment variable NEXUS_NVMF_ANA_ENABLE is defined when
creating a Nexus.
Include a chore to switch away from deprecated spdk_nvmf functions.
Fixes CAS-789, CAS-791.
> feat(nexus): make ANA reporting configurable

- csi/moac/test/watcher_test.js
It's more a workaround for behaviour that normally should not happen.
On the other hand it does not really matter because it affects only
the test suite.
Resolves: CAS-760
> ci(moac): fix timing issues in moac watcher tests

- test/e2e/common/e2e_config/e2e_config.go
- test/e2e/common/util_testpods.go
- test/e2e/configurations/ci_e2e_config.yaml
- test/e2e/e2e-fio/Dockerfile
- test/e2e/e2e-fio/README.md
- test/e2e/e2e-fio/build.sh
- test/e2e/e2e-fio/e2e_fio.c
- test/e2e/io_soak/README.md
- test/e2e/io_soak/definitions.go
- test/e2e/io_soak/disruptor_fio.go
- test/e2e/io_soak/filesystem_fio.go
- test/e2e/io_soak/fio.go
- test/e2e/io_soak/io_soak_test.go
- test/e2e/io_soak/rawblock_fio.go
Create a fio docker image specifically designed for mayastor
e2e testing.
Add CIRegistry entry to e2econfig so that this image and future
test docker images are retrieved from the CI registry, independent
of Mayastor images.
Re-jig io soak tests to use the mayastor/e2e-fio docker image.
This removes the need to run multiple threads to run fio, as
the e2e-fio pod can be deployed to run fio on creation.
Add disruptor fio jobs which deploy pods running the e2e-fio image,
restart policy set to restart always, and configured to raise SIGSEGV
after a configurable delay, whilst running fio.
Update the CI configuration to scale up the number of test pods
and volumes to run as part of the IO soak test.
> ci: add disruptive pods to I/O soak test MQ-252

- csi/moac/node.ts
- csi/moac/test/csi_test.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
- csi/moac/volumes.ts
- csi/moac/watcher.ts
This happened when putting moac under a bit of stress and issuing
create/publish/unpublish/destroy requests in a quick succession.
It revealed a few race conditions. Basically, publish method was
running in "parallel" (interleaved) with FSA code, so the state of
the volume was changing in two places. That has an easy fix of
putting code that changes the state of the volume from publish
method to FSA itself. fsa() guarding method guarantees that we can
have only one _fsa() running at any given time. So that should fix
the race condition. What publish merely does is set a few volume
state variables that tell FSA what to do and kick off FSA that does
the rest. Notification mechanism for letting the publish method know
when the required changes are done is in place but had to be slightly …
> fix(moac): moac assert when publishing a volume

- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/tests/replica_timeout.rs
When a nexus child is faulted, set its state to Destroying to ensure
that its bdev is indeed destroyed when calling bdev_destroy().
Fixes CAS-793
> fix(nexus): destroy child bdev when faulted

- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/util.go
- test/e2e/common/util_mayastor_crds.go
- test/e2e/common/util_pvc.go
- test/e2e/common/util_testpods.go
- test/e2e/configurations/ci_e2e_config.yaml
- test/e2e/io_soak/fio.go
- test/e2e/io_soak/io_soak_test.go
IO soak test:
- monitor health of all MSVs
- monitor online state of all pools
Basic volume IO test:
Add functionality for late binding of volumes,
ie WaitForFirstConsumer
for NVMe-of volumes the test matrix is now
- Filesystem volume with immediate binding
- Filesystem volume with delayed binding
- Raw block volume with immediate binding
- Raw block volume with delayed binding
iSCSI volume testing is unchanged
Make a few global var strings constants
Add function so that VolumeType vars are printed as
human readable strings.
> test(e2e): update IO soak and basic volume IO tests

- Jenkinsfile
- test/e2e/common/util_testpods.go
Ensure fio pods are run with a label to allow 
Grafana Loki  to gather logs from them.
Also extend timeout to 3 hours to allow e2e tests to
complete in time, which currently approach 2 hours.
> test(e2e): add label to fio pods

- test/e2e/basic_volume_io/basic_volume_io_test.go
- test/e2e/common/e2e_config/e2e_config.go
- test/e2e/common/util_pvc.go
- test/e2e/common/util_testpods.go
- test/e2e/configurations/ci_e2e_config.yaml
- test/e2e/io_soak/definitions.go
- test/e2e/io_soak/disruptor_fio.go
- test/e2e/io_soak/filesystem_fio.go
- test/e2e/io_soak/fio.go
- test/e2e/io_soak/io_soak_test.go
- test/e2e/io_soak/rawblock_fio.go
Update the basic volume IO test so that
it uses fio "self-running" pods
it uses 500Mb volumes
volumes size configurable.
minor refactor for io-soak,
- remove the image override, common code
uses mayastor-e2e now
- common up fio argument array code.
> test(e2e): update basic volume IO test MQ-377

- chart/develop/values.yaml
- chart/release/values.yaml
- chart/templates/nats-deployment.yaml
- chart/test/values.yaml
- chart/values.yaml
- deploy/nats-deployment.yaml
- scripts/generate-deploy-yamls.sh
Update the nats deployment yaml to a stateful set using a configmap
for the nats config, a config reloader, etc... based on the natsio
latest example files for kubernetes.
Make the nats deployment type configurable through helm using the
existing develop,release and test profiles.
> chore(nats): configurable nats cluster

- test/e2e/configurations/ci_e2e_config.yaml
There have been a number of failures where fio fails to
start and returns with an exit value of 15.
We think this may be because of pressure on the host
system resources.
So reduce the pressure.
> test(e2e): set loadfactor to 10 for io-soak tests

- Jenkinsfile
Send slack messages to mayastor-e2e channel
instead of mayastor-backend for e2e failures.
> test(e2e): notify mayastor-e2e channel

- scripts/e2e-test.sh
Removed so as not to impede soak testing with false failures.
Will be reintroduced shortly when no longer
re-using the faulted node.
> test(e2e): temporarily disable pod remove test

- mayastor/src/bdev/dev/nvmx/channel.rs
- mayastor/src/bdev/dev/nvmx/controller.rs
- mayastor/src/bdev/dev/nvmx/controller_inner.rs
- mayastor/src/bdev/dev/nvmx/device.rs
- mayastor/src/bdev/dev/nvmx/handle.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nexus/nexus_child_status_config.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_metadata.rs
- mayastor/src/bdev/nexus/nexus_module.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/src/subsys/config/mod.rs
Nexus now treats all its replica devices as abstract block devices,
which allows clear separation, and uses abstract block device I/O
handles for serving child I/O.
In order to prevent start of controller resets in response to I/O errors
(mostly connection failures), maximum number of controller resets
introduced along with reset cool down interval.
Per-channel I/O operation accounting is introduced to have better I/O
observability/statistics.
Implements CAS-781
> feat(nvmx): abstract block devices for nexus children

- chart/templates/nats-deployment.yaml
The NatsConfig route was missing the namespace which meant nats services
would not talk to each other and thus events were lost.
> fix: add missing nats namespace to the helm charts

- mayastor/src/bdev/dev/loopback.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/core/bdev.rs
Nexus now registers a listener for all its children and finalizes
child removal in response to device removal event.
> fix(nvmx): nexus children removed in response to events

- csi/src/dev/nvmf.rs
- nvmeadm/src/error.rs
- nvmeadm/src/nvme_uri.rs
- nvmeadm/src/nvmf_discovery.rs
The behaviour of the controller can be tuned better instead of just
accepting the default values from kernel.
Avoid repeating code for connecting to a target and make the code
more rusty.
This work was originally done to address CAS-499 (Mayastor targets
should set sane io timeouts). As it evolved we decided it's better
to document the behavior and suggest how to avoid it instead of
overriding the defaults. Merging it and improving nvmeadm lib
capabilities does not make any harm.
> feat(nvmeadm): add support for a few controller options

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/src/bin/nvmet.rs
- mayastor/src/core/bdev.rs
- mayastor/src/core/share.rs
- mayastor/src/grpc/bdev_grpc.rs
- mayastor/src/grpc/pool_grpc.rs
- mayastor/src/lvs/lvol.rs
- mayastor/src/lvs/lvs_pool.rs
- mayastor/src/subsys/config/mod.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/tests/aio_unmap.rs
- mayastor/tests/lvs_pool.rs
- mayastor/tests/nexus_add_remove.rs
- mayastor/tests/nexus_children_add_remove.rs
- mayastor/tests/nexus_share.rs
- nix/pkgs/libspdk/default.nix
- spdk-sys/build.rs
- test/grpc/test_nexus.js
Add a nexus_share JSON RPC that allows a nexus bdev to be shared over
nvmf with a specified controller ID range. This allows the same nexus
on different Mayastor instances to use non-overlapping controller ID
ranges thereby allowing the initiator to connect to same nexus over
multiple paths.
Add a mocha test to test_nexus to verify that the specified controller
ID range is used when sharing the nexus over nvmf.
Fixes CAS-779
> feat(nexus): share over nvmf with controller ID range

- doc/mayastor-client.md
- mayastor/src/bin/mayastor-client/bdev_cli.rs
- mayastor/src/bin/mayastor-client/context.rs
- mayastor/src/bin/mayastor-client/device_cli.rs
- mayastor/src/bin/mayastor-client/jsonrpc_cli.rs
- mayastor/src/bin/mayastor-client/main.rs
- mayastor/src/bin/mayastor-client/nexus_child_cli.rs
- mayastor/src/bin/mayastor-client/nexus_cli.rs
- mayastor/src/bin/mayastor-client/perf_cli.rs
- mayastor/src/bin/mayastor-client/pool_cli.rs
- mayastor/src/bin/mayastor-client/rebuild_cli.rs
- mayastor/src/bin/mayastor-client/replica_cli.rs
- mayastor/src/bin/mayastor-client/snapshot_cli.rs
- nix/pkgs/mayastor/cargo-package.nix
- test/grpc/test_cli.js
Support both tables/plaintext and JSON in outputs.
Users can now specify `-o json` or `-o default` to configure their output options.
`-o default` is implied. This mimics the `nvme` tool.
Normalizes the output of commands to be similar to `docker` or `kubectl` style commands,
returning relevant URIs, names, etc.
Resolves https://github.com/openebs/Mayastor/issues/756
> feat: support multiple client output formats

- test/e2e/configurations/ci_e2e_config.yaml
The basic volume test failed because the fio run exceeded the timeout.
Raise timeout from 60s to 90s.
> test(e2e): extend timeout for basic test

- Jenkinsfile
- scripts/e2e-test.sh
- test/e2e/README.md
- test/e2e/common/e2e_config/e2e_config.go
- test/e2e/common/locations/util_locations.go
- test/e2e/configurations/ci_e2e_config.yaml
- test/e2e/install/install_test.go
- test/e2e/uninstall/uninstall_test.go
I preparation for moving the e2e tests to separate repository,
allow e2e tests to run on arbitrary mayastor repo trees.
The e2e tests will use yaml files in the mayastor source
tree to deploy mayastor as defined for the revision of mayastor
that exists in the mayastor source tree
1. Stop using relative paths to locate files in the directory trees,
instead rely on 2 absolute paths
1. mayastor source tree root
2. e2e test tree root
2. Reduce reliance on environment variables (which are transient and not
recorded automatically) in favour of using the configuration entity.
3. Document more clearly where the configuration file is searched for and loaded.
> ci: allow e2e tests to run on arbitrary mayastor source tree MQ-430

- Cargo.lock
- Cargo.toml
- composer/Cargo.toml
- composer/src/lib.rs
- csi/Cargo.toml
- csi/src/dev.rs
- csi/src/server.rs
- jsonrpc/Cargo.toml
- jsonrpc/src/lib.rs
- jsonrpc/src/test.rs
- mayastor/Cargo.toml
- mayastor/src/bin/mayastor-client/context.rs
- mayastor/src/bin/mayastor-client/main.rs
- mayastor/src/bin/mayastor.rs
- mayastor/src/bin/nvmet.rs
- mayastor/src/core/env.rs
- mayastor/src/core/reactor.rs
- mayastor/src/subsys/mbus/registration.rs
- mayastor/src/subsys/nvmf/subsystem.rs
- mayastor/tests/common/compose.rs
- mbus-api/Cargo.toml
- mbus-api/src/mbus_nats.rs
- nix/pkgs/mayastor/cargo-package.nix
- nix/sources.json
- rpc/Cargo.toml
This pulls Tokio (0.2 to 1.2) and Tonic (0.1 to 0.4) up to their latest stable versions
and resolves all their breaking changes.
> feat: update tonic and tokio

- chart/templates/mayastor-daemonset.yaml
- csi/moac/test/volumes_test.js
- csi/moac/volume_operator.ts
- csi/moac/volumes.ts
- deploy/mayastor-daemonset.yaml
Two issues, described in great depth in #772 github ticket, were
encountered by a user while trying to provision mayastor volume on
RKE cluster:
1. Mayastor config file was mounted as a directory instead as a file
2. Unhandled exception in Moac (result of partially created volume)
Both issues are fixed in this commit.
Add 1. There does not seem to be a good reason for mounting config
file instead of just the whole config directory so I have removed
that mount. It's not the first time we see this issue and although it
is probably caused by a bug in k8s/OS it can be easily avoided.
> fix(moac): failed to provision volume on RKE

- deploy/fio.yaml
Update deploy/fio.yaml to use the newly minted
mayadata/fio image on docker hub
> fix: change to use mayadata/fio CAS-599

- shell.nix
Restore the pre-commit hook installation that was inadvertently
removed.
Fixes: 98f8a06b  ("style(lint): lint commit messages")
> fix: restore pre-commit hook

- csi/moac/nexus.ts
- csi/moac/replica.ts
- csi/moac/test/nexus_test.js
- csi/moac/test/node_test.js
- csi/moac/test/replica_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
This introduces a new volume state "offline" that is used for
volumes that are inaccessible (the node with the nexus is down).
It is important distinction from "faulted" state that has been
used for this case previously.  "faulted" speaks for the data
(data loss), while "offline" speaks for availability of the data
(access). FSA has been fixed to handle this new state properly so
it is possible to:
1. create pod with mounted volume (on a different node than nexus),
2. bring the node with nexus down,
3. delete pod with the mounted volume,
4. recreate the pod with the same volume again.
This gives a chance to manually recover the volume by the user
action in case that the node with nexus never comes back online.
What happens in the background is that a series of CSI calls …
> fix(moac): cannot unpublish nexus on a node that is down

- csi/moac/csi.ts
- csi/moac/replica.ts
- csi/moac/test/csi_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
This avoids some failure recovery scenarios that would be
difficult to handle otherwise. App and nexus are either both up
or down. If they are down, then k8s restarts the application on a
different node. That triggers unpublish and publish calls that
allow mayastor CSI plugin to move the nexus along with the app to
the new node. In the future, the restriction to run both on the
same node may be lifted once we provide redundancy at the nexus
level.
What users need to do to take advantage of this new code
improving stability? At this time they need to run stateful apps
strictly on storage nodes using any of the provided mechanisms
to influence k8s scheduler decisions (i.e. nodeSelector). In the
future, they won't need to do anything as the node affinity for
apps will be set by the CSI …
> feat(moac): nexus and app must run on the same node if possible

- Jenkinsfile
- nix/lib/version.nix
- scripts/release.sh
The default length of the short commit can vary.
We use this to tag images so need have a definite length.
> test(e2e): set the short commit length

- Jenkinsfile
The default behaviour is to pull from the CI registry.
Ensure the continuous run still pulls from dockerhub.
This is done by replacing the URI parameter in --registry
with the keyword 'dockerhub' which e2e-test.sh recognizes.
> test(e2e): continuous runs need DockerHub images

- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_metadata.rs
Reduce the number of handles created when writing labels (and index).
Restrict knowledge of MetaDataIndex in labelling code to only two methods:
- generate_and_write_label()
- check_or_write_label()
> chore(nexus): refactor labelling and metadata code

- mayastor/src/bdev/loopback.rs
- mayastor/src/core/bdev.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/pool_grpc.rs
- mayastor/tests/nexus_with_local.rs
If the alias we try to set, is present, we return true rather then
failing the operation.
If the bdev is destroyed, we remove the URI from the alias.
While debugging this i've also decided to remove the tracing
of yield points as they make the calls to noise and have no
real value
> fix(nexus): remove alias from bdevs that are local

- mayastor/src/subsys/config/mod.rs
BUG
If mayastore has multiple pools defined then, in the mayastore YAML config file,
all defined replicas are reported multiple times as belonging to each and every pool.
FIX
Each replica is now reported precisely once under the pool to which it belongs.
> fix(mayastor): replicas are reported incorrectly for multiple pools

- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/handle.rs
- mayastor/src/bdev/nvmx/utils.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/nvme.rs
- mayastor/tests/nexus_multipath.rs
Implement NexusChild::resv_register() which sends an NVMe
Reservation Register command as an NVMe IO Passthru command via
BlockDeviceHandle::{nvme_resv_register,io_passthru} when adding a
new child or when creating a nexus with children, though only to NVMe
child devices.
Add a Rust integration test, tacked on to nexus_multipath as that
already sets up a remote child, to verify that the key has been
registered.
Use a hard-coded key for now as this just lays the groundwork for
subsequent commits to acquire the reservation.
Fixes CAS-849
> feat(nexus): register an NVMe reservation on adding a child

- mayastor/src/bdev/nexus/nexus_io.rs
Currently incoming READ I/O is not completed in case of submission
error, which might happen when the underlying I/O qpair is disconnected
in response to network errors. That leads to lost I/O on initiator.
> fix(nexus): io completed in case of submission errors

- csi/src/dev.rs
- csi/src/dev/iscsi.rs
- csi/src/dev/nbd.rs
- csi/src/dev/nvmf.rs
- csi/src/node.rs
When the node with nexus target is down or isn't accessible for any
reason, one have to wait for 10-15 minutes with default linux settings
until the IO error is propagated back to the consumer of the volume
(i.e. app or filesystem). By setting ctrl_loss_tmo to ioTimeout from
storage class, we give the control over this to user. If ioTimeout is
not set in SC then default linux settings apply.
Resolves: CAS-823
> feat(csi): ctrl_loss_tmo should be set to ioTimeout from SC

- chart/templates/moac-deployment.yaml
- csi/moac/.gitignore
- csi/moac/crds/mayastorvolume.yaml
- csi/moac/csi.ts
- csi/moac/index.ts
- csi/moac/moac
- csi/moac/package.json
- csi/moac/test/csi_test.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/index.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/tsconfig.json
- csi/moac/volume.ts
- csi/moac/volume_operator.ts
- csi/moac/volumes.ts
- csi/src/node.rs
- deploy/fio.yaml
- deploy/moac-deployment.yaml
- deploy/storage-class.yaml
- test/grpc/test_csi.js
We want to support late binding of mayastor volumes because we can
optimize distribution of the volume over the nodes. In particular we
can enforce that the nexus and one of the replicas is created on
the same node as the app when creating the volume.
There is a new storage class parameter "local" that enforces the
locality if set to true (the default in our storage class yaml).
If it is not possible to schedule the app on the same node as nexus
and replica and "local" is enabled, then the pod remains in
unscheduleable state until the user rectifies the situation.
There is one downside of local volumes though. Once the node
affinity is set during the volume creation it cannot be changed
later. Assuming that all nodes holding original replicas of the
volume would be removed from the …
> feat(csi): support WaitForFirstConsumer for mayastor volumes

- chart/templates/moac-deployment.yaml
- deploy/moac-deployment.yaml
- deploy/storage-class.yaml
fixes: https://github.com/openebs/Mayastor/issues/822
Currently application deployments on mayastor volumes are not adhering to fsGroups, 
due to which the mount points are not always writable. This is because there is no 
fsType set by default.   fsType should either be mentioned in the storage class or 
should be set by default in csi provisioner container. fsType defined in Storage class 
overrides this default.
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L391
Signed-off-by: Payes Anand <payes.anand@mayadata.io>
> fix(fstype): add default fstype to csi provisioner container

- mayastor/src/core/thread.rs
- mayastor/src/subsys/nvmf/mod.rs
Use the associated output rather than enforcing Result<T, E> for these futures
> chore(thread): clean up thread guards

- csi/moac/crds/mayastorpool.yaml
- csi/moac/pool_operator.ts
- csi/moac/test/pool_operator_test.js
When MOAC restarts it checks the pool resources and may then attempt to
create pools based on specs, which could cause it to recreate pools on
different nodes for instance, if the user had modified the SPEC.
This change "caches" the original spec in the status part of the
resource which then MOAC refers to, rather then the resource SPEC.
Also, if a disk URI (retrieved from mayastor) is available, always use that one.
If a SPEC change is detected, then tag a message on the MSP reason
alerting the user to the fact that it will be ignored. It is removed
if the user reverts the SPEC to the original.
Resolves CAS-855
> fix: disregard msp spec modifications

- composer/src/lib.rs
- mayastor/src/core/bdev.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/replica.rs
- mayastor/src/subsys/config/mod.rs
- mayastor/tests/replica_uri.rs
Adds a UUID as a query parameter to the replica's URI making it uniquely identifiable.
The nexus create will then be able to associate a child with a state, retrieved from etcd,
using the URI, and thus avoid having to open the child and retrieve a GUID from the metadata,
if said child is not in a healthy state.
> feat: make replica URI's unique

- .gitignore
- mayastor/src/bin/mayastor.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/runtime.rs
- mayastor/src/core/thread.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/tests/thread.rs
- nix/pkgs/libiscsi/default.nix
- nix/pkgs/libspdk/default.nix
- nix/pkgs/mayastor/cargo-package.nix
- shell.nix
Mayastor has its own futures which are driven by polling of the "green" threads.
If however, we want to do something which does not need or can run on the
mayastor cores, we can dispatch it to a foreign runtime.
Additionally this also fixes a bug where we where interacting with the nvmf
target from an invalid thread.
> feat(core): provide handle to external runtime

- csi/moac/nexus.ts
- csi/moac/test/nexus_test.js
- csi/moac/test/volumes_test.js
- csi/moac/volume.ts
- csi/moac/volumes.ts
This solves the problem when nexus publish fails because create nexus
grpc call fails, but the publish operation is still waiting for
completing the publish. There is nothing that would trigger a new run
of FSA so it waits indefinitely (until k8s unpublishes the volume).
The same problem applies to create, unpublish and destroy operations
too. We introduce a new delegation mechanism for notifying blocked
callers about errors that may happen in FSA. FSA itself is responsible
for interpretting failures and notifying potential consumers.
Another improvement is that if the failure does not have any consumer
so we cannot rely for example on k8s to retry the operation, there is
a timer 30s that triggers a new run on fsa, so the operation will not
be stuck forever.
Note that if the operation …
> fix(moac): propagate errors from FSA to callers

- mayastor/src/subsys/mbus/mod.rs
- mayastor/src/subsys/mbus/registration.rs
- mbus-api/src/lib.rs
- mbus-api/src/mbus_nats.rs
- test/grpc/test_nats.js
NATS messages get queued by the nats client and so we may not get an error when we try
to send a message. So, attempt to flush the queue after each send with a default timeout
of 5 seconds. If the flush fails then we'll log the error. Subsequent sends will then be
failed by the NATS client until such a time connection is reestablished.
Also add connect/disconnect logging to the NATS server.
> fix: add error message when we fail to send registration hb

- Jenkinsfile
Increase timeout from 3 to 5 hours for long nightly runs.
A recent test exceeded 3 hours without hanging.
> test(e2e): extend timeout as tests are being added

- Jenkinsfile
Nightly e2e runs should run against the build
tagged with the git sha, not nightly.
Use new nightly profile for nightly runs.
> test(e2e): nightly test git sha

- Jenkinsfile
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/handle.rs
- mayastor/src/core/io_device.rs
- mayastor/src/core/mod.rs
1. Added support of fail-fast I/O completion for proper I/O error propagation.
2. Concurrent Nexus retire operations are now serialised and get executed
sequentially in case different replicas experience I/O errors at the same
time.
3. I/O submission errors can now also trigger device retire (solves edge cases
when I/O channels are dropped concurrently by reset operation, triggered
by I/O-unrelated operations (admin queue timeouts, etc).
4. Fixed a few misbehaviours in generic retire logic (like retiring healthy
replicas in response to I/O errors from the faulty replica).
Implements CAS-868, CAS-865, CAS-866
> fix(nexus): retire replicas in response to I/O errors

- csi/moac/.gitignore
- csi/moac/event_stream.js
- csi/moac/index.ts
- csi/moac/node.ts
- csi/moac/package.json
- csi/moac/registry.ts
- csi/moac/rest_api.js
- csi/moac/test/csi_test.js
- csi/moac/test/event_stream_test.js
- csi/moac/test/index.js
- csi/moac/test/nats_test.js
- csi/moac/test/node_operator_test.js
- csi/moac/test/pool_operator_test.js
- csi/moac/test/registry_test.js
- csi/moac/test/rest_api_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volume_test.js
- csi/moac/test/volumes_test.js
- csi/moac/tsconfig.json
Users can control how often are synchronized the storage nodes and
when storage node moves to offline state. This is important even
more now as we still haven't implemented events from storage nodes
to the control plane.
The parameters are propagated from index to registry where they are
used for creating new node objects. While touching the registry code
it has been converted to typescript.
Resolves: CAS-85
> feat(moac): new options for sync of storage nodes

- Jenkinsfile
now that XRay failures do not fail the build.
> test(e2e): re-enable XRay

- csi/moac/volume.ts
- csi/moac/volume_operator.ts
If msn is removed from the cluster (can happen when mayastor on the
node restarts), then certain operations in volume and volume operator
can fail trying to reference the node structure that is being
disassociated with the object (nexus/replica). So handle these cases
gracefully.
Resolves: CAS-902
> fix(moac): moac should handle node removals better

- csi/moac/index.ts
- csi/moac/logger.js
- csi/moac/mbus.js
- csi/moac/node-packages.nix
- csi/moac/node_operator.ts
- csi/moac/package-lock.json
- csi/moac/package.json
- csi/moac/pool_operator.ts
- csi/moac/test/csi_test.js
- csi/moac/test/index.js
- csi/moac/test/nats_test.js
- csi/moac/test/nexus_test.js
- csi/moac/test/node_operator_test.js
- csi/moac/test/node_test.js
- csi/moac/test/pool_operator_test.js
- csi/moac/test/pool_test.js
- csi/moac/test/registry_test.js
- csi/moac/test/replica_test.js
- csi/moac/test/volume_operator_test.js
- csi/moac/test/volumes_test.js
- csi/moac/test/watcher_test.js
- csi/moac/volume_operator.ts
- csi/moac/watcher.ts
The dependency update fixes a couple of sec vulnerabilities.
We switched back to official k8s client as all our fixes have been
merged to the upstream.
dirty-chai was removed because it's not possible to write TS tests
(definitions are different than expected). Instead we ignore the
eslint error which was why we started to use dirty-chai originally.
> feat(moac): update dependencies etc

- csi/moac/test/volume_operator_test.js
- csi/moac/volume_operator.ts
The problem was that the objects (old and new one) were basically
the same except that order of entries in replicas array was different.
Problem #1 is that we do useless update of CR and #2 is that k8s
does not emit mod event in such case so volume-operator was timing
out waiting for the event.
The fix is to enforce deterministic order of entries in replicas
array so that deep-equal compares the objects correctly.
> fix(moac): timeouts when updating volume custom resource

- csi/moac/volume.ts
- csi/moac/volumes.ts
fix: don't complete volume destroy until it's done
Don't complete the destroy if the replicas have not been deleted or if
the nexus info entry is not deleted from etcd.
fix: don't succeed volume creation if it failed
When the volume creation fails we attempt to delete the volume. Before
this is complete we leave the volume in limbo and another create could
be tricked into an update, thus completing the CSI call with success.
To avoid this, check that the volume is not pending, unknown or
destroyed before allowing a volume update.
There is still an issue with this logic: if the destroy fails during
creation then nothing else will attempt the destroy again, leaving us
with a destroyed volume in the list, meaning the volume will get
stuck...
> fix: don't succeed volume creation if it failed

- mayastor/src/bdev/nvme.rs
- mayastor/src/bdev/nvmf.rs
- mayastor/src/bdev/nvmx/channel.rs
- mayastor/src/subsys/config/opts.rs
- nix/pkgs/libspdk/default.nix
- test/grpc/test_nexus.js
Sync with upstream changes to bdev_nvme_create(), bdev_nvme_delete(),
spdk_nvme_poll_group_create(), and spdk_sock_impl_opts.
The nbd code has moved on so the reversion of commit d2704a0 had to be
dropped. This causes the create, publish, un-publish, destroy of an
nbd nexus test in test_nexus.js to fail so skip all nbd tests there as
nbd is not supported anyway.
Also cherry-pick da976633 ("nvmf: delay remove subsystem cb until no
qpairs remain")
Fixes CAS-831, CAS-914
> feat: build against SPDK 21.04

- csi/moac/src/grpc_client.ts
- csi/moac/src/nexus.ts
- csi/moac/src/node.ts
- csi/moac/src/pool.ts
- csi/moac/src/registry.ts
- csi/moac/src/replica.ts
- csi/moac/src/volume.ts
- csi/moac/test/grpc_client_test.js
- csi/moac/test/mayastor_mock.js
- csi/moac/test/node_test.js
- csi/moac/test/pool_test.js
For some reason which is out of scope of this PR, mayastor fails to
send a reply to grpc request issued by moac. That makes the whole
life-cycle of the volume stuck until the moac is restarted. It's
a general problem pertaining to all grpc operations. We need to
set a timeout on all grpc requests to prevent this from happening.
The default timeout for all grpc calls is 15s now. The destroy
replica call with timeout of 1 hour being exception because it is
known to be slow when the replica is large.
This might trigger new bugs in mayastor as some operations might
be resent now. It is a question of how mayastor will handle a new
request while the old one is still in the progress. We will fix
those as we discover them. This could have happened even before.
It's just that likelyhood has …
> fix(moac): volume remains in destroyed state

- csi/moac/src/volume.ts
- mayastor/src/bdev/loopback.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/nexus_uri.rs
- mayastor/tests/nexus_with_local.rs
fix(moac): use filtered replicaSet
During the volume's fsa, MOAC filters out replicas which are not shared properly but it then
uses the unfiltered list to determine which replicas it should add to a nexus.
This could cause a nexus to have 2 bdev children.
Fix: use the filtered replicaSet
fix: don't add the same loopback device to the nexus
Other device types return an error when we attempt to open them twice.
The loopback's are special cases, because they're already open, eg: we
create a replica and then open the loopback device.
When a loopback device is reopened with a different UUID it ends up
overwriting the existing UUID and returning OK which sounds very bad.
Fix: Fail the open request if the UUID is not the expected one.
Related issue, because opening an existing loopback succeeds …
> fix: don't readd existing children to the nexus

- mayastor/src/core/descriptor.rs
- mayastor/tests/nexus_multipath.rs
Removing a loopback replica that is already shared over nvmf should
result in the replica remaining shared over nvmf. NexusChild::close()
calls Descriptor::unclaim() which marks the bdev as unclaimed, causing
the replica to lose its shared state. When the replica is subsequently
destroyed, the nvmf target remains, though with no namespaces, and is
leaked.
Have Descriptor::unclaim() only unclaim a bdev that was claimed by
NEXUS_MODULE. Only test code calls Descriptor::claim().
This issue was always present but could previously only be exposed by
adding a replica over loopback, then sharing that replica over nvmf.
After changes in 347d37a, an already-shared replica could be added as
a local (loopback) child, making it more likely.
Add a cargo test to verify that the loopback replica remains …
> fix(nexus): removing a loopback replica that is already shared

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nvmx/controller_inner.rs
Add a NexusInitialising error which is returned when creating a nexus if
a nexus with the same name already exists and is initialising.
Additional changes: minor typo fixes.
> chore: add additional error

- spdk-sys/build.sh
Iscsi initiator module was accidentally removed from spdk build process
in the latest commits, which leads to missing 'delete_iscsi_disk'
function when building custom spdk.
This fix re-adds the removed module to the resulting spdk binary.
> fix(spdk): restored iscsi initiator module in spdk binary

- mayastor/src/bdev/nexus/nexus_label.rs
- mayastor/src/bdev/nexus/nexus_metadata.rs
- mayastor/tests/nexus_metadata.rs
Do not create a metadata index on the "MayaMeta" partition for persisting
state of each child, as this information is now stored in etcd.
> chore(mayastor): remove code to create metadata index on "MayaMeta" partition

- terraform/main.tf
- terraform/mod/libvirt/main.tf
- terraform/mod/lxd/main.tf
- terraform/variables.tf
These can be overridden with -var="name=$value" via the cmdline.
> chore: add memory and vcpu variables to terraform

- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/server.rs
- test/python/test_null_nexus.py
gRPC requests are received on the tokio runtime and dispatched to the
reactors by sending it a message. This made us run requests
in parallel which is what we want to avoid.
Additionally, the embedded json-rpc server only checks for incoming
messages every N ms. This change also makes the adopt that model by
holding the lock while it sleeps.
The lock implemented is an RW lock so we can make it more relaxed later
if we need to.
> feat(nexus): serialize gRPC requests

- scripts/generate-deploy-yamls.sh
This means we can further customize the generated yaml's without having to modify
the chart's values.yaml files.
> feat(helm): allow caller to specify additional variable or file

- chart/templates/csi-daemonset.yaml
- chart/values.yaml
- csi/src/dev.rs
- csi/src/dev/nvmf.rs
- csi/src/server.rs
- deploy/csi-daemonset.yaml
If this parameter is set, the csi server will set the parameter on startup.
The io_timeout value on the storage class overrides this value and that
should work, but we're not 100% sure that it works for all kernel
versions. This value should cover the cases when the SC value does not
work.
Added a 30s timeout value to the charts. A user may choose to comment
the value out of the yaml to preserve existing settings.
> feat: add nvme_core module io_timeout parameter to the csi server

- chart/develop/values.yaml
- chart/release/values.yaml
- chart/templates/mayastor-daemonset.yaml
- chart/test/values.yaml
Enable RUST_LOG=trace for develop and test images, avoid on release
images.
Does it make sense? Should help in cases when errors are not easily repeatable.
> feat(yaml): enable mayastor trace for some images

- test/python/common/fio_spdk.py
- test/python/common/hdl.py
- test/python/docker-compose.yml
- test/python/test_multi_nexus.py
- test/python/test_nexus.py
- test/python/test_nexus_create_destroy.py
Fix docker-compose config so that container ms3 starts on a system
with only 8 cores.
Add a new test that creates 2 replicas shared over nvmf, 1 as
loopback. Create a nexus with all 3 replicas, then destroy the nexus,
for 10 repetitions.
Update the FioSpdk class to match the interface of Fio so that it
supports multiple filenames and add copies of existing Fio tests that
use FioSpdk instead, which removes the requirement for another VM.
> test(python): add a nexus create/destroy test and update FioSpdk

- Jenkinsfile
Change the default to not run e2e tests.
This is to allow the nightly tests to generate develop
images for use by the new nightly-stable pipeline.
> test(e2e): change default for e2e testing to off

- csi/moac/src/volume.ts
- csi/moac/src/volume_operator.ts
- csi/moac/src/volumes.ts
When a volume is being destroyed, it may not have any replicas or nexuses but we still need to
delete the MSV, so make sure we don't exit early.
Add all of the msv event "del" logic to the serialization queue, otherwise it could be ran before
the "new" event has been processed.
Skip volume update for faulted volumes.
Don't import volumes which are already created. This happens right after a volume is created,
which is an unfortunate side effect, so we can just skip it.
Don't show throw invalid extending volume error when the volume size has not yet been set.
> fix(msv): multiple fixes to the msv logic

- mayastor/tests/nvme_device_timeout.rs
Depending on timing, if the KeepAlive is triggered before we've submitted the read IO,
the controller could be failed and the IO will fail before getting submitted.
This is likely because we now don't reset and retry to connect and simply fail the controller.
In case of early error check that the error is what we expected for this case.
> fix(test): io_timeout_reset fails too early

- csi/moac/src/volume.ts
- csi/moac/test/volumes_test.js
- mayastor/tests/nvme_device_timeout.rs
On create the state was being directly set, leading to a missing mod event.
fixes: CAS-948
> fix: missing mod event on immediate creation

- mayastor/src/bdev/device.rs
- mayastor/src/bdev/mod.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/handle.rs
- mayastor/src/bdev/nvmx/mod.rs
- mayastor/src/core/env.rs
- create functions to initialise io_ctx mempools to be called explicitly on startup
- add command line options to override the size of each mempool
resolves CAS-952
> chore(mayastor): allow size of io_ctx mempools to be configurable

- csi/moac/src/nats.ts
- csi/moac/src/node.ts
- csi/moac/src/node_operator.ts
- csi/moac/src/registry.ts
- csi/moac/test/nats_test.js
- csi/moac/test/node_operator_test.js
- csi/moac/test/node_stub.js
- csi/moac/test/registry_test.js
The problem was that the mayastor unregistered itself and node object
was removed from moac's internal state before all events related to
offlining the node could be processed. One of the previous complaints
about msn records was that they disappear whenever the storage node
is rebooted which is confusing for users. This fix is addressing both
issues at once. Instead of removing the node upon deregistration, it
disconnects the grpc client and switches the node to offline state.
So it stays around along with all other objects that might be on the
node (pools, replicas, nexuses) and events can be processed as
normally. The obvious downside is that users have to remove msn
records manually in case they know that the storage node will never
join the cluster again. But that's just a small …
> fix(moac): volume gets stuck in offline state when doing failover

- mayastor/src/subsys/config/opts.rs
Upstream SPDK defaults to 4 for MaxR2TPerConnection, not 64, so
"PDU Pool" was 16X larger than it needs to be.
Fixes: 682e802 ("mayastor: Build against SPDK 20.10")
> fix(iscsi): use correct upstream default for MaxR2TPerConnection

- deploy/mayastorpoolcrd.yaml
It should have been removed when moac was removed from the repo.  We
can live without the link because pool crd is created by moac when it
starts. People who wish to create pools before the moac is fully up
and running can employ different methods (i.e. waiting in loop until
the definition of crd appears or wait until moac liveness probe
confirms that moac has been fully started).
> fix: remove broken symlink to pool CRD

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nvmx/controller_inner.rs
- mayastor/src/bdev/nvmx/handle.rs
- mayastor/src/core/block_device.rs
- mayastor/src/core/mod.rs
- mayastor/src/core/nvme.rs
- mayastor/tests/nexus_multipath.rs
- nix/pkgs/mayastor/cargo-package.nix
- nix/pkgs/mayastor/default.nix
- nix/pkgs/mayastor/units.nix
- spdk-sys/build.rs
- spdk-sys/wrapper.h
Refactor the existing reservation key code such that both code paths
that add a child call NexusChild::acquire_write_exclusive(), which
sends an NVMe Reservation Acquire command to acquire a write exclusive
reservation on the child, then a Reservation Report command to verify
that the reservation has been acquired, followed by with another
Reservation Acquire command to preempt an existing reservation, if
another host has it.
Add a test to verify that, refactoring the existing nexus_multipath
test as well as disabling it as the write exclusive reservation means
only one Nexus can write to a replica.
Fixes CAS-850
> feat(nexus): acquire write exclusive reservation on adding a child

- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/uri.rs
- mayastor/tests/nexus_multipath.rs
Allow the MAYASTOR_NVMF_HOSTID environment variable to override the
default randomly generated 128-bit extended host identifier used by
the nvmx NVMf client with an optionally-hyphenated UUID string.
Overriding that also overrides the host NQN as SPDK usually derives
the host NQN from the host ID, unless the host NQN has also been
overridden.
Extend the NVMe reservation acquire test to verify that the host
adding the child has indeed acquired the write exclusive reservation.
Fixes CAS-856
> feat(nvmx): allow configurable extended host ID

- Cargo.lock
- Cargo.toml
- csi/Cargo.toml
- csi/src/filesystem_vol.rs
- csi/src/format.rs
- csi/src/mount.rs
- csi/src/nodeplugin_svc.rs
- devinfo/Cargo.toml
- devinfo/build.rs
- devinfo/src/blkid/mod.rs
- devinfo/src/blkid/partition.rs
- devinfo/src/blkid/probe.rs
- devinfo/src/lib.rs
- devinfo/src/mountinfo/mod.rs
- devinfo/src/partition/mod.rs
- devinfo/wrapper.h
- mayastor/src/logger.rs
- nix/pkgs/mayastor/cargo-package.nix
- test/grpc/test_csi.js
By not pulling in dependencies from git directly we can get rid of the
need to calculate the sha and use nix builtins.
The git dependencies we used where:
- h2 (to fix a k8s issue)
- partition_id
- blkid
The changes to h2 are perhaps not needed anymore as the newer k8s
clients should have the issue of authority IDs fixed.
To get around the partition and blkid dependencies, I've implemented
the required pieces myself basing it those crates which are not
actively maintained.
> ci(fix): remove the need to specify cargosha256

- mayastor/src/bin/mayastor-client/controller_cli.rs
- mayastor/src/grpc/controller_grpc.rs
- mayastor/src/grpc/mayastor_grpc.rs
- rpc/proto/mayastor.proto
- test/python/README.md
- test/python/common/hdl.py
- test/python/common/msclient.py
- test/python/common/util.py
- test/python/test_cli_controller.py
This commit introduces a new CLI command for obtaining I/O statistics for
NVMe controllers: 'controller stats'.
Also implemented a test helper for exposing mayastor CLI to Python BDD tests
in a handy manner.
Implements CAS-950
> feat(cli): cli command for nvme controller statistics

- test/python/common/nvme.py
- test/python/test_ana_client.py
Added new testcases to validate that client properly sees virtual
controllers, correct path status and namespace NGUID when connected
to a multipath nexus.
Fixes CAS-981, CAS-982
> test(py): new ana testcases for virtual controller and namespace

- test/python/test_ana_client.py
Added new testcase to validate that I/O policy for a multipath nexus
is NUMA.
Fixes CAS-980
> test(py): new ana testcase for checking io policy

- Cargo.lock
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_rebuild.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/controller_state.rs
- mayastor/src/bin/mayastor-client/context.rs
- nix/lib/rust.nix
- nix/pkgs/images/default.nix
- nix/pkgs/mayastor/cargo-package.nix
- nix/sources.json
- shell.nix
This removes the test binaries from the container image as they are not needed.
Also, add /bin to PATH and wrap mayastor-client to mctl.
Lastly, the mozilla-overlay isn't very flexible to use. Switch to a
more flexible overlay which, for example, does not take forever to copy
HTML files when building images.
The second commit bumps cargo deps.
> chore(build): rust-overlay and container image

- nix/pkgs/images/default.nix
- nix/pkgs/libspdk/default.nix
- nix/pkgs/mayastor/cargo-package.nix
All the containers in fact use the same images. So the CSI agent should
actually be part of that.
> fix(build): ship mayastor-csi in container

- test/python/features/nexus.feature
- test/python/test_bdd_nexus.py
- test/python/test_nexus_publish.py
- roughly translated from test/grpc/test_nexus.js
- also added non-bdd tests which tests create/publish/unpublish/destroy
sequence of operations for each of the main protocols
- resolves CAS-968
> test(py): add pytest-bdd feature tests for nexus

- mayastor/src/grpc/nexus_grpc.rs
- test/grpc/test_nexus.js
In nexus_lookup(), search for a nexus with the name as-is first, to
allow UUID-as-name created nexuses to be found, before falling back to
using uuid_to_name() for v1 created Nexuses that have a "nexus-<uuid>"
type name.
Fixes CAS-1021
> fix(grpc): allow UUID as name for CreateNexusV2

- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/tests/nexus_multipath.rs
- test/python/docker-compose.yml
- test/python/test_nexus_multipath.py
Change the NVMe reservation type to write exclusive, all registrants,
which allows all registrants (any host that registers a key, any key),
write access to the replica. This also treats all registrants as
reservation holders.
Update the existing nexus_resv_acquire cargo test to verify that both
nexuses are registered to the replica's NVMe target. Add a python test
to verify that using the kernel NVMe initiator.
Fixes CAS-973
> feat(nexus): allow 2nd nexus to connect to replica

- mayastor/src/bdev/nexus/nexus_persistence.rs
Switch the key for persisting NexusInfo to the nexus bdev UUID, which
is specified when creating the nexus using CreateNexusV2 and is unique
cluster-wide.
Fixes CAS-1023
> fix(nexus): persist NexusInfo to etcd using nexus UUID

- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/nexus_grpc.rs
- rpc/proto/mayastor.proto
- test/python/test_ana_client.py
list_nexus_v2() gRPC call now provides ANA state for a nexus.
Fixes CAS-978
> feat(nexus): nexus list should report ana state

- mayastor/src/bin/mayastor-client/replica_cli.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/lvs/lvs_pool.rs
- mayastor/tests/lvs_pool.rs
- mayastor/tests/replica_snapshot.rs
- rpc/proto/mayastor.proto
- test/python/common/hdl.py
- test/python/features/replica-guid.feature
- test/python/test_replica_uuid.py
fix(mayastor): add support of uuid and name as separate replica proprties
Added new gRPC methods to support separately UUID and name for replica
creation and enumeration.
Fixes CAS-1036
> fix(mayastor): add support of uuid and name as separate replica proprties

- Jenkinsfile
Stop pytests (temporarily) while the node upon which the agent resides
is repurposed as a "hypervisor" node.
> chore: temporarily disable pytest stage in jenkins pipeline

- mayastor/src/bdev/aio.rs
- mayastor/src/bdev/malloc.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/src/bdev/null.rs
- mayastor/src/bdev/nvme.rs
- mayastor/src/bdev/nvmf.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/controller_inner.rs
- mayastor/src/bdev/nvmx/uri.rs
- mayastor/src/bdev/uring.rs
- mayastor/src/core/bdev.rs
- mayastor/src/core/channel.rs
- mayastor/src/core/share.rs
- mayastor/src/core/thread.rs
- mayastor/src/lvs/lvol.rs
- mayastor/src/lvs/lvs_pool.rs
- mayastor/src/subsys/config/opts.rs
- mayastor/tests/nexus_multipath.rs
- nix/pkgs/libspdk/default.nix
- scripts/check-coredumps.sh
- spdk-sys/wrapper.h
- test/python/test_nexus_multipath.py
Build mayastor against SPDK 21.07. This fixes heap corruption when a 
nexus is unpublished or destroyed whilst an NVMe client is still 
connected to it.
The upgrade required fixes to leaked bdev aliases and corrects the use
of spdk_nvme_probe_poll_async().
Fixed CAS-1042, CAS-1056.
> feat: build against SPDK 21.07

- test/python/docker-compose.yml
- test/python/test_nexus_multipath.py
Test destroying a nexus whilst under IO load with 3 paths.
Test making both paths inaccessible whilst under IO load, then restore one path.
Fixes CAS-976, CAS-977, CAS-983
> test(python): multipath failover scenarios

- test/python/README.md
- test/python/setup.sh
This change allows the python tests to to be configured and run manually.
In order to run them in CI will require changes to the Jenkins pipeline
to include  submodules in the checkout.
> fix(pytest): update setup.sh to reflect new location of mayadata.proto

- .github/workflows/pr-commitlint.yml
- mayastor/tests/common/mod.rs
- mayastor/tests/core.rs
- mayastor/tests/nexus_multipath.rs
- mayastor/tests/nexus_rebuild.rs
Originally I aimed to also remove `etcd` from the default `nix-shell` as part of this based [on Jeffrey's advice in my previous PR](https://github.com/openebs/mayastor/pull/1004#discussion_r695568965) but for some reason the `persistence` tests fail to find the `etcd` binary when it's from the host and not nix. After spending some hours trying to debug that, I gave-up.
> Two random minor improvements

- scripts/pytest-tests.sh
- test/python/common/fio.py
- test/python/common/mayastor.py
- test/python/test_ana_client.py
- test/python/test_bdd_nexus.py
- test/python/test_bdd_nexus_multipath.py
- test/python/test_bdd_pool.py
- test/python/test_bdd_rebuild.py
- test/python/test_bdd_replica.py
- test/python/test_cli_controller.py
- test/python/test_common.py
- test/python/test_config.ini
- test/python/test_multi_nexus.py
- test/python/test_nexus.py
- test/python/test_nexus_multipath.py
- test/python/test_nexus_publish.py
- test/python/test_null_nexus.py
- test/python/test_replica_uuid.py
- test/python/test_rpc.py
Include all current pytests in scripts/pytest-tests.sh.
Identify, and temporarily disable, those tests that
are currently failing and require additional work.
> chore(test): validate remaining pytest tests

- mayastor/src/lvs/lvol.rs
Improve the performance of replica creation/destruction by:
1. Increasing the size of the buffer used to wipe the superblock from 4K to 64K.
2. Wiping the superblock on creation only.
> chore: speed up replica creation/destruction

- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bdev/nvmx/controller.rs
- mayastor/src/bdev/nvmx/controller_inner.rs
- mayastor/tests/nexus_multipath.rs
- mayastor/tests/nvme_device_timeout.rs
- mayastor/tests/persistence.rs
- test/python/tests/nexus/test_nexus.py
Handle it by scheduling a future once, and only once, to destroy the
device if spdk_nvme_ctrlr_process_admin_completions() returns an
error, usually -ENXIO if the remote child is unreachable when
handling admin commands such as keep-alive.
This means an unreachable remote child on an idle nexus is now noticed
and the child is marked as degraded. In the case where the nexus is
under IO load and 2 remote replicas are unreachable at almost the same
time, both replicas are now consistently degraded.
Fixes CAS-941
> fix(nvmx): handle failures from processing completions for admin comands

- chart/templates/csi-daemonset.yaml
- chart/templates/mayastor-daemonset.yaml
Use mayastor image as host for mayastor-csi for CI testing.
Use the "command" field in the yamls for mayastor and mayastor-csi to specify unambiguously which binary to run.
Part of PR #1007 moved to separate PR as requested in review.
This relates to mq-1989.
> test(e2e): use mayastor image for mayastor-csi daemonset

- terraform/mod/k8s/repo.sh
This makes "reboot" behave as a "hard rest" from a container standpoint.
> fix(k8s): workaround for long shutdown bug

- Jenkinsfile
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_child.rs
- mayastor/src/bin/mayastor-client/nexus_cli.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/tests/nexus_multipath.rs
- test/python/common/hdl.py
- test/python/tests/nexus/test_nexus.py
- test/python/tests/nexus_multipath/test_bdd_nexus_multipath.py
- test/python/tests/nexus_multipath/test_nexus_multipath.py
Pass through the preempt key from NexusCreateV2 to the reservation
acquire command that is sent to replicas when a nexus is created and
change the acquire action to preempt if the preempt key is non-zero,
otherwise it remains as acquire.
Add a test to check that a preempted nexus is no longer allowed to
write to replicas.
Fixes CAS-851
> feat(nexus): handle preempt key in NexusCreateV2

- chart/templates/csi-daemonset.yaml
- chart/values.yaml
- csi/src/dev.rs
- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_persistence.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/nexus_grpc.rs
- mayastor/tests/nexus_io.rs
- scripts/grpc-test.sh
fix(nexus_v2): add uuid field to the nexus
The CreateV2 was changed to use uuid's but all the lookups are made using
the name, even though the arg is called uuid...
This should be properly addressed as part of 1107 but for now use the
workaround of looking up by uuid if by name fails.
When a nexus is published the NQN is set to the name but the namespace uuid's are
set to the nexus UUID. This breaks the CSI plugin logic, as it expects them to be
the same...
As a WA for the moment, when using the V2 api set the bdev uuid to match
the name, if the name is a UUID. The uuid arg is then used as a means to identify
the nexus only.
This means the nqn and the namespace uuid is now using the nexus name, which in
case of the control plane on k8s, is the volume uuid.
Also tidiy up some corner cases …
> fix(nexus_v2): add uuid field to the nexus

- mayastor/src/bdev/nvmx/channel.rs
- mayastor/src/bdev/nvmx/controller.rs
- test/python/tests/nexus/test_remote_only.py
Implement Tiago's fix by essentially holding a reference to the nvmx controller in channel, giving it up on channel shutdown, and waiting in controller::device_destroy() until it holds the only reference before dropping the controller.
Fixes CAS-1177
> fix(nvmx): delay controller destruction until channels have been destroyed

- .gitignore
- mayastor/src/grpc/mayastor/v1.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/mod.rs
- mayastor/src/grpc/server.rs
- mayastor/src/grpc/v1/pool.rs
- mayastor/src/lvs/lvs_pool.rs
- mayastor/src/lvs/mod.rs
- mayastor/src/pool.rs
- mayastor/src/subsys/config/pool.rs
- mayastor/tests/lvs_pool.rs
- mayastor/tests/nexus_io.rs
- mayastor/tests/replica_snapshot.rs
- rpc/Cargo.toml
- rpc/build.rs
- rpc/src/lib.rs
- scripts/pytest-tests.sh
- test/grpc/test_replica.js
- test/python/setup.sh
- test/python/tests/replica/features/pool.feature
- test/python/tests/replica/test_bdd_pool.py
- test/python/v1/hdl.py
- test/python/v1/mayastor.py
- test/python/v1/pool/docker-compose.yml
- test/python/v1/pool/features/pool.feature
- test/python/v1/pool/test_bdd_pool.py
- adds the implementation of mayastor v1 service for Pool.
- adds separate rpcs to import and export pools
- operations on non-existing pool will return an error instead of null
Signed-off-by: shubham <shubham14bajpai@gmail.com>
> feat(grpc): add mayastor v1 service for pools

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_bdev_children.rs
- mayastor/src/bdev/nexus/nexus_channel.rs
- mayastor/src/bdev/nexus/nexus_io.rs
- mayastor/src/bdev/nexus/nexus_share.rs
- mayastor/src/core/mod.rs
This PR is a follow-up for #1052. It fixes a couple of things that I forgot to do in the original commit.
Mark BdevContainer (spdk-rs) and Nexus structures as "non-unpinnable". This leads to several fixes in Nexus use (replacing &mut self with Pin<&mut Self>). If a struct is not explicitly marked with marker::PhantomPinned, Rust assumes it is unpinnable and one can easily get a &mut to it. We don't want that for Bdev contexts, Nexus struct instances in particular.
Some trivial clean-ups of things like excessive "pub" use, etc.
Please also review the spdk-rs submodule part of this commit: mayadata-io/spdk-rs#2.
> fix(mayastor): prevent auto-unpin of nexus

- mayastor/src/bdev/nexus/nexus_bdev.rs
Resuming already unpaused nexus is now allowed (results in no-op)
and triggers no assertion, which simplifies high-level logic for
nexus suspend/resume clients.
Fixes CAS-1256
> fix(nexus): assertion failure in nexus_bdev resume()

- nix/pkgs/mayastor/cargo-package.nix
Mayastor binary had an incorrect RPATH set at fixup phase of
image build. The fixup was needed after SPDK linkage was
refactored, but RPATH subsitution was done incorrectly at
that time.
> fix(ci): fixed rpath in matastor docker image

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_persistence.rs
In case the last replica fails, it is not marked as not healthy
in the ETCD, which allows Caontrol Plane to recover the nexus later
without ambiguity (as the replica with the most recent user data
remains known).
Resolves: CAS-1284
> fix(nexus): do not persist faulted state of the last replica

- mayastor/src/lvs/lvol.rs
Fixed use of Lvol name after it has been freed.
This partially fixes CAS-1258.
Fixes CAS-1258
> fix(lvol): referring lvol name after destroy

- mayastor/src/bdev/nvmx/channel.rs
- mayastor/src/subsys/config/opts.rs
Added NVMF_TCP_MAX_QPAIRS (includes adminq) to control the max number of qpairs per controller.
Why this may be useful? Example, if mayastor is configured with 2 cores but the hosts have 32 cores.
This may create an unbalanced configuration as mayastor will only use 2 IO qpairs to the replicas.
This is an initial approach that allows a user to easily configure how many qpairs the initiator
host may use.
> chore: add env variable to control max number of qpairs

- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_io_subsystem.rs
Suspend/resume operations on NVMe subsystems are now serialised for nexuses,
which properly handles simultaneous I/O suspension/resume operations
in case multiple replicas get retired at the same time.
Resolves: CAS-1285
> fix(nexus): serialised nexus i/o suspend/resume

- chart/templates/mayastor-daemonset.yaml
Rather than adding 1Gi extra just set 2Gi as the minimum.
> chore: update charts to add 2Gi as a minimum hugepages

- chart/templates/mayastor-daemonset.yaml
- deploy/mayastor-daemonset.yaml
Limiting the qpairs to a low value means we cannot then allocate more for the rebuilds.
> chore: don't add default max qpairs per controller

- Cargo.lock
- chart/templates/_helpers.tpl
- chart/templates/mayastor-daemonset.yaml
- composer/Cargo.toml
- csi/Cargo.toml
- deploy/csi-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- devinfo/Cargo.toml
- jsonrpc/Cargo.toml
- mayastor/Cargo.toml
- mayastor/src/bdev/nexus/mod.rs
- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_io_subsystem.rs
- mayastor/src/bdev/nexus/nexus_persistence.rs
- mayastor/src/bdev/nvmx/channel.rs
- mayastor/src/subsys/config/opts.rs
- mbus-api/Cargo.toml
- nvmeadm/Cargo.toml
- rpc/Cargo.toml
- spdk-sys/Cargo.toml
- sysfs/Cargo.toml
- Removes -P argument from the mayastor container
spec, as the use of a local pool config store
has been deprecated and conflicts with the
control plane's state store
- Removes the same from the pre-generated
mayastor-daemonset definition in the /deploy
folder, which is referenced in the user docs
> fix(helm chart): remove local pool config store

- mayastor/src/bdev/nexus/nexus_bdev.rs
- mayastor/src/bdev/nexus/nexus_persistence.rs
- mayastor/src/bin/mayastor-client/nexus_cli.rs
- mayastor/src/grpc/mayastor_grpc.rs
- mayastor/src/grpc/v1/nexus.rs
- mayastor/tests/nexus_io.rs
Provide the ability to receive a key under which the NexusInfo structure
should be persisted. If provided by the control plane, this key will be
used otherwise it will default to the nexus UUID to ensure backwards
compatibility.
> feat(nexus info key): use supplied key if present

- Cargo.lock
- Cargo.toml
- ci.nix
- libnvme-rs/Cargo.toml
- libnvme-rs/build.rs
- libnvme-rs/src/error.rs
- libnvme-rs/src/lib.rs
- libnvme-rs/src/nvme_device.rs
- libnvme-rs/src/nvme_tree.rs
- libnvme-rs/src/nvme_uri.rs
- libnvme-rs/wrapper.h
- mayastor/Cargo.toml
- mayastor/tests/mount_fs.rs
- mayastor/tests/nexus_io.rs
- mayastor/tests/persistence.rs
- nix/mayastor-overlay.nix
- nix/pkgs/libnvme/default.nix
- nix/sources.json
- shell.nix
New crate that uses the libnvme development C library. Reuse NvmeTarget, and some NvmeErrors, from nvmeadm and implement connect and disconnect to an NVMe-oF target, and list connections using libnvme.
Fixes CAS-1218, CAS-1217
Starts on CAS-1220
> feat(libnvme-rs): new crate, implement connect, disconnect, list

- nix/pkgs/mayastor/cargo-package.nix
Its cargo.toml turns out to be a dependency when building the image
though it's only used for Mayastor cargo tests.
> fix: add libnvme-rs to cargo-package

- Jenkinsfile
Ensure the correct source code is used to build the images. This should
ensure that the latest images are pushed to the registry.
> fix(Jenkins): build correct images

- Jenkinsfile
Before running the python tests ensure that all existing containers are
destroyed. This will ensure that the python tests are run in a clean
environment.
It has been observed on CI that if containers are left around (due to
previous test failures) subsequent python tests will fail. The error
message will look like:
"compose.project.ProjectError: Encountered errors while bringing up the
project."
> fix(python tests): cleanup containers

- chart/templates/mayastor-daemonset.yaml
- deploy/mayastor-daemonset.yaml
- nix/pkgs/libspdk/default.nix
Fix build on arm64 platform. Intel-ipsec-mb lib is only specific to
x64_64 platform.
And Mayastor can run on arm64 now, not just x86_64.
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>
This PR is related to Mayastor arm64 support: https://github.com/openebs/mayastor/issues/1063
> fix(build): fix arm64 build

- nix/pkgs/libspdk/default.nix
This update intends to include arm build fixes.
Update SPDK to the top tip of branch v22.01.x-mayastor with the
output of cmd: "nix-prefetch-git --fetch-submodules --rev
refs/heads/v22.01.x-mayastor git@github.com:openebs/spdk.git"
Update spdk-rs to the latest branch develop
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>
This PR is related to Mayastor arm64 support: https://github.com/openebs/mayastor/issues/1063
> chore(spdk): update spdk

- io-engine/src/bin/io-engine.rs
- io-engine/src/core/env.rs
- io-engine/src/logger.rs
Default logger output format can be hard to follow because each line
has a verbose prefix of date, time and code location.
For development purposes, a alternative compact format is introduced.
> feat(logger): adding compact log output format

- ci.nix
- io-engine/tests/persistence.rs
- shell.nix
By using the path directly we avoid being stopped at our tracks by the sudoers security.
Resolves: #1158
Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>
> fix(etcd): setup etcd tests with path from nix environment

- io-engine/src/grpc/v1/replica.rs
- scripts/pytest-tests.sh
- test/python/cross-grpc-version/nexus/docker-compose.yml
- test/python/cross-grpc-version/nexus/features/nexus.feature
- test/python/cross-grpc-version/nexus/test_bdd_nexus.py
- test/python/cross-grpc-version/pool/docker-compose.yml
- test/python/cross-grpc-version/pool/features/pool.feature
- test/python/cross-grpc-version/pool/test_bdd_pool.py
- test/python/cross-grpc-version/rebuild/docker-compose.yml
- test/python/cross-grpc-version/rebuild/features/rebuild.feature
- test/python/cross-grpc-version/rebuild/test_bdd_rebuild.py
- test/python/cross-grpc-version/replica/docker-compose.yml
- test/python/cross-grpc-version/replica/features/replica.feature
- test/python/cross-grpc-version/replica/test_bdd_replica.py
- Adds BDD tests for pool operations with v1 gRPC calls on top of v0 versioned pools to check for backward compatibility
- Adds BDD tests for nexus operations with v1 gRPC calls on top of v0 versioned nexus to check for backward compatibility
- Adds BDD tests for rebuild operations with v1 gRPC calls on top of v0 versioned replica to check for backward compatibility
- Adds BDD tests for replica operations with v1 gRPC calls on top of v0 versioned replca to check for backward compatibility
Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
> chore(ci): add BDD tests to check cross compatability between v0 & v1 gRPC versions
